project:
  type: manuscript
  output-dir: docs
  
manuscript: 
 article: manuscript_GNM.qmd
 
format: 
 html:
  comments: 
   hypothesis: true

crossref:
  custom:
    - kind: float
      key: figsupp
      latex-env: figsupp
      reference-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure
      
 # docx: default
 # pdf: default

      
execute:
 freeze: auto
 cache: false
 notebook: false

editor: visual

