project:
  type: manuscript
  output-dir: docs
  
manuscript: 
 article: manuscript_GNM.qmd

 
format: 
 html:
  comments: 
   hypothesis: true
  bibliography: references.bib
 # docx:
 #  fontsize: 12
 # pdf: default

crossref:
  custom:
    - kind: float
      key: figsupp
      latex-env: figsupp
      reference-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure
    - kind: float
      key: tabsupp
      latex-env: tabsupp
      reference-prefix: Table S
      space-before-numbering: false
      latex-list-of-description: Supplementary Tables
    - kind: float
      key: figmain
      latex-env: figmain
      reference-prefix: "Figure "
      space-before-numbering: false
      latex-list-of-description: Article Figures
    - kind: float
      key: tabmain
      latex-env: tabmain
      reference-prefix: "Table "
      space-before-numbering: false
      latex-list-of-description: Article Tables

      
execute:
 freeze: auto
 cache: false
 notebook: false

editor: visual

