project:
  type: manuscript
  output-dir: docs
  
manuscript: 
 article: manuscript_GNM.qmd

 
format: 
 html:
  comments: 
   hypothesis: true
  bibliography: references.bib
 # docx: 
 #  fontsize: 12
 # pdf: default

crossref:
  custom:
    - kind: float
      key: figsupp
      latex-env: figsupp
      reference-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure
      


      
execute:
 freeze: auto
 cache: false
 notebook: false

editor: visual

