project:
  type: manuscript
  output-dir: _output 
  render: 
    - manuscript_GNM.qmd
  
manuscript: 
 article: manuscript_GNM.qmd

title: "Why do birds use green nest material? A systematic review and meta-analysis of experiments"

abstract: |
 Many animals build nests, often considered extended phenotypes that shape survival and reproduction beyond the builder’s body. Birds are key examples of nest builders, and some species add fresh green plant material to their nests. Yet, the adaptive value of this behaviour remains debated. Non-mutually exclusive hypotheses propose roles in courtship signalling, parasite defence, and direct enhancement of offspring condition through pharmacological effects independent of parasite reduction. Here, we conducted a pre-registered systematic review and meta-analysis of 28 experimental studies (published and unpublished), spanning seven bird species and 274 effect sizes, to test whether green nest material enhances fitness and to evaluate competing functional explanations. Our synthesis shows that green nest material can increase fitness in birds that exhibit this behaviour. However, this effect varies depending on the fitness proxy investigated, and its functional role remains inconclusive. We found no clear evidence supporting the courtship, nest protection, or drug hypothesis. Instead, experimental design was the strongest moderator of effect size variation, challenging the role of aromatic compounds in the fitness benefits of green nest material and highlighting the need for further research into the underlying mechanisms.
 
affiliations:
  - id: "1"
    name: Department of Evolutionary Biology, Bielefeld University, Germany
  - id: "2"
    name: Department of Animal Behaviour, Bielefeld University, Germany
  - id: "3"
    name: CNC, Center for Neuroscience and Cell Biology, University of Coimbra, Portugal
  - id: "4"
    name: CIBB, Center for Innovative Biomedicine and Biotechnology, University of Coimbra, Portugal


authors:
  - name: "Shreya Dimri"
    orcid: 0009-0009-2155-7506
    corresponding: true
    email: shreya.dimri@uni-bielefeld.de
    affiliations: [{ ref: "1" }]
  - name: "Tuba Rizvi"
    orcid: 0009-0008-2051-2165
    affiliations: [{ ref: "1" }]
  - name: "Júlio M.G. Segovia"
    orcid: 0000-0002-6914-012X
    affiliations: [{ ref: "1" }]
  - name: "Meinolf Ottensmann"
    orcid: 0000-0003-3112-6928
    affiliations: [{ ref: "2" }]
  - name: "Alfredo Sánchez-Tójar"
    orcid: 0000-0002-2886-0649
    affiliations: [{ ref: "1" }, { ref: "3" }, { ref: "4" }]    

    

crossref:
  custom:
    - kind: float
      key: figsupp
      latex-env: figsupp
      reference-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure
    - kind: float
      key: tabsupp
      latex-env: tabsupp
      reference-prefix: Table S
      space-before-numbering: false
      latex-list-of-description: Supplementary Tables
    - kind: float
      key: figmain
      latex-env: figmain
      reference-prefix: "Figure"
      space-before-numbering: true
      latex-list-of-description: Article Figures
    - kind: float
      key: tabmain
      latex-env: tabmain
      reference-prefix: "Table"
      space-before-numbering: true
      latex-list-of-description: Article Tables

    
bibliography: references.bib

format:
  html:
    comments: false
    csl: apa.csl
  preprint-typst:
    output-file: GNM_Preprint1
    theme: jou
    running-head: "Preprint"
    layout:
    - spacing: 0.6em
    typst-blocks: |
      #set page(margin: (x: 2, y: 2))
      #set text(size: 10pt)
    include-before-body:
     - text: |
          #set text(size: 10pt)
          #show figure: it => {
            set text(size: 6pt);
            it
          }
          #show table: it => {
            set text(size: 6pt);
            it
          }
    citeproc: true
    line-number: false
    csl: apa.csl
    
  elsevier-pdf:
    output-file: GNM_Submission1
    journal:
     name: "Proceedings of the Royal Society B - Biological Sciences"
     formatting: review
     layout: onecolumn
     cite-style: number
    typst-block: |
     #set par(line-numbering: true)
    include-in-header: 
      text: |
        \newpageafter{author}
        \usepackage{lineno}
    include-before-body:
      text: |
        \linenumbers
    margin-top: 3cm
    margin-bottom: 3cm
    margin-left: 2.5cm
    margin-right: 2.5cm
    keep-tex: true
    csl: proceedings-of-the-royal-society-b.csl
  
  docx:
    output-file: GNM_Supervisor1
    journal:
     name: "Proceedings of the Royal Society B - Biological Sciences"
     formatting: review
     cite-style: number
    citeproc: true
    csl: proceedings-of-the-royal-society-b.csl

execute:
 freeze: auto
 cache: false
 notebook: false

editor: visual

