{
  "hash": "5356b0a9c829c2c3a4ab6cfe12d7770a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"WORKING TITLE: The adaptive value of green nest material across birds: A systematic review and meta-analysis\"\nauthors:\n  - name: Shreya Dimri\n    affiliation: Department of Evolutionary Biology, Bielefeld University, Bielefeld, Germany\n    corresponding: true\n  - name: Tuba Rizvi\n    affiliation: Department of Evolutionary Biology, Bielefeld University, Bielefeld, Germany\n  - name: Júlio Segovia\n    affiliation: Department of Evolutionary Biology, Bielefeld University, Bielefeld, Germany\n  - name: Alfredo Sánchez-Tójar\n    affiliation: Department of Evolutionary Biology, Bielefeld University, Bielefeld, Germany\n    \nbibliography: references.bib\n---\n\n::: {.cell .hidden}\n\n```{.r .cell-code .hidden}\ndevtools::install_github(\"daniel1noble/orchaRd\", ref = \"main\", force = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nUsing GitHub PAT from the git credential store.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nDownloading GitHub repo daniel1noble/orchaRd@main\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n── R CMD build ─────────────────────────────────────────────────────────────────\n* checking for file ‘/private/var/folders/61/lmczt3d923df8ywy3mn788qm0000gn/T/RtmpADXO9K/remotes3656580327/daniel1noble-orchaRd-2892a29/DESCRIPTION’ ... OK\n* preparing ‘orchaRd’:\n* checking DESCRIPTION meta-information ... OK\n* checking for LF line-endings in source and make files and shell scripts\n* checking for empty or unneeded directories\nRemoved empty directory ‘orchaRd/bib’\nRemoved empty directory ‘orchaRd/figures’\n* building ‘orchaRd_2.0.tar.gz’\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\npacman::p_load(readr,tidyverse,metafor,orchaRd)\n```\n:::\n\n::: {.cell .hidden}\n\n```{.r .cell-code .hidden}\n# Own reference list\nown_library <- read_csv(\"data/01_systematic_search/01_search_strategy/own_library_references.csv\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nNew names:\nRows: 15 Columns: 15\n── Column specification\n──────────────────────────────────────────────────────── Delimiter: \",\" chr\n(11): type, title, issn, doi, abstract, language, journal, author, note,... dbl\n(4): ...1, volume, number, year\nℹ Use `spec()` to retrieve the full column specification for this data. ℹ\nSpecify the column types or set `show_col_types = FALSE` to quiet this message.\n• `` -> `...1`\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Systematic search and abstract screening\nunique_reference_list <- read_csv(\"data/unique_reference_list.csv\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRows: 383 Columns: 12\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (9): label, title, author, journal, volume, number, pages, doi, abstract\ndbl (3): year, search_duplicated, n_duplicates\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nfull_reference_before_deduplication<-read_csv(\"data/full_reference_before_deduplication.csv\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nNew names:\nRows: 535 Columns: 65\n── Column specification\n──────────────────────────────────────────────────────── Delimiter: \",\" chr\n(65): label, title, author, journal, volume, number, pages, year, doi, a...\nℹ Use `spec()` to retrieve the full column specification for this data. ℹ\nSpecify the column types or set `show_col_types = FALSE` to quiet this message.\n• `` -> `...11`\n• `` -> `...12`\n• `` -> `...13`\n• `` -> `...14`\n• `` -> `...15`\n• `` -> `...16`\n• `` -> `...17`\n• `` -> `...18`\n• `` -> `...19`\n• `` -> `...20`\n• `` -> `...21`\n• `` -> `...22`\n• `` -> `...23`\n• `` -> `...24`\n• `` -> `...25`\n• `` -> `...26`\n• `` -> `...27`\n• `` -> `...28`\n• `` -> `...29`\n• `` -> `...30`\n• `` -> `...31`\n• `` -> `...32`\n• `` -> `...33`\n• `` -> `...34`\n• `` -> `...35`\n• `` -> `...36`\n• `` -> `...37`\n• `` -> `...38`\n• `` -> `...39`\n• `` -> `...40`\n• `` -> `...41`\n• `` -> `...42`\n• `` -> `...43`\n• `` -> `...44`\n• `` -> `...45`\n• `` -> `...46`\n• `` -> `...47`\n• `` -> `...48`\n• `` -> `...49`\n• `` -> `...50`\n• `` -> `...51`\n• `` -> `...52`\n• `` -> `...53`\n• `` -> `...54`\n• `` -> `...55`\n• `` -> `...56`\n• `` -> `...57`\n• `` -> `...58`\n• `` -> `...59`\n• `` -> `...60`\n• `` -> `...61`\n• `` -> `...62`\n• `` -> `...63`\n• `` -> `...64`\n• `` -> `...65`\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nselected_abstract_screening<-read_csv(\"data/selected_abstract_screening.csv\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRows: 40 Columns: 15\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (11): paper_id, label, title, author, journal, number, pages, doi, abstr...\ndbl  (4): volume, year, search_duplicated, n_duplicates\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# For updated search\nunique_reference_list_repeat <- read_csv(\"data/unique_reference_repeat_12082024.csv\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRows: 53 Columns: 13\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (10): Paper_ID, label, title, author, journal, number, pages, doi, abstr...\ndbl  (3): volume, year, n_duplicates\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nfull_reference_before_deduplication_repeat<-read_csv(\"data/full_reference_repeat_12082024.csv\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nNew names:\nRows: 66 Columns: 22\n── Column specification\n──────────────────────────────────────────────────────── Delimiter: \",\" chr\n(20): label, title, author, journal, number, pages, doi, abstract, ...11... dbl\n(2): volume, year\nℹ Use `spec()` to retrieve the full column specification for this data. ℹ\nSpecify the column types or set `show_col_types = FALSE` to quiet this message.\n• `` -> `...11`\n• `` -> `...12`\n• `` -> `...13`\n• `` -> `...14`\n• `` -> `...15`\n• `` -> `...16`\n• `` -> `...17`\n• `` -> `...18`\n• `` -> `...19`\n• `` -> `...20`\n• `` -> `...21`\n• `` -> `...22`\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nselected_abstract_screening_repeat<-read_csv(\"data/selected_abstract_screening_repeat.csv\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRows: 4 Columns: 15\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (10): Paper_ID, label, title, author, journal, pages, doi, abstract, scr...\ndbl  (4): volume, number, year, n_duplicates\nlgl  (1): notes\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# For fulltext screening\nexcluded_fulltext <- read_csv(\"data/excluded_fulltext.csv\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nNew names:\nRows: 19 Columns: 51\n── Column specification\n──────────────────────────────────────────────────────── Delimiter: \",\" chr\n(25): paper_ID, fulltext_screening, fulltext_notes, variable_note, autho... dbl\n(16): ...1, year_publication, experiment_ID, group_ID, repeated_trait_ID... lgl\n(10): control_plant_species, proxies_sign, statistics_type, test_statist...\nℹ Use `spec()` to retrieve the full column specification for this data. ℹ\nSpecify the column types or set `show_col_types = FALSE` to quiet this message.\n• `` -> `...1`\n```\n\n\n:::\n:::\n\n\n\n\n# Methods\n\n## Registration and Reporting\n\nWe pre-registered our study protocol on Open Science Framework [@dimri2024] prior to data exploration and analysis. The pre-registration details the study's objectives, a priori hypotheses and predictions, methods and planned data analyses. Unless stated otherwise, we adhered to the registered protocol. We followed the PRISMA-EcoEvo guidelines [@odea2021] for reporting this study (@figsupp-checklist). All resources associated with this study, including data and code, are available at \\[<https://github.com/shreyadimri/Green_Nest_Material>\\] (insert Zenodo citation later).\n\n## Information source and search\n\nWe conducted a systematic search on Web of Science Core Collection and Scopus on 07.09.2022. The keyword search query was designed in three blocks to included terms for predictor/treatment (\"green\\*\" OR \"herb\\*\" OR \"aromatic\\*\") AND \"nest\\*\"), population of interest (\"bird\\*\" OR \"aves\" OR \"avian\" OR \"ornithol\\*\" OR \"passerine\\*\" OR \"passeriform\\*\" OR \"songbird\\*\" OR list of all bird genera) and only experimental studies (\"experiment\\*\" OR \"manipulat\\*\") (for a complete search string tailored to specific database see @figsupp-string). We searched the title, abstract and keywords in English-language only, with no restrictions on publication date or study type. We found 383 unique articles after removing 152 duplicates using R package 'revtools' v0.4.1 (@westgate2019). We validated our search using an initial library of 15 relevant articles (@figsupp-own-library), ensuring all were retrieved. Additionally, we used R package 'litsearchr' v1.0.0 (@grames2019) to confirm our keyword selection, which did not yield any new relevant terms.\n\n## Eligibility criteria\n\nAll title and abstract screening were screened independently by atleast two screeners (\\~66% each by SD, TR, JMGS) following a pre-designed decision tree (@figsupp-decision-tree) in `revtools`. We included all studies on birds that experimentally manipulated the green nest material (including aromatics or herbs). 40 articles passed title and abstract screening and further evaluated in a fulltext screening by a single screener (\\~33% each by SD, TR, JMGS) and double checked by another. We used the same criteria as above with an additional evaluation of whether the variable of interest in the article was a fitness proxy. 19 articles were excluded and all conflicts in screening decisions (\\~1% disagreement for title and abstract screening and none for fulltext screening) were resolved through discussion.\n\nWe repeated our search using the same search string on 12.08.2024 and found 66 additional articles. After de-duplicating, SD screened the title and abstract for the 53 unique articles using the same decision tree. We found 1 article by updating our search. In addition, we identified 3 articles through other sources that were not a part of our search. These studies met our inclusion criteria and were added to our meta-analysis. The exact number of screened and included studies along with reasons of exclusion are shown in @figsupp-prisma-flowchart.\n\n## Data Extraction\n\n\n\n\n::: {.cell .hidden}\n\n```{.r .cell-code .hidden}\nmerged_data_extraction <- read_csv(\"data/03_data_cleaning/merged_data_extraction.csv\", show_col_types = F)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nNew names:\n• `` -> `...1`\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ndataset_after_cleaning <- merged_data_extraction %>% filter(fulltext_screening!=\"excluded\")\nincluded_papers_no<-length(unique(dataset_after_cleaning$paper_ID))\n\n# Numbers for extraction ID\ndata_extractors <- merged_data_extraction %>%\n     distinct(paper_ID, .keep_all = TRUE) %>%\n     select(paper_ID, extractor_ID) %>%\n     mutate(extractor_ID = case_when(\n    extractor_ID == \"JS/SD/TR\" ~ \"TR/JMGS/SD\",\n    TRUE ~ extractor_ID)) %>%\n     group_by(extractor_ID) %>%\n     summarise(total_papers = n(), .groups = \"drop\")\n\nexcluded_proxies<- dataset_after_cleaning %>% filter(proxy_decision==\"exclude\")\nSAonly_proxies<- dataset_after_cleaning %>% filter(proxy_decision==\"senstivity-analysis\" | proxy_decision==\"sensitivity-analysis\")\n```\n:::\n\n\n\n\nData was extracted evenly by one of the three authors (\\~33% each SD, TR and JMGS) and was checked by another to ensure correctness of the data. We extracted the primary data (i.e., measures of central tendency and variance) from text whenever possible. In cases where primary data was only available in figures (such as boxplots), we used `metaDigitise` v.1.0.1 (@pick2018). If primary data was not available, we extracted any inferential statistics (t-test, F-statistics) that could be used to calculate an effect size. In cases where the values could not be extracted from the article but datasets were provided, we calculated the means, SD and sample sizes from the raw data. When data was presented in different sources, we prioritized the source having the maximum resolution.\n\nTo obtain any missing data and to locate any grey literature, we wrote to the corresponding author of the articles that passed fulltext screening using a standardized email template (\\@figsupp-email). We contacted 4 authors for missing data, while the rest were asked for any potential unpublished data. All four authors responded to our email- 2 provided the data as requested, one did not have the data any more and one did not give a conclusive response. One author provided unpublished data. Another unpublished data was provided by the author of this study (MO). We extracted data for 24 published articles and 2 unpublished studies.\n\nWe extracted mean, variance and sample size for a control-treatment pairwise comparison. Controls included non-aromatic materials (e.g., grass, moss), lesser amounts of aromatic material, or no material. Treatments consisted of aromatic materials added by authors, birds, or both. In cases comparing non-aromatic material to a blank nest, the non-aromatic material was considered the treatment. We recorded the type of comparison being made as a moderator.\n\nFor each study we also extracted information related to the study subjects (species of birds, location of the study population), the methodology of the study (plant species used as treatment and control, trait measured) and information about the extracted data (location or source of the data recorded). We categorized the trait measured into 6 broad categories - physiology, morphology, reproduction, behaviour, parasite and pathogenic load, phenology. In cases where the trait measured was a type of parasite or pathogen, we categorised the parasite studied into arthropods or micro-organisms. For a complete list of variables extracted see @figsupp-variables . We excluded some traits (k=10 , n=3) measured from all our analysis because it was unclear how they related to fitness (see @figsupp-excluded-proxies for the list and reason of exclusion). We also had to exclude some fitness proxies (n=?, k=?) because of the low sample size per group (less than x).\n\n## Effect size calculation\n\n\n\n\n::: {.cell .hidden}\n\n```{.r .cell-code .hidden}\ninferential_stats<-dataset_after_cleaning%>%filter(statistics_type==\"t-test\"|statistics_type==\"ANCOVA\")\n\ncontingency_table<-dataset_after_cleaning%>%filter(proxy_decision==\"contingency table\")\n\nno_ES<-dataset_after_cleaning%>%filter(proxy_comment == \"use 0 as ES\")\n\nnegative_lnRR<-dataset_after_cleaning%>%\n  filter(measure_central_tendency_experiment<=0 | measure_central_tendency_control<=0)\n```\n:::\n\n\n\n\nWe calculated two effect sizes for each pairwise comparison-log response ratio (lnRR) and standardised mean difference with heteroskedasticity correction (SMDH), using `escalc` function (`measure= ROM` and `SMDH` respectively, `vtype= \"LS\"`) in `metafor` package (@metafor). We specified the treatment group as the numerator and the control group as the denominator for lnRR and treatment minus control for SMDH, such that the positive values indicate the trait value increased in the treatment group. In cases such as measures of parasite load or prevalence, laying or hatching dates, courtship time, scab score etc., the sign was inverted to ensure comparability across all fitness proxies. In all cases, the effect sizes were coded such that the fitness proxies were positively correlated with the overall fitness.\n\nFor studies reporting only inferential statistics (e.g., t-tests, ANCOVA), we estimated SMD values (k=4, n=2) using the equations provided by @thehand2019 . In cases of dichotomous variables (e.g., successful nests, k=3, n=1) we used the data to calculate log odds ratio using `escalc` function (`measure=OR`) and convert it to SMD using equations from @thehand2019. Since lnRR cannot be calculated from inferential statistics or dichotomous variables, only SMD under the assumption of homoscedasticity was derived from such data. We excluded these effect sizes along with any zero or negative values (k=8, n=5) when calculating lnRR.\n\nThe sample sizes used were the number of nests in each group, and not the number of individuals, whenever possible. In cases where the control or treatment group was used repeatedly across multiple comparisons, sample sizes were adjusted by dividing them by the number of times each group was used in the comparison, to account for shared group non-independence. For the cases where the authors reported no significant difference between the two groups (n=16, k=2) but did not provide the values, we used zero as the effect size. To impute the SD for these cases, we used the missing-case approach following @nakagawa2022.\n\n## Data Analysis\n\nWe performed analysis in R version 4.3.0 (@positteam2023). All multilevel meta-analytical models and meta-regressions were fit using `metafor v.4.8-0` (@metafor). Sampling variances were modelled as variance-covariance matrices assuming a 0.5 correlation (ρ) between sampling variances from the same study [@noble2017] using `vcalc` function. (See Supplementary Appendix @figsupp-correlation for sensitivity analysis using different values of correlation (ρ)).\n\nOur data had various sources of non-independence which we accounted for using random effects. We considered the following level of non-independence- (a) multiple effect sizes were collected from same study (Paper ID), (b) some bird species (species ID) and (c) some geographical locations (population ID) were studied multiple times, (d) some sub-populations (Experiment ID e.g. birds studied at the same location for multiple years or birds studied at the same location separated by distance) and (e) group of individuals (Group ID, eg. males and females in a population, first clutch and second clutch) were represented in our data several times and (f) repeated traits collected on the same group of animals (repeated trait ID e.g. chick mass on day 7, 14 and 21).\n\nWe fitted the following random effects in all our models unless stated otherwise- Paper ID, Group ID, Species ID, Population ID and an observation-level random effect (Observation ID). Initially we had pre-registered the inclusion of Experiment ID and repeated trait ID and not population ID. Experiment ID and group ID were almost indistinguishable, as such we decided to leave out the one with lesser resolution i.e. Experiment ID. Additionally, we observed that not many effect sizes were measured repeatedly, making the repeated trait ID very similar to the observation ID. After exploring the overlap (@figsupp-random-effect), we decided to only keep observation ID. We added population ID, which accounts for many effect sizes from different studies coming from the same geographical location.\n\n### Meta-analytical models for biological predictions\n\nTo estimate the overall effect of green nest material addition to the nest on fitness across bird species that perform this behaviour, we fitted two separate multilevel intercept-only meta-analytical models using lnRR or SMDH as dependent variables. We used the `rma.mv` function from the `metafor` package using the 'REML' method. Test statistics and confidence intervals for the fixed effects were computed using t distribution. We used the entire dataset for this analysis except some traits (k=21 , n=8; see @figsupp-SAonly_proxies for details) that we decided to exclude from all our analysis due to lack of evidence supporting their relationship with fitness. However, we also conducted a sensitivity analysis (@figsupp-MLMA-excluded) including these proxies to ensure robustness of our results. In the model using SMDH, We estimated total amount of heterogeneity ($𝜎^2$; the variation not explained by the sampling error), its sources (or relative heterogeneity; $I^2$), mean-standardised metric ($CVH2$) and variance-mean-standardised metric of heterogeneity ($M2$) (@yang2025).\n\nTo test the effect of green nest material on reproductive success (courtship hypothesis) and on protective effects and health benefits for the nestling (Parental care hypothesis), we ran a multilevel meta-regression with 'hypothesis' (Courtship hypothesis, Parental care hypothesis, Both) as a moderator. using the entire dataset. For this and all meta-regressions, we estimated $R_{marginal}^2$, the percentage of heterogeneity explained by the moderators (@nakagawa2012) using the entire dataset.\n\n### Meta-regressions for exploratory analysis\n\nWe performed additional pre-registered multi-level meta-regressions for which we did not have clear or strong directional predictions on specific subsets of data. To understand the effect of green nest material on the parasite load depending on the type of parasites, we used effect sizes on parasites and pathogens (n=?, k=?). We ran a meta-regression with a type of parasite as a moderator (levels: arthropod, micro-organism). We also ran a meta-regression with with the entire dataset set using bird species as a moderator (levels: Cyanistes caeruleus, Sturnus unicolor, Tachycineta bicolor, Sturnus vulgaris, Parus major, Passer cinnamomeus, Buteo buteo) to understand if the effect of green nest material on fitness depended on the system being studied. To test the effect of time of addition of green nest material on the fitness outcome (levels: before egg hatching, after egg hatching, continuously throughout the nesting phase) we ran a meta-regression with Time of addition of green nest material as the moderator. We explored the effect of green nest material on fitness depending on the type of trait studies (levels:physiology, morphology, reproduction, behaviour, parasite and pathogenic load, phenology) using a meta-regression with the trait type as a moderator. We explored the impact of methodological differences on the relationship between green nest material and fitness. To understand the effect of type of experimental design (i.e. whether the authors compared - non-aromatic vs. aromatic, no added material vs. aromatic, no added material vs. non-aromatic), we ran a meta-regression with type of experimental design as the moderator.\n\n### Publication Bias Test\n\nPublication bias is the higher likelihood of a subset of research findings, such as statistically significant results, being published as compared to the rest. We tested for evidence of publication bias (following @nakagawa2021) for both lnRR and SMDH separately. To test for small study effects, we ran meta-regression , using the inverse of effective sample size as a moderator. To understand the decline effect (also known as time-lag bias) we ran another meta-regression with a mean-centered publication year as a moderator.\n\n# Results\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ndataset_analysis <- read_csv(\"data/03_data_cleaning/dataset_analysis.csv\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nNew names:\nRows: 288 Columns: 72\n── Column specification\n──────────────────────────────────────────────────────── Delimiter: \",\" chr\n(35): paper_ID, fulltext_screening, variable_note, authors, population_l... dbl\n(36): ...1, year_publication, Observation_ID, experiment_ID, group_ID, r... lgl\n(1): fulltext_notes\nℹ Use `spec()` to retrieve the full column specification for this data. ℹ\nSpecify the column types or set `show_col_types = FALSE` to quiet this message.\n• `` -> `...1`\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nES_per_study<-dataset_analysis%>%group_by(paper_ID)%>%count(paper_ID)\n\nbirds_info<-dataset_analysis%>%group_by(bird_species)%>%count(bird_species)\nbirds_info$perc<-(birds_info$n/nrow(dataset_analysis))*100\n```\n:::\n\n\n\n\nWe obtained 288 effect sizes from 28 studies, published between 1988-2024. The mean (±SD) number of effect sizes per study was 10.3 ± 7.34, with a range of 2--33 effect sizes per study. Median and mean sample sizes per effect size were 10 and 15.6 respectively (range: 1-- 111; 14 effect sizes had a sample size less than 2 in each group). The studies were conducted on 7 species across 20 locations. About 81% of the effect sizes come from three bird species (Cyanistes caeruleus, k = 79; Sturnus unicolor, k = 60; Sturnus vulgaris, k = 95).\n\n**Does addition of green nest material have an adaptive function?**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nintercept_lnRR<-readRDS(here::here(\"model/intercept_lnRR.rds\"))\nintercept_SMDH<-readRDS(here::here(\"model/intercept_SMDH.rds\"))\n```\n:::\n\n\n\n\nThe intercept only meta-analytic model using the log response ratio (lnRR) estimated a 1.5% increase in fitness in nests with green nest material across bird species \\[Figure ; lnRR = 0.015, 95% CI: \\[-0.014, 0.044\\], 95% PI: \\[-0.277, 0.307\\], p-value = 0.31, k = 252, n = 26\\]. The total heterogeneity (𝜎2) was estimated at 0.022 (Q = 2350.224, p \\< 0.001). Measures of relative heterogeneity (I^2^~total~ = 98.4%) and standardized heterogeneity (mean-standardized: CV~total~ = 9.8 and variance-mean-standardized: M~total =~ 0.91) suggested high variability across effect sizes. Using standardized mean difference (SMDH) as an alternate effect size, the intercept only meta-analytic model estimated a small positive but statistically significant effect of green nest material on fitness \\[Figure ; SMDH = 0.172, 95% CI: \\[0.042, 0.302\\], 95% PI: \\[-0.83, 1.174\\], p-value = 0.01, k = 258, n = 26\\]. Total heterogeneity was higher in case of SMDH (𝜎^2^= 0.254 Q = 1124.787, p \\< 0.001). and the relative heterogeneity was substantially reduced (I^2^~total~ = 65.8%). The standardized heterogeneity (CV~total~ = 2.93 and M~total =~ 0.75) remained high. While lnRR and SMDH differ in their scale, both effect sizes suggest a small but positive effect of green nest material on fitness. These differences in overall effect can stem from the different underlying biological and statistical assumptions. lnRR incorporates the mean difference at a multiplicative scale whereas SMDH expresses the difference on an additive scale. The difference in relative heterogeneity between the two effect sizes aligns with broader trends observed in meta-analysis in ecology and evolution (see @yang2024 for more details).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\norchaRd::caterpillars(intercept_lnRR, mod = \"1\", group=\"paper_ID\",xlab = \"Effect size (Log Response Ratio - lnRR)\")\n```\n\n::: {.cell-output-display}\n![](manuscript_GNM_files/figure-docx/unnamed-chunk-3-1.png)\n:::\n\n```{.r .cell-code .hidden}\norchaRd::caterpillars(intercept_SMDH, mod = \"1\", group=\"paper_ID\",xlab = \"Effect size (Standardized Mean Difference - SMDH)\")\n```\n\n::: {.cell-output-display}\n![](manuscript_GNM_files/figure-docx/unnamed-chunk-3-2.png)\n:::\n\n```{.r .cell-code .hidden}\nintercept_lnRR_plot <- orchard_plot(intercept_lnRR,\n                                         mod = \"1\",\n                                         group = \"paper_ID\",\n                                         trunk.size = 1,\n                                         branch.size = 2,\n                                         alpha = 0.3,\n                                         twig.size = 1,\n                                         xlab = \"Effect size (Log Response Ratio - lnRR)\",\n                                         colour = \"#218833\",\n                                         fill = T) +\n  scale_fill_manual(values = \"#218833\") +\n  scale_colour_manual(values = \"#218833\") +  \n  theme(legend.direction=\"horizontal\", legend.title = element_text(size =8),\n        legend.text = element_text(size = 10), \n        axis.title = element_text(size = 15),\n        axis.text.x = element_text(size = 15),\n        axis.text.y = element_blank()) +\n  labs(x = \"Intercept\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nScale for fill is already present.\nAdding another scale for fill, which will replace the existing scale.\nScale for colour is already present.\nAdding another scale for colour, which will replace the existing scale.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(intercept_lnRR_plot)\n```\n\n::: {.cell-output-display}\n![](manuscript_GNM_files/figure-docx/unnamed-chunk-3-3.png)\n:::\n\n```{.r .cell-code .hidden}\nintercept_SMDH_plot <- orchard_plot(intercept_SMDH,\n                                         mod = \"1\",\n                                         group = \"paper_ID\",\n                                         trunk.size = 1,\n                                         branch.size = 2,\n                                         alpha = 0.3,\n                                         twig.size = 1,\n                                         xlab = \"Effect size (Standardized Mean Difference - SMDH)\",\n                                         colour = \"#895129\",\n                                         fill = T) +\n  scale_fill_manual(values = \"#895129\") +\n  scale_colour_manual(values = \"#895129\") +  \n  theme(legend.direction=\"horizontal\", legend.title = element_text(size =8),\n        legend.text = element_text(size = 10), \n        axis.title = element_text(size = 15),\n        axis.text.x = element_text(size = 15),\n        axis.text.y = element_blank()) +\n  labs(x = \"Intercept\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nScale for fill is already present.\nAdding another scale for fill, which will replace the existing scale.\nScale for colour is already present.\nAdding another scale for colour, which will replace the existing scale.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(intercept_SMDH_plot)\n```\n\n::: {.cell-output-display}\n![](manuscript_GNM_files/figure-docx/unnamed-chunk-3-4.png)\n:::\n:::\n\n\n\n\n\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\-\\--\n\n## Supplementary Appendix\n\n<details>\n\n<summary>Supplementary materials</summary>\n\n\n\n\n---\nbibliography: references.bib\ncode-fold: true\n---\n\n\n\n::: {#figsupp-checklist}\n| Checklist Item | Sub-item Number | Sub-item | Reported by authors? | Notes |\n|----------------|-----------------|----------|----------------------|-------|\n|                |                 |          |                      |       |\n|                |                 |          |                      |       |\n|                |                 |          |                      |       |\n\nPrisma Eco-Evo Checklist according to @odea2021\n:::\n\n::: {#figsupp-variables}\n| variable name | description | values | Notes |\n|---------------|-------------|--------|-------|\n|               |             |        |       |\n|               |             |        |       |\n|               |             |        |       |\n\nThis is the list of all the variables that were extracted for the purpose of this study\n:::\n\n::: {#figsupp-own-library}\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\npacman::p_load(readr,knitr, dplyr)\nown_library <- read_csv(\"data/01_systematic_search/01_search_strategy/own_library_references.csv\", \n                        show_col_types = F)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nNew names:\n• `` -> `...1`\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nown_library%>% \n  select(c(title,author,doi, journal, year, issn))%>% \n  kable(col.names=(c(\"Article Title\",\"Authors\",\"DOI\", \"Journal\", \"Year of Publication\", \"ISSN\" )),\n        caption = \"Articles from our own library used for validating search strategy\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Articles from our own library used for validating search strategy\n\n|Article Title                                                                                                                         |Authors                                                                                                                                                                                     |DOI                              |Journal                                                  | Year of Publication|ISSN      |\n|:-------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:--------------------------------|:--------------------------------------------------------|-------------------:|:---------|\n|`{Green} incubation': avian offspring benefit from aromatic nest herbs through improved parental incubation behaviour                 |Gwinner, Helga and Capilla-Lasheras, Pablo and Cooper, Caren and Helm, Barbara month = jun,                                                                                                 |10.1098/rspb.2018.0376           |PROCEEDINGS OF THE ROYAL SOCIETY B-BIOLOGICAL SCIENCES   |                2018|0962-8452 |\n|Telomere length and dynamics of spotless starling nestlings depend on nest-building materials used by parents                         |Soler, Juan J. and Ruiz-Castellano, Cristina and Figuerola, Jordi and Martin-Vivaldi, Manuel and Martinez-de la Puente, Josue and Ruiz-Rodriguez, Magdalena and Tomas, Gustavo month = apr, |10.1016/j.anbehav.2017.01.018    |ANIMAL BEHAVIOUR                                         |                2017|0003-3472 |\n|Green plants in nests reduce offspring recruitment rates in the spotless starling                                                     |Polo, Vicente and Rubalcaba, Juan G. and Veiga, Jose P. month = aug,                                                                                                                        |10.1093/beheco/arv056            |BEHAVIORAL ECOLOGY                                       |                2015|1045-2249 |\n|Nest size and aromatic plants in the nest as sexually selected female traits in blue tits                                             |Tomas, Gustavo and Merino, Santiago and Martinez-de la Puente, Josue and Moreno, Juan and Morales, Judith and Rivero-de Aguilar, Juan month = aug,                                          |10.1093/beheco/art015            |BEHAVIORAL ECOLOGY                                       |                2013|1045-2249 |\n|Interacting effects of aromatic plants and female age on nest-dwelling ectoparasites and blood-sucking flies in avian nests           |Tomas, G. and Merino, S. and Martinez-de la Puente, J. and Moreno, J. and Morales, J. and Lobato, E. and Rivero-de Aguilar, J. and del Cerro, S. month = jun,                               |10.1016/j.beproc.2012.02.003     |BEHAVIOURAL PROCESSES                                    |                2012|0376-6357 |\n|Experimental {Addition} of {Green} {Plants} to the {Nest} {Increases} {Testosterone} {Levels} in {Female} {Spotless} {Starlings       |Polo, Vicente and Lopez-Rull, Isabel and Gil, Diego and Veiga, Jose P. month = feb,                                                                                                         |10.1111/j.1439-0310.2009.01724.x |ETHOLOGY                                                 |                2010|0179-1613 |\n|Aromatic plants in nests of the blue tit {Cyanistes} caeruleus protect chicks from bacteria                                           |Mennerat, Adele and Mirleau, Pascal and Blondel, Jacques and Perret, Philippe and Lambrechts, Marcel M. and Heeb, Philipp month = oct,                                                      |10.1007/s00442-009-1418-6        |OECOLOGIA                                                |                2009|0029-8549 |\n|Do female spotless starlings {Sturnus} unicolor adjust maternal investment according to male attractiveness?                          |Lopez-Rull, Isabel and Gil, Diego month = may,                                                                                                                                              |10.1111/j.1600-048X.2009.04553.x |JOURNAL OF AVIAN BIOLOGY                                 |                2009|0908-8857 |\n|Aromatic plants in nests of blue tits: positive effects on nestlings                                                                  |Mennerat, Adele and Perret, Philippe and Bourgault, Patrice and Blondel, Jacques and Gimenez, Olivier and Thomas, Don W. and Heeb, Philipp and Lambrechts, Marcel M. month = mar,           |10.1016/j.anbehav.2008.11.008    |ANIMAL BEHAVIOUR                                         |                2009|0003-3472 |\n|Blue tits ({Cyanistes} caeruleus) respond to an experimental change in the aromatic plant odour composition of their nest             |Mennerat, A. month = nov,                                                                                                                                                                   |10.1016/j.beproc.2008.07.003     |BEHAVIOURAL PROCESSES                                    |                2008|0376-6357 |\n|Experimental addition of greenery reduces flea loads in nests of a non-greenery using species, the tree swallow {Tachycineta} bicolor |Shutler, Dave and Campbell, Adam A. month = jan,                                                                                                                                            |10.1111/j.2007.0908-8857.04015.x |JOURNAL OF AVIAN BIOLOGY                                 |                2007|0908-8857 |\n|European starlings: nestling condition, parasites and green nest material during the breeding season                                  |Gwinner, H and Berger, S month = oct,                                                                                                                                                       |10.1007/s10336-005-0012-x        |JOURNAL OF ORNITHOLOGY                                   |                2005|0021-8375 |\n|Does fresh vegetation protect avian nests from ectoparasites? {An} experiment with tree swallows                                      |Dawson, RD month = jul,                                                                                                                                                                     |10.1139/Z04-076                  |CANADIAN JOURNAL OF ZOOLOGY-REVUE CANADIENNE DE ZOOLOGIE |                2004|0008-4301 |\n|ECTOPARASITISM} {AND} {THE} {ROLE} {OF} {GREEN} {NESTING} {MATERIAL} {IN} {THE} {EUROPEAN} {STARLING                                  |FAUTH, PT and KREMENTZ, DG and HINES, JE                                                                                                                                                    |10.1007/BF00328399               |OECOLOGIA                                                |                1991|0029-8549 |\n|Aromatic plants in blue tit {Cyanistes} caeruleus nests: no negative effect on blood-sucking {Protocalliphora} blow fly larvae        |Mennerat, Adele and Perret, Philippe and Caro, Samuel P. and Heeb, Philipp and Lambrechts, Marcel M. month = mar,                                                                           |10.1111/j.0908-8857.2008.04400.x |JOURNAL OF AVIAN BIOLOGY                                 |                2008|0908-8857 |\n\n\n:::\n:::\n\n\n:::\n\n::: {#figsupp-random-effect}\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# pacman::p_load(readr, dplyr, tidyverse)\n# install.packages(\"devtools\", repos = \"https://cloud.r-project.org/\")\n# devtools::install_github(\"davidsjoberg/ggsankey\")\n# library(ggsankey)\n# analysis_dataset <- read_csv(\"data/03_data_cleaning/dataset_analysis.csv\", \n#                         show_col_types = F)\n# \n# sankey_data <- analysis_dataset %>%\n#   select(Observation_ID,paper_ID, experiment_ID_coded, group_ID_coded, repeated_trait_ID_coded)%>%\n#   mutate(across(c(Observation_ID,paper_ID, experiment_ID_coded, group_ID_coded, repeated_trait_ID_coded), as.character)) %>%\n#   make_long(Observation_ID,paper_ID, experiment_ID_coded, group_ID_coded, repeated_trait_ID_coded)\n# \n# ggplot(sankey_data, aes(x = x, next_x = next_x, node = node, next_node = next_node, fill = factor(node))) +\n#   geom_alluvial(flow.alpha = .6) +\n#   scale_fill_viridis_d(drop = FALSE) +\n#   theme_alluvial(base_size = 18) +\n#   labs(x = NULL) +\n#   theme(legend.position = \"none\",\n#         plot.title = element_text(hjust = .5))\n# \n# sankey_data_birds <- analysis_dataset %>%\n#   select(paper_ID, bird_species, population_ID)%>%\n#   mutate(across(c(paper_ID, bird_species, population_ID), as.character)) %>%\n#   make_long(paper_ID, bird_species, population_ID)\n# \n# \n# ggplot(sankey_data_birds, aes(x = x, \n#                next_x = next_x, \n#                node = node, \n#                next_node = next_node,\n#                fill = factor(node))) +\n#   geom_sankey() +\n#   scale_fill_discrete(drop=FALSE) +\n#   theme(legend.position = \"none\")\n```\n:::\n\n\n:::\n\n::: {#figsupp-string}\nThe search was conducted twice, the first time on 07.09.2022 and then repeated on 12.08.2024 to ensure it was the most up to date and did not miss any additional articles on the topic that were published meanwhile. For both the searches, we did not use any time limitation i.e. it included all the published literature till that given date. We used **Advance Search** option for both Web of Science Core Collection Database and Scopus Database using the search query given below.\\\n\\\nSearch string for the Web of Science Core Collection\\\nDatabases used in the search included\\\n-Science Citation Index Expanded (SCI-EXPANDED) \\[1900-present\\]\\\n-Social Sciences Citation Index (SSCI) \\[1900-present\\]\\\n-Arts & Humanities Citation Index (AHCI) \\[1975 - present\\]\\\n-Conference Proceedings Citation Index - Science (CPCI-S) \\[1991 - present\\]\\\n-Conference Proceedings Citation Index - Social Science & Humanities (CPCI-SSH) \\[1991 - present\\]\\\n-Emerging Sources Citation Index (ESCI) \\[2017- present\\]\\\n\\\nWe used advance search option and Title (TI), Abstract (AB) and Author Keywords (AK) to conduct our systematic search using the following string\\\n\\\n\\<TI=(((\"green\\*\" OR \"herb\\*\" OR \"aromatic\\*\") AND \"nest\\*\" AND (\"bird\\*\" OR \"aves\" OR \"avian\" OR \"ornithol\\*\" OR \"passerine\\*\" OR \"passeriform\\*\" OR \"songbird\\*\" OR \"Accipiter\" OR \"Aegypius\" OR \"Aquila\" OR \"Aviceda\" OR \"Busarellus\" OR \"Butastur\" OR \"Buteo\" OR \"Buteogallus\" OR \"Chondrohierax\" OR \"Circaetus\" OR \"Circus\" OR \"Clanga\" OR \"Elanoides\" OR \"Elanus\" OR \"Gampsonyx\" OR \"Geranoaetus\" OR \"Geranospiza\" OR \"Gypaetus\" OR \"Gypohierax\" OR \"Gyps\" OR \"Haliaeetus\" OR \"Haliastur\" OR \"Harpagus\" OR \"Harpia\" OR \"Hieraaetus\" OR \"Ictinaetus\" OR \"Ictinia\" OR \"Kaupifalco\" OR \"Leptodon\" OR \"Leucopternis\" OR \"Lophotriorchis\" OR \"Milvus\" OR \"Morphnarchus\" OR \"Morphnus\" OR \"Necrosyrtes\" OR \"Neophron\" OR \"Nisaetus\" OR \"Parabuteo\" OR \"Pernis\" OR \"Pithecophaga\" OR \"Polemaetus\" OR \"Pseudastur\" OR \"Rostrhamus\" OR \"Rupornis\" OR \"Sarcogyps\" OR \"Spilornis\" OR \"Spizaetus\" OR \"Stephanoaetus\" OR \"Terathopius\" OR \"Torgos\" OR \"Trigonoceps\" OR \"Cathartes\" OR \"Coragyps\" OR \"Gymnogyps\" OR \"Sarcoramphus\" OR \"Vultur\" OR \"Pandion\" OR \"Sagittarius\" OR \"Aix\" OR \"Alopochen\" OR \"Amazonetta\" OR \"Anas\" OR \"Anser\" OR \"Asarcornis\" OR \"Aythya\" OR \"Branta\" OR \"Bucephala\" OR \"Cairina\" OR \"Callonetta\" OR \"Cereopsis\" OR \"Chen\" OR \"Chenonetta\" OR \"Chloephaga\" OR \"Clangula\" OR \"Coscoroba\" OR \"Cyanochen\" OR \"Cygnus\" OR\"Dendrocygna\" OR \"Heteronetta\" OR \"Histrionicus\" OR \"Hymenolaimus\" OR \"Lophodytes\" OR \"Lophonetta\" OR \"Malacorhynchus\" OR \"Mareca\" OR \"Marmaronetta\" OR \"Melanitta\" OR \"Merganetta\" OR \"Mergellus\" OR \"Mergus\" OR \"Neochen\" OR \"Netta\" OR \"Nettapus\" OR \"Nomonyx\" OR \"Oxyura\" OR \"Plectropterus\" OR \"Polysticta\" OR \"Pteronetta\" OR \"Sarkidiornis\" OR \"Sibirionetta\" OR \"Somateria\" OR \"Spatula\" OR \"Tachyeres\" OR \"Tadorna\" OR \"Thalassornis\" OR \"Anhima\" OR \"Chauna\" OR \"Anseranas\" OR \"Aegotheles\" OR \"Aerodramus\" OR \"Aeronautes\" OR \"Apus\" OR \"Chaetura\" OR \"Collocalia\" OR \"Cypseloides\" OR \"Cypsiurus\" OR \"Hirundapus\" OR \"Panyptila\" OR \"Streptoprocne\" OR \"Tachornis\" OR \"Tachymarptis\" OR \"Hemiprocne\" OR \"Abeillia\" OR \"Adelomyia\" OR \"Aglaeactis\" OR \"Aglaiocercus\" OR \"Amazilia\" OR \"Androdon\" OR \"Anopetia\" OR \"Anthocephala\" OR \"Anthracothorax\" OR \"Archilochus\" OR \"Atthis\" OR \"Augastes\" OR \"Avocettula\" OR \"Basilinna\" OR \"Boissonneaua\" OR \"Calliphlox\" OR \"Calypte\" OR \"Campylopterus\" OR \"Chaetocercus\" OR \"Chalcostigma\" OR \"Chalybura\" OR \"Chlorestes\" OR \"Chlorostilbon\" OR \"Chrysolampis\" OR \"Chrysuronia\" OR \"Clytolaema\" OR \"Coeligena\" OR \"Colibri\" OR \"Cyanophaia\" OR \"Cynanthus\" OR \"Discosura\" OR \"Doricha\" OR \"Doryfera\" OR \"Elvira\" OR \"Ensifera\" OR \"Eriocnemis\" OR \"Eugenes\" OR \"Eulampis\" OR \"Eulidia\" OR \"Eupetomena\" OR \"Eupherusa\" OR \"Eutoxeres\" OR \"Florisuga\" OR \"Glaucis\" OR \"Goethalsia\" OR \"Goldmania\" OR \"Haplophaedia\" OR \"Heliactin\" OR \"Heliangelus\" OR \"Heliodoxa\" OR \"Heliomaster\" OR \"Heliothryx\" OR \"Hylocharis\" OR \"Juliamyia\" OR \"Klais\" OR \"Lafresnaya\" OR \"Lampornis\" OR \"Lamprolaima\" OR \"Lepidopyga\" OR \"Lesbia\" OR \"Leucippus\" OR \"Leucochloris\" OR \"Lophornis\" OR \"Mellisuga\" OR \"Metallura\" OR \"Microchera\" OR \"Myrmia\" OR \"Myrtis\" OR \"Ocreatus\" OR \"Opisthoprora\" OR \"Oreonympha\" OR \"Oreotrochilus\" OR \"Orthorhyncus\" OR \"Oxypogon\" OR \"Panterpe\" OR \"Patagona\" OR \"Phaeochroa\" OR \"Phaethornis\" OR \"Phlogophilus\" OR \"Polyonymus\" OR \"Polytmus\" OR \"Pterophanes\" OR \"Ramphodon\" OR \"Ramphomicron\" OR \"Rhodopis\" OR \"Sappho\" OR \"Schistes\" OR \"Selasphorus\" OR \"Sephanoides\" OR \"Stephanoxis\" OR \"Sternoclyta\" OR \"Taphrospilus\" OR \"Thalurania\" OR \"Thaumastura\" OR \"Threnetes\" OR \"Topaza\" OR \"Trochilus\" OR \"Urochroa\" OR \"Urosticte\" OR \"Apteryx\" OR \"Anthracoceros\" OR \"Buceros\" OR \"Bycanistes\" OR \"Lophoceros\" OR \"Penelopides\" OR \"Rhabdotorrhinus\" OR \"Rhyticeros\" OR \"Tockus\" OR \"Bucorvus\" OR \"Phoeniculus\" OR \"Rhinopomastus\" OR \"Upupa\" OR \"Antrostomus\" OR \"Caprimulgus\" OR \"Chordeiles\" OR \"Eleothreptus\" OR \"Eurostopodus\" OR \"Hydropsalis\" OR \"Lurocalis\" OR \"Lyncornis\" OR \"Nyctidromus\" OR \"Nyctiphrynus\" OR \"Nyctipolus\" OR \"Nyctiprogne\" OR \"Phalaenoptilus\" OR \"Setopagis\" OR \"Systellura\" OR \"Uropsalis\" OR \"Nyctibius\" OR \"Batrachostomus\" OR \"Podargus\" OR \"Steatornis\" OR \"Cariama\" OR \"Casuarius\" OR \"Dromaius\" OR \"Aethia\" OR \"Alca\" OR \"Alle\" OR \"Brachyramphus\" OR \"Cepphus\" OR \"Cerorhinca\" OR \"Fratercula\" OR \"Pinguinus\" OR \"Ptychoramphus\" OR \"Synthliboramphus\" OR \"Uria\" OR \"Burhinus\" OR \"Anarhynchus\" OR \"Charadrius\" OR \"Elseyornis\" OR \"Erythrogonys\" OR \"Hoploxypterus\" OR \"Oreopholus\" OR \"Peltohyas\" OR \"Phegornis\" OR \"Pluvialis\" OR \"Thinornis\" OR \"Vanellus\" OR \"Chionis\" OR \"Dromas\" OR \"Cursorius\" OR \"Glareola\" OR \"Rhinoptilus\" OR \"Stiltia\" OR \"Haematopus\" OR \"Actophilornis\" OR \"Hydrophasianus\" OR \"Irediparra\" OR \"Jacana\" OR \"Metopidius\" OR \"Microparra\" OR \"Anous\" OR \"Chlidonias\" OR \"Chroicocephalus\" OR \"Creagrus\" OR \"Gelochelidon\" OR \"Gygis\" OR \"Hydrocoloeus\" OR \"Hydroprogne\" OR \"Ichthyaetus\" OR \"Larosterna\" OR \"Larus\" OR \"Leucophaeus\" OR \"Onychoprion\" OR \"Pagophila\" OR \"Phaetusa\" OR \"Rhodostethia\" OR \"Rissa\" OR \"Rynchops\" OR \"Sterna\" OR \"Sternula\" OR \"Thalasseus\" OR \"Xema\" OR \"Pedionomus\" OR \"Pluvianellus\" OR \"Pluvianus\" OR \"Himantopus\" OR \"Recurvirostra\" OR \"Nycticryphes\" OR \"Rostratula\" OR \"Actitis\" OR \"Arenaria\" OR \"Bartramia\" OR \"Calidris\" OR \"Coenocorypha\" OR \"Gallinago\" OR \"Limnodromus\" OR \"Limosa\" OR \"Lymnocryptes\" OR \"Numenius\" OR \"Phalaropus\" OR \"Scolopax\" OR \"Tringa\" OR \"Xenus\" OR \"Stercorarius\" OR \"Attagis\" OR \"Thinocorus\" OR \"Turnix\" OR \"Ciconia\" OR \"Ephippiorhynchus\" OR \"Jabiru\" OR \"Leptoptilos\" OR \"Mycteria\" OR \"Colius\" OR \"Urocolius\" OR \"Alectroenas\" OR \"Alopecoenas\" OR \"Caloenas\" OR \"Chalcophaps\" OR \"Claravis\" OR \"Columba\" OR \"Columbina\" OR \"Didunculus\" OR \"Drepanoptila\" OR \"Ducula\" OR \"Ectopistes\" OR \"Gallicolumba\" OR \"Geopelia\" OR \"Geophaps\" OR \"Geotrygon\" OR \"Goura\" OR \"Gymnophaps\" OR \"Hemiphaga\" OR \"Henicophaps\" OR \"Leptotila\" OR \"Leptotrygon\" OR \"Leucosarcia\" OR \"Lopholaimus\" OR \"Macropygia\" OR \"Metriopelia\" OR \"Ocyphaps\" OR \"Oena\" OR \"Otidiphaps\" OR \"Patagioenas\" OR \"Petrophassa\" OR \"Pezophaps\" OR \"Phapitreron\" OR \"Phaps\" OR \"Ptilinopus\" OR \"Raphus\" OR \"Reinwardtoena\" OR \"Spilopelia\" OR \"Streptopelia\" OR \"Treron\" OR \"Trugon\" OR \"Turacoena\" OR \"Turtur\" OR \"Uropelia\" OR \"Zenaida\" OR \"Zentrygon\" OR \"Actenoides\" OR \"Alcedo\" OR \"Caridonax\" OR \"Ceryle\" OR \"Ceyx\" OR \"Chloroceryle\" OR \"Cittura\" OR \"Corythornis\" OR \"Dacelo\" OR \"Halcyon\" OR \"Ispidina\" OR \"Lacedo\" OR \"Megaceryle\" OR \"Melidora\" OR \"Syma\" OR \"Tanysiptera\" OR \"Todiramphus\" OR \"Atelornis\" OR \"Brachypteracias\" OR \"Geobiastes\" OR \"Coracias\" OR \"Eurystomus\" OR \"Merops\" OR \"Nyctyornis\" OR \"Baryphthengus\" OR \"Electron\" OR \"Eumomota\" OR \"Hylomanes\" OR \"Momotus\" OR \"Todus\" OR \"Cacomantis\" OR \"Carpococcyx\" OR \"Centropus\" OR \"Cercococcyx\" OR \"Chrysococcyx\" OR \"Clamator\" OR \"Coccycua\" OR \"Coccyzus\" OR \"Coua\" OR \"Crotophaga\" OR \"Cuculus\" OR \"Dasylophus\" OR \"Dromococcyx\" OR \"Eudynamys\" OR \"Geococcyx\" OR \"Guira\" OR \"Hierococcyx\" OR \"Morococcyx\" OR \"Neomorphus\" OR \"Pachycoccyx\" OR \"Phaenicophaeus\" OR \"Piaya\" OR \"Rhinortha\" OR \"Scythrops\" OR \"Surniculus\" OR \"Tapera\" OR \"Urodynamis\" OR \"Zanclostomus\" OR \"Dinornis\" OR \"Anomalopteryx\" OR \"Emeus\" OR \"Euryapteryx\" OR \"Eurypyga\" OR \"Rhynochetos\" OR \"Caracara\" OR \"Daptrius\" OR \"Falco\" OR \"Herpetotheres\" OR \"Ibycter\" OR \"Micrastur\" OR \"Microhierax\" OR \"Milvago\" OR \"Phalcoboenus\" OR \"Polihierax\" OR \"Spiziapteryx\" OR \"Aburria\" OR \"Chamaepetes\" OR \"Crax\" OR \"Mitu\" OR \"Nothocrax\" OR \"Oreophasis\" OR \"Ortalis\" OR \"Pauxi\" OR \"Penelope\" OR \"Penelopina\" OR \"Pipile\" OR \"Alectura\" OR \"Megapodius\" OR \"Acryllium\" OR \"Guttera\" OR \"Numida\" OR \"Callipepla\" OR \"Colinus\" OR \"Cyrtonyx\" OR \"Dendrortyx\" OR \"Odontophorus\" OR \"Oreortyx\" OR \"Philortyx\" OR \"Ptilopachus\" OR \"Rhynchortyx\" OR \"Alectoris\" OR \"Ammoperdix\" OR \"Arborophila\" OR \"Argusianus\" OR \"Bambusicola\" OR \"Bonasa\" OR \"Caloperdix\" OR \"Centrocercus\" OR \"Chrysolophus\" OR \"Coturnix\" OR \"Crossoptilon\" OR \"Dendragapus\" OR \"Excalfactoria\" OR \"Falcipennis\" OR \"Francolinus\" OR \"Gallus\" OR \"Haematortyx\" OR \"Ithaginis\" OR \"Lagopus\" OR \"Lerwa\" OR \"Lophophorus\" OR \"Lophura\" OR \"Lyrurus\" OR \"Meleagris\" OR \"Pavo\" OR \"Peliperdix\" OR \"Perdix\" OR \"Phasianus\" OR \"Polyplectron\" OR \"Pternistis\" OR \"Pucrasia\" OR \"Rhizothera\" OR \"Rollulus\" OR \"Scleroptila\" OR \"Syrmaticus\" OR \"Tetrao\" OR \"Tetraogallus\" OR \"Tetraophasis\" OR \"Tragopan\" OR \"Tympanuchus\" OR \"Gavia\" OR \"Aramus\" OR \"Anthropoides\" OR \"Antigone\" OR \"Balearica\" OR \"Bugeranus\" OR \"Grus\" OR \"Leucogeranus\" OR \"Heliornis\" OR \"Psophia\" OR \"Aenigmatolimnas\" OR \"Amaurolimnas\" OR \"Amaurornis\" OR \"Anurolimnas\" OR \"Aramides\" OR \"Atlantisia\" OR \"Coturnicops\" OR \"Crex\" OR \"Dryolimnas\" OR \"Eulabeornis\" OR \"Fulica\" OR \"Gallicrex\" OR \"Gallinula\" OR \"Gallirallus\" OR \"Laterallus\" OR \"Lewinia\" OR \"Micropygia\" OR \"Neocrex\" OR \"Nesoclopeus\" OR \"Paragallinula\" OR \"Pardirallus\" OR \"Porphyrio\" OR \"Porphyriops\" OR \"Porzana\" OR \"Rallicula\" OR \"Rallina\" OR \"Rallus\" OR \"Tribonyx\" OR \"Canirallus\" OR \"Sarothrura\" OR \"Leptosomus\" OR \"Corythaeola\" OR \"Corythaixoides\" OR \"Crinifer\" OR \"Musophaga\" OR \"Tauraco\" OR \"Opisthocomus\" OR \"Afrotis\" OR \"Ardeotis\" OR \"Chlamydotis\" OR \"Neotis\" OR \"Otis\" OR \"Tetrax\" OR \"Acanthisitta\" OR \"Pachyplichas\" OR \"Traversia\" OR \"Xenicus\" OR \"Acanthiza\" OR \"Acanthornis\" OR \"Aethomyias\" OR \"Aphelocephala\" OR \"Calamanthus\" OR \"Gerygone\" OR \"Hylacola\" OR \"Neosericornis\" OR \"Oreoscopus\" OR \"Origma\" OR \"Pachycare\" OR \"Pycnoptilus\" OR \"Pyrrholaemus\" OR \"Sericornis\" OR \"Smicrornis\" OR \"Acrocephalus\" OR \"Arundinax\" OR \"Calamonastides\" OR \"Hippolais\" OR \"Iduna\" OR \"Nesillas\" OR \"Aegithalos\" OR \"Leptopoecile\" OR \"Psaltriparus\" OR \"Aegithina\" OR \"Alaemon\" OR \"Alauda\" OR \"Alaudala\" OR \"Ammomanes\" OR \"Calandrella\" OR \"Calendulauda\" OR \"Chersomanes\" OR \"Eremophila\" OR \"Eremopterix\" OR \"Galerida\" OR \"Lullula\" OR \"Melanocorypha\" OR \"Mirafra\" OR \"Pinarocorys\" OR \"Spizocorys\" OR \"Artamus\" OR \"Gymnorhina\" OR \"Melloria\" OR \"Bombycilla\" OR \"Buphagus\" OR \"Calcarius\" OR \"Plectrophenax\" OR \"Rhynchophanes\" OR \"Callaeas\" OR \"Heteralocha\" OR \"Philesturnus\" OR \"Calyptophilus\" OR \"Campephaga\" OR \"Ceblepyris\" OR \"Coracina\" OR \"Edolisoma\" OR \"Lalage\" OR \"Malindangia\" OR \"Pericrocotus\" OR \"Amaurospiza\" OR \"Cardinalis\" OR \"Caryothraustes\" OR \"Chlorothraupis\" OR \"Cyanocompsa\" OR \"Cyanoloxia\" OR \"Granatellus\" OR \"Habia\" OR \"Passerina\" OR \"Periporphyrus\" OR \"Pheucticus\" OR \"Piranga\" OR \"Spiza\" OR \"Certhia\" OR \"Salpornis\" OR \"Abroscopus\" OR \"Cettia\" OR \"Horornis\" OR \"Phyllergates\" OR \"Tesia\" OR \"Urosphena\" OR \"Chloropsis\" OR \"Cinclus\" OR \"Apalis\" OR \"Artisornis\" OR \"Camaroptera\" OR \"Cisticola\" OR \"Eremomela\" OR \"Heliolais\" OR \"Hypergerus\" OR \"Neomixis\" OR \"Oreolais\" OR \"Orthotomus\" OR \"Phragmacia\" OR \"Poliolais\" OR \"Prinia\" OR \"Schistolais\" OR \"Urolais\" OR \"Urorhipis\" OR \"Climacteris\" OR \"Cormobates\" OR \"Conopophaga\" OR \"Struthidea\" OR \"Aphelocoma\" OR \"Calocitta\" OR \"Cissa\" OR \"Coloeus\" OR \"Corvus\" OR \"Cyanocitta\" OR \"Cyanocorax\" OR \"Cyanolyca\" OR \"Cyanopica\" OR \"Dendrocitta\" OR \"Garrulus\" OR \"Gymnorhinus\" OR \"Nucifraga\" OR \"Perisoreus\" OR \"Pica\" OR \"Platylophus\" OR \"Podoces\" OR \"Psilorhinus\" OR \"Ptilostomus\" OR \"Pyrrhocorax\" OR \"Urocissa\" OR \"Ampelioides\" OR \"Ampelion\" OR \"Carpornis\" OR \"Cephalopterus\" OR \"Conioptilon\" OR \"Cotinga\" OR \"Doliornis\" OR \"Gymnoderus\" OR \"Haematoderus\" OR \"Lipaugus\" OR \"Perissocephalus\" OR \"Phoenicircus\" OR \"Phytotoma\" OR \"Pipreola\" OR \"Porphyrolaema\" OR \"Procnias\" OR \"Pyroderus\" OR \"Querula\" OR \"Rupicola\" OR \"Snowornis\" OR \"Xipholena\" OR \"Zaratornis\" OR \"Dasyornis\" OR \"Dicaeum\" OR \"Prionochilus\" OR \"Dicrurus\" OR \"Donacobius\" OR \"Dulus\" OR \"Emberiza\" OR \"Amadina\" OR \"Amandava\" OR \"Cryptospiza\" OR \"Erythrura\" OR \"Estrilda\" OR \"Euodice\" OR \"Euschistospiza\" OR \"Lagonosticta\" OR \"Lonchura\" OR \"Mandingoa\" OR \"Neochmia\" OR \"Nesocharis\" OR \"Nigrita\" OR \"Ortygospiza\" OR \"Parmoptila\" OR \"Pyrenestes\" OR \"Pytilia\" OR \"Spermophaga\" OR \"Stagonopleura\" OR \"Taeniopygia\" OR \"Uraeginthus\" OR \"Calyptomena\" OR \"Cymbirhynchus\" OR \"Eurylaimus\" OR \"Psarisomus\" OR \"Serilophus\" OR \"Smithornis\" OR \"Chamaeza\" OR \"Formicarius\" OR \"Acanthis\" OR \"Agraphospiza\" OR \"Akialoa\" OR \"Bucanetes\" OR \"Carduelis\" OR \"Carpodacus\" OR \"Chloris\" OR \"Chlorodrepanis\" OR \"Chlorophonia\" OR \"Chrysocorythus\" OR \"Coccothraustes\" OR \"Crithagra\" OR \"Drepanis\" OR \"Eophona\" OR \"Euphonia\" OR \"Fringilla\" OR \"Haemorhous\" OR \"Hemignathus\" OR \"Himatione\" OR \"Leucosticte\" OR \"Linaria\" OR \"Linurgus\" OR \"Loxia\" OR \"Loxioides\" OR \"Loxops\" OR \"Magumma\" OR \"Melamprosops\" OR \"Oreomystis\" OR \"Paroreomyza\" OR \"Pinicola\" OR \"Procarduelis\" OR \"Pseudonestor\" OR \"Psittirostra\" OR \"Pyrrhoplectes\" OR \"Pyrrhula\" OR \"Rhodopechys\" OR \"Rhodospiza\" OR \"Serinus\" OR \"Spinus\" OR \"Telespiza\" OR \"Anabacerthia\" OR \"Anabazenops\" OR \"Ancistrops\" OR \"Anumbius\" OR \"Aphrastura\" OR \"Asthenes\" OR \"Automolus\" OR \"Berlepschia\" OR \"Campylorhamphus\" OR \"Certhiasomus\" OR \"Certhiaxis\" OR \"Cinclodes\" OR \"Clibanornis\" OR \"Coryphistera\" OR \"Cranioleuca\" OR \"Deconychura\" OR \"Dendrexetastes\" OR \"Dendrocincla\" OR \"Dendrocolaptes\" OR \"Dendroplex\" OR \"Drymornis\" OR \"Drymotoxeres\" OR \"Furnarius\" OR \"Geocerthia\" OR \"Geositta\" OR \"Glyphorynchus\" OR \"Heliobletus\" OR \"Hellmayrea\" OR \"Hylexetastes\" OR \"Lepidocolaptes\" OR \"Leptasthenura\" OR \"Limnoctites\" OR \"Limnornis\" OR \"Lochmias\" OR \"Margarornis\" OR \"Mazaria\" OR \"Megaxenops\" OR \"Metopothrix\" OR \"Microxenops\" OR \"Nasica\" OR \"Ochetorhynchus\" OR \"Phacellodomus\" OR \"Philydor\" OR \"Phleocryptes\" OR \"Premnoplex\" OR \"Premnornis\" OR \"Pseudasthenes\" OR \"Pseudocolaptes\" OR \"Pseudoseisura\" OR \"Pygarrhichas\" OR \"Roraimia\" OR \"Schoeniophylax\" OR \"Sclerurus\" OR \"Sittasomus\" OR \"Spartonoica\" OR \"Sylviorthorhynchus\" OR \"Synallaxis\" OR \"Syndactyla\" OR \"Tarphonomus\" OR \"Thripadectes\" OR \"Thripophaga\" OR \"Upucerthia\" OR \"Xenerpestes\" OR \"Xenops\" OR \"Xiphocolaptes\" OR \"Xiphorhynchus\" OR \"Grallaria\" OR \"Grallaricula\" OR \"Hylopezus\" OR \"Myrmothera\" OR \"Alopochelidon\" OR \"Atticora\" OR \"Cecropis\" OR \"Delichon\" OR \"Haplochelidon\" OR \"Hirundo\" OR \"Neochelidon\" OR \"Notiochelidon\" OR \"Orochelidon\" OR \"Petrochelidon\" OR \"Phedina\" OR \"Progne\" OR \"Psalidoprocne\" OR \"Pseudhirundo\" OR \"Pseudochelidon\" OR \"Ptyonoprogne\" OR \"Riparia\" OR \"Stelgidopteryx\" OR \"Tachycineta\" OR \"Hyliota\" OR \"Hypocolius\" OR \"Agelaioides\" OR \"Agelaius\" OR \"Agelasticus\" OR \"Amblycercus\" OR \"Amblyramphus\" OR \"Anumara\" OR \"Cacicus\" OR \"Chrysomus\" OR \"Curaeus\" OR \"Dives\" OR \"Dolichonyx\" OR \"Euphagus\" OR \"Gnorimopsar\" OR \"Gymnomystax\" OR \"Hypopyrrhus\" OR \"Icterus\" OR \"Lampropsar\" OR \"Leistes\" OR \"Macroagelaius\" OR \"Molothrus\" OR \"Nesopsar\" OR \"Oreopsar\" OR \"Psarocolius\" OR \"Pseudoleistes\" OR \"Quiscalus\" OR \"Sturnella\" OR \"Xanthocephalus\" OR \"Xanthopsar\" OR \"Icteria\" OR \"Ifrita\" OR \"Irena\" OR \"Corvinella\" OR \"Eurocephalus\" OR \"Lanius\" OR \"Actinodura\" OR \"Argya\" OR \"Garrulax\" OR \"Grammatoptila\" OR \"Heterophasia\" OR \"Ianthocincla\" OR \"Laniellus\" OR \"Leiothrix\" OR \"Liocichla\" OR \"Minla\" OR \"Pterorhinus\" OR \"Trochalopteron\" OR \"Turdoides\" OR \"Bradypterus\" OR \"Cincloramphus\" OR \"Helopsaltes\" OR \"Locustella\" OR \"Megalurus\" OR \"Poodytes\" OR \"Machaerirhynchus\" OR \"Graueria\" OR \"Hylia\" OR \"Macrosphenus\" OR \"Melocichla\" OR \"Sylvietta\" OR \"Chlorophoneus\" OR \"Dryoscopus\" OR \"Laniarius\" OR \"Malaconotus\" OR \"Nilaus\" OR \"Rhodophoneus\" OR \"Tchagra\" OR \"Telophorus\" OR \"Amytornis\" OR \"Chenorhamphus\" OR \"Clytomyias\" OR \"Malurus\" OR \"Stipiturus\" OR \"Melampitta\" OR \"Melanocharis\" OR \"Oedistoma\" OR \"Toxorhamphus\" OR \"Melanopareia\" OR \"Acanthagenys\" OR \"Acanthorhynchus\" OR \"Anthochaera\" OR \"Anthornis\" OR \"Caligavis\" OR \"Entomyzon\" OR \"Epthianura\" OR \"Glycifohia\" OR \"Gymnomyza\" OR \"Lichmera\" OR \"Manorina\" OR \"Melidectes\" OR \"Melilestes\" OR \"Meliphaga\" OR \"Melipotes\" OR \"Melithreptus\" OR \"Myzomela\" OR \"Nesoptilotis\" OR \"Philemon\" OR \"Phylidonyris\" OR \"Prosthemadera\" OR \"Ptiloprora\" OR \"Ptilotula\" OR \"Pycnopygius\" OR \"Timeliopsis\" OR \"Xanthotis\" OR \"Menura\" OR \"Allenia\" OR \"Cinclocerthia\" OR \"Dumetella\" OR \"Margarops\" OR \"Melanoptila\" OR \"Melanotis\" OR \"Mimus\" OR \"Oreoscoptes\" OR \"Ramphocinclus\" OR \"Toxostoma\" OR \"Lamprospiza\" OR \"Mitrospingus\" OR \"Moho\" OR \"Mohoua\" OR \"Arses\" OR \"Carterornis\" OR \"Clytorhynchus\" OR \"Grallina\" OR \"Hypothymis\" OR \"Monarcha\" OR \"Myiagra\" OR \"Symposiachrus\" OR \"Terpsiphone\" OR \"Trochocercus\" OR \"Anthus\" OR \"Macronyx\" OR \"Motacilla\" OR \"Alethe\" OR \"Anthipes\" OR \"Brachypteryx\" OR \"Calliope\" OR \"Campicoloides\" OR \"Cercotrichas\" OR \"Chamaetylas\" OR \"Copsychus\" OR \"Cossypha\" OR \"Cyanoptila\" OR \"Cyornis\" OR \"Enicurus\" OR \"Erithacus\" OR \"Eumyias\" OR \"Ficedula\" OR \"Fraseria\" OR \"Irania\" OR \"Larvivora\" OR \"Leonardina\" OR \"Luscinia\" OR \"Melaenornis\" OR \"Monticola\" OR \"Muscicapa\" OR \"Myiomela\" OR \"Myioparus\" OR \"Myophonus\" OR \"Myrmecocichla\" OR \"Niltava\" OR \"Oenanthe\" OR \"Phoenicurus\" OR \"Pogonocichla\" OR \"Saxicola\" OR \"Sheppardia\" OR \"Sholicola\" OR \"Stiphrornis\" OR \"Tarsiger\" OR \"Thamnolaea\" OR \"Vauriella\" OR \"Aethopyga\" OR \"Anabathmis\" OR \"Anthreptes\" OR \"Arachnothera\" OR \"Chalcomitra\" OR \"Cinnyris\" OR \"Cyanomitra\" OR \"Deleornis\" OR \"Hedydipna\" OR \"Kurochkinegramma\" OR \"Leptocoma\" OR \"Nectarinia\" OR \"Daphoenositta\" OR \"Nesospingus\" OR \"Nicator\" OR \"Notiomystis\" OR \"Aleadryas\" OR \"Oriolus\" OR \"Pitohui\" OR \"Sphecotheres\" OR \"Turnagra\" OR \"Colluricincla\" OR \"Falcunculus\" OR \"Melanorectes\" OR \"Pachycephala\" OR \"Pseudorectes\" OR \"Panurus\" OR \"Cicinnurus\" OR \"Diphyllodes\" OR \"Manucodia\" OR \"Paradisaea\" OR \"Ptiloris\" OR \"Paramythia\" OR \"Pardalotus\" OR \"Baeolophus\" OR \"Cephalopyrus\" OR \"Cyanistes\" OR \"Lophophanes\" OR \"Machlolophus\" OR \"Melaniparus\" OR \"Melanochlora\" OR \"Pardaliparus\" OR \"Parus\" OR \"Periparus\" OR \"Poecile\" OR \"Pseudopodoces\" OR \"Sittiparus\" OR \"Sylviparus\" OR \"Basileuterus\" OR \"Cardellina\" OR \"Catharopeza\" OR \"Dendroica\" OR \"Geothlypis\" OR \"Helmitheros\" OR \"Leiothlypis\" OR \"Limnothlypis\" OR \"Mniotilta\" OR \"Myioborus\" OR \"Myiothlypis\" OR \"Oporornis\" OR \"Oreothlypis\" OR \"Parkesia\" OR \"Protonotaria\" OR \"Seiurus\" OR \"Setophaga\" OR \"Vermivora\" OR \"Aimophila\" OR \"Ammodramus\" OR \"Amphispiza\" OR \"Arremon\" OR \"Arremonops\" OR \"Artemisiospiza\" OR \"Atlapetes\" OR \"Calamospiza\" OR \"Chlorospingus\" OR \"Chondestes\" OR \"Junco\" OR \"Melospiza\" OR \"Melozone\" OR \"Oreothraupis\" OR \"Oriturus\" OR \"Passerculus\" OR \"Passerella\" OR \"Peucaea\" OR \"Pezopetes\" OR \"Pipilo\" OR \"Pooecetes\" OR \"Pselliophorus\" OR \"Rhynchospiza\" OR \"Spizella\" OR \"Spizelloides\" OR \"Xenospiza\" OR \"Zonotrichia\" OR \"Carpospiza\" OR \"Gymnoris\" OR \"Hypocryptadius\" OR \"Montifringilla\" OR \"Onychostruthus\" OR \"Passer\" OR \"Petronia\" OR \"Pyrgilauda\" OR \"Alcippe\" OR \"Gampsorhynchus\" OR \"Illadopsis\" OR \"Jabouilleia\" OR \"Kenopia\" OR \"Laticilla\" OR \"Malacocincla\" OR \"Malacopteron\" OR \"Napothera\" OR \"Pellorneum\" OR \"Rimator\" OR \"Trichastoma\" OR \"Amalocichla\" OR \"Drymodes\" OR \"Eopsaltria\" OR \"Eugerygone\" OR \"Heteromyias\" OR \"Melanodryas\" OR \"Microeca\" OR \"Monachella\" OR \"Pachycephalopsis\" OR \"Peneoenanthe\" OR \"Peneothello\" OR \"Petroica\" OR \"Poecilodryas\" OR \"Tregellasia\" OR \"Peucedramus\" OR \"Microligea\" OR \"Phaenicophilus\" OR \"Xenoligea\" OR \"Phylloscopus\" OR \"Picathartes\" OR \"Antilophia\" OR \"Ceratopipra\" OR \"Chiroxiphia\" OR \"Chloropipo\" OR \"Corapipo\" OR \"Cryptopipo\" OR \"Heterocercus\" OR \"Ilicura\" OR \"Lepidothrix\" OR \"Machaeropterus\" OR \"Manacus\" OR \"Masius\" OR \"Neopelma\" OR \"Pipra\" OR \"Pseudopipra\" OR \"Tyranneutes\" OR \"Xenopipo\" OR \"Erythropitta\" OR \"Hydrornis\" OR \"Pitta\" OR \"Batis\" OR \"Platysteira\" OR \"Anaplectes\" OR \"Bubalornis\" OR \"Euplectes\" OR \"Malimbus\" OR \"Plocepasser\" OR \"Ploceus\" OR \"Quelea\" OR \"Sporopipes\" OR \"Pnoepyga\" OR \"Microbates\" OR \"Polioptila\" OR \"Ramphocaenus\" OR \"Garritornis\" OR \"Prunella\" OR \"Cinclosoma\" OR \"Ptilorrhoa\" OR \"Phainopepla\" OR \"Phainoptila\" OR \"Ptiliogonys\" OR \"Ailuroedus\" OR \"Amblyornis\" OR \"Ptilonorhynchus\" OR \"Sericulus\" OR \"Alophoixus\" OR \"Andropadus\" OR \"Arizelocichla\" OR \"Atimastillas\" OR \"Baeopogon\" OR \"Bleda\" OR \"Chlorocichla\" OR \"Criniger\" OR \"Eurillas\" OR \"Hemixos\" OR \"Hypsipetes\" OR \"Iole\" OR \"Ixos\" OR \"Neolestes\" OR \"Phyllastrephus\" OR \"Pycnonotus\" OR \"Spizixos\" OR \"Stelgidillas\" OR \"Tricholestes\" OR \"Regulus\" OR \"Anthoscopus\" OR \"Auriparus\" OR \"Remiz\" OR \"Rhagologus\" OR \"Eleoscytalopus\" OR \"Liosceles\" OR \"Psilorhamphus\" OR \"Pteroptochos\" OR \"Scelorchilus\" OR \"Scytalopus\" OR \"Teledromas\" OR \"Rhipidura\" OR \"Rhodinocichla\" OR \"Sapayoa\" OR \"Sitta\" OR \"Spindalis\" OR \"Chelidorhynx\" OR \"Culicicapa\" OR \"Elminia\" OR \"Acridotheres\" OR \"Agropsar\" OR \"Ampeliceps\" OR \"Aplonis\" OR \"Basilornis\" OR \"Cinnyricinclus\" OR \"Creatophora\" OR \"Gracula\" OR \"Gracupica\" OR \"Hartlaubius\" OR \"Hylopsar\" OR \"Lamprotornis\" OR \"Leucopsar\" OR \"Mino\" OR \"Notopholia\" OR \"Onychognathus\" OR \"Pastor\" OR \"Poeoptera\" OR \"Rhabdornis\" OR \"Sarcops\" OR \"Scissirostrum\" OR \"Speculipastor\" OR \"Spodiopsar\" OR \"Streptocitta\" OR \"Sturnia\" OR \"Sturnus\" OR \"Chamaea\" OR \"Chleuasicus\" OR \"Chloropeta\" OR \"Chrysomma\" OR \"Conostoma\" OR \"Fulvetta\" OR \"Lioparus\" OR \"Paradoxornis\" OR \"Pseudoalcippe\" OR \"Psittiparus\" OR \"Rhopophilus\" OR \"Sinosuthora\" OR \"Suthora\" OR \"Sylvia\" OR \"Teretistris\" OR \"Akletos\" OR \"Ampelornis\" OR \"Aprositornis\" OR \"Batara\" OR \"Cercomacra\" OR \"Cercomacroides\" OR \"Cymbilaimus\" OR \"Dichrozona\" OR \"Drymophila\" OR \"Dysithamnus\" OR \"Epinecrophylla\" OR \"Euchrepomis\" OR \"Formicivora\" OR \"Frederickena\" OR \"Gymnocichla\" OR \"Gymnopithys\" OR \"Hafferia\" OR \"Herpsilochmus\" OR \"Hylophylax\" OR \"Hypocnemis\" OR \"Hypocnemoides\" OR \"Hypoedaleus\" OR \"Isleria\" OR \"Mackenziaena\" OR \"Megastictus\" OR \"Microrhopias\" OR \"Myrmeciza\" OR \"Myrmelastes\" OR \"Myrmoborus\" OR \"Myrmochanes\" OR \"Myrmoderus\" OR \"Myrmophylax\" OR \"Myrmorchilus\" OR \"Myrmornis\" OR \"Myrmotherula\" OR \"Neoctantes\" OR \"Oneillornis\" OR \"Percnostola\" OR \"Phaenostictus\" OR \"Phlegopsis\" OR \"Pithys\" OR \"Poliocrania\" OR \"Pygiptila\" OR \"Pyriglena\" OR \"Rhegmatorhina\" OR \"Rhopias\" OR \"Rhopornis\" OR \"Sakesphorus\" OR \"Sciaphylax\" OR \"Sclateria\" OR \"Sipia\" OR \"Taraba\" OR \"Thamnistes\" OR \"Thamnomanes\" OR \"Thamnophilus\" OR \"Willisornis\" OR \"Xenornis\" OR \"Anisognathus\" OR \"Bangsia\" OR \"Buthraupis\" OR \"Calochaetes\" OR \"Catamblyrhynchus\" OR \"Catamenia\" OR \"Charitospiza\" OR \"Chlorochrysa\" OR \"Chlorophanes\" OR \"Chlorornis\" OR \"Chrysothlypis\" OR \"Cissopis\" OR \"Cnemoscopus\" OR \"Coereba\" OR \"Compsospiza\" OR \"Compsothraupis\" OR \"Conirostrum\" OR \"Conothraupis\" OR \"Coryphospingus\" OR \"Creurgops\" OR \"Cyanerpes\" OR \"Cyanicterus\" OR \"Cypsnagra\" OR \"Dacnis\" OR \"Delothraupis\" OR \"Diglossa\" OR \"Diuca\" OR \"Dolospingus\" OR \"Donacospiza\" OR \"Dubusia\" OR \"Emberizoides\" OR \"Embernagra\" OR \"Eucometis\" OR \"Euneornis\" OR \"Geospiza\" OR \"Gubernatrix\" OR \"Haplospiza\" OR \"Hemispingus\" OR \"Hemithraupis\" OR \"Heterospingus\" OR \"Incaspiza\" OR \"Iridophanes\" OR \"Iridosornis\" OR \"Lanio\" OR \"Lophospingus\" OR \"Loxigilla\" OR \"Loxipasser\" OR \"Melanodera\" OR \"Melanospiza\" OR \"Melopyrrha\" OR \"Nemosia\" OR \"Nephelornis\" OR \"Oreomanes\" OR \"Oryzoborus\" OR \"Parkerthraustes\" OR \"Paroaria\" OR \"Phrygilus\" OR \"Piezorina\" OR \"Pipraeidea\" OR \"Poospiza\" OR \"Pyrrhocoma\" OR \"Ramphocelus\" OR \"Rhodospingus\" OR \"Saltator\" OR \"Saltatricula\" OR \"Schistochlamys\" OR \"Sericossypha\" OR \"Sicalis\" OR \"Sporophila\" OR \"Stephanophorus\" OR \"Tachyphonus\" OR \"Tangara\" OR \"Tersina\" OR \"Thlypopsis\" OR \"Thraupis\" OR \"Tiaris\" OR \"Trichothraupis\" OR \"Volatinia\" OR \"Wetmorethraupis\" OR \"Xenodacnis\" OR \"Xenospingus\" OR \"Tichodroma\" OR \"Macronus\" OR \"Pomatorhinus\" OR \"Spelaeornis\" OR \"Stachyridopsis\" OR \"Stachyris\" OR \"Iodopleura\" OR \"Laniisoma\" OR \"Laniocera\" OR \"Myiobius\" OR \"Onychorhynchus\" OR \"Oxyruncus\" OR \"Pachyramphus\" OR \"Schiffornis\" OR \"Terenotriccus\" OR \"Tityra\" OR \"Xenopsaris\" OR \"Campylorhynchus\" OR \"Cantorchilus\" OR \"Catherpes\" OR \"Cinnycerthia\" OR \"Cistothorus\" OR \"Cyphorhinus\" OR \"Henicorhina\" OR \"Microcerculus\" OR \"Odontorchilus\" OR \"Pheugopedius\" OR \"Salpinctes\" OR \"Thryomanes\" OR \"Thryophilus\" OR \"Thryothorus\" OR \"Troglodytes\" OR \"Uropsila\" OR \"Catharus\" OR \"Cichlopsis\" OR \"Entomodestes\" OR \"Geokichla\" OR \"Hylocichla\" OR \"Ixoreus\" OR \"Myadestes\" OR \"Neocossyphus\" OR \"Ridgwayia\" OR \"Sialia\" OR \"Stizorhina\" OR \"Turdus\" OR \"Zoothera\" OR \"Agriornis\" OR \"Alectrurus\" OR \"Anairetes\" OR \"Aphanotriccus\" OR \"Arundinicola\" OR \"Atalotriccus\" OR \"Attila\" OR \"Camptostoma\" OR \"Capsiempis\" OR \"Casiornis\" OR \"Cnemarchus\" OR \"Cnemotriccus\" OR \"Cnipodectes\" OR \"Colonia\" OR \"Colorhamphus\" OR \"Conopias\" OR \"Contopus\" OR \"Corythopis\" OR \"Culicivora\" OR \"Deltarhynchus\" OR \"Elaenia\" OR \"Empidonax\" OR \"Empidonomus\" OR \"Euscarthmus\" OR \"Fluvicola\" OR \"Griseotyrannus\" OR \"Gubernetes\" OR \"Hemitriccus\" OR \"Heteroxolmis\" OR \"Hirundinea\" OR \"Hymenops\" OR \"Inezia\" OR \"Knipolegus\" OR \"Lathrotriccus\" OR \"Legatus\" OR \"Leptopogon\" OR \"Lessonia\" OR \"Lophotriccus\" OR \"Machetornis\" OR \"Mecocerculus\" OR \"Megarynchus\" OR \"Mionectes\" OR \"Mitrephanes\" OR \"Muscigralla\" OR \"Muscisaxicola\" OR \"Myiarchus\" OR \"Myiodynastes\" OR \"Myiopagis\" OR \"Myiophobus\" OR \"Myiornis\" OR \"Myiotheretes\" OR \"Myiotriccus\" OR \"Myiozetetes\" OR \"Neopipo\" OR \"Neoxolmis\" OR \"Nephelomyias\" OR \"Ochthoeca\" OR \"Ochthornis\" OR \"Oncostoma\" OR \"Ornithion\" OR \"Phaeomyias\" OR \"Philohydor\" OR \"Phyllomyias\" OR \"Phylloscartes\" OR \"Piprites\" OR \"Pitangus\" OR \"Platyrinchus\" OR \"Poecilotriccus\" OR \"Pogonotriccus\" OR \"Polioxolmis\" OR \"Polystictus\" OR \"Pseudelaenia\" OR \"Pseudocolopteryx\" OR \"Pseudotriccus\" OR \"Pyrocephalus\" OR \"Pyrrhomyias\" OR \"Ramphotrigon\" OR \"Rhynchocyclus\" OR \"Rhytipterna\" OR \"Satrapa\" OR \"Sayornis\" OR \"Serpophaga\" OR \"Silvicultrix\" OR \"Sirystes\" OR \"Stigmatura\" OR \"Sublegatus\" OR \"Suiriri\" OR \"Tachuris\" OR \"Taeniotriccus\" OR \"Todirostrum\" OR \"Tolmomyias\" OR \"Tumbezia\" OR \"Tyrannopsis\" OR \"Tyrannulus\" OR \"Tyrannus\" OR \"Uromyias\" OR \"Xenotriccus\" OR \"Xolmis\" OR \"Zimmerius\" OR \"Urocynchramus\" OR \"Artamella\" OR \"Calicalicus\" OR \"Cyanolanius\" OR \"Euryceros\" OR \"Falculea\" OR \"Hypositta\" OR \"Leptopterus\" OR \"Mystacornis\" OR \"Newtonia\" OR \"Oriolia\" OR \"Philentoma\" OR \"Prionops\" OR \"Pseudobias\" OR \"Schetba\" OR \"Tephrodornis\" OR \"Tylas\" OR \"Vanga\" OR \"Xenopirostris\" OR \"Anomalospiza\" OR \"Vidua\" OR \"Cyclarhis\" OR \"Erpornis\" OR \"Hylophilus\" OR \"Pteruthius\" OR \"Vireo\" OR \"Vireolanius\" OR \"Zeledonia\" OR \"Apalopteron\" OR \"Dasycrotapha\" OR \"Heleia\" OR \"Lophozosterops\" OR \"Sterrhoptilus\" OR \"Yuhina\" OR \"Zosterops\" OR \"Zosterornis\" OR \"Agamia\" OR \"Ardea\" OR \"Ardeola\" OR \"Botaurus\" OR \"Bubulcus\" OR \"Butorides\" OR \"Cochlearius\" OR \"Dupetor\" OR \"Egretta\" OR \"Gorsachius\" OR \"Ixobrychus\" OR \"Nyctanassa\" OR \"Nycticorax\" OR \"Pilherodius\" OR \"Syrigma\" OR \"Tigriornis\" OR \"Tigrisoma\" OR \"Zebrilus\" OR \"Balaeniceps\" OR \"Pelecanus\" OR \"Scopus\" OR \"Bostrychia\" OR \"Eudocimus\" OR \"Geronticus\" OR \"Lophotibis\" OR \"Mesembrinibis\" OR \"Nipponia\" OR \"Phimosus\" OR \"Platalea\" OR \"Plegadis\" OR \"Pseudibis\" OR \"Theristicus\" OR \"Threskiornis\" OR \"Phaethon\" OR \"Phoeniconaias\" OR \"Phoenicoparrus\" OR \"Phoenicopterus\" OR \"Bucco\" OR \"Chelidoptera\" OR \"Hapaloptila\" OR \"Hypnelus\" OR \"Malacoptila\" OR \"Micromonacha\" OR \"Monasa\" OR \"Nonnula\" OR \"Notharchus\" OR \"Nystalus\" OR \"Capito\" OR \"Eubucco\" OR \"Brachygalba\" OR \"Galbalcyrhynchus\" OR \"Galbula\" OR \"Jacamaralcyon\" OR \"Jacamerops\" OR \"Indicator\" OR \"Melichneutes\" OR \"Melignomon\" OR \"Prodotiscus\" OR \"Buccanodon\" OR \"Gymnobucco\" OR \"Lybius\" OR \"Pogoniulus\" OR \"Stactolaema\" OR \"Trachyphonus\" OR \"Psilopogon\" OR \"Blythipicus\" OR \"Campephilus\" OR \"Campethera\" OR \"Celeus\" OR \"Chloropicus\" OR \"Chrysocolaptes\" OR \"Chrysophlegma\" OR \"Colaptes\" OR \"Dendrocopos\" OR \"Dendrocoptes\" OR \"Dendropicos\" OR \"Dinopium\" OR \"Dryobates\" OR \"Dryocopus\" OR \"Gecinulus\" OR \"Geocolaptes\" OR \"Jynx\" OR \"Leiopicus\" OR \"Leuconotopicus\" OR \"Meiglyptes\" OR \"Melanerpes\" OR \"Micropternus\" OR \"Mulleripicus\" OR \"Nesoctites\" OR \"Picoides\" OR \"Piculus\" OR \"Picumnus\" OR \"Picus\" OR \"Reinwardtipicus\" OR \"Sasia\" OR \"Sphyrapicus\" OR \"Veniliornis\" OR \"Yungipicus\" OR \"Andigena\" OR \"Aulacorhynchus\" OR \"Pteroglossus\" OR \"Ramphastos\" OR \"Selenidera\" OR \"Semnornis\" OR \"Aechmophorus\" OR \"Podiceps\" OR \"Podilymbus\" OR \"Poliocephalus\" OR \"Rollandia\" OR \"Tachybaptus\" OR \"Diomedea\" OR \"Phoebastria\" OR \"Phoebetria\" OR \"Thalassarche\" OR \"Hydrobates\" OR \"Oceanodroma\" OR \"Fregetta\" OR \"Garrodia\" OR \"Nesofregetta\" OR \"Oceanites\" OR \"Pelagodroma\" OR \"Aphrodroma\" OR \"Ardenna\" OR \"Bulweria\" OR \"Calonectris\" OR \"Daption\" OR \"Fulmarus\" OR \"Halobaena\" OR \"Macronectes\" OR \"Pachyptila\" OR \"Pagodroma\" OR \"Pelecanoides\" OR \"Procellaria\" OR \"Pseudobulweria\" OR \"Pterodroma\" OR \"Puffinus\" OR \"Thalassoica\" OR \"Cacatua\" OR \"Callocephalon\" OR \"Calyptorhynchus\" OR \"Eolophus\" OR \"Lophochroa\" OR \"Nymphicus\" OR \"Probosciger\" OR \"Alipiopsitta\" OR \"Amazona\" OR \"Anodorhynchus\" OR \"Ara\" OR \"Aratinga\" OR \"Bolborhynchus\" OR \"Brotogeris\" OR \"Conuropsis\" OR \"Cyanoliseus\" OR \"Cyanopsitta\" OR \"Deroptyus\" OR \"Diopsittaca\" OR \"Enicognathus\" OR \"Eupsittula\" OR \"Forpus\" OR \"Graydidascalus\" OR \"Guarouba\" OR \"Guaruba\" OR \"Hapalopsittaca\" OR \"Leptosittaca\" OR \"Myiopsitta\" OR \"Nannopsittaca\" OR \"Orthopsittaca\" OR \"Pionites\" OR \"Pionopsitta\" OR \"Pionus\" OR \"Poicephalus\" OR \"Primolius\" OR \"Psilopsiagon\" OR \"Psittacara\" OR \"Psittacus\" OR \"Pyrilia\" OR \"Pyrrhura\" OR \"Rhynchopsitta\" OR \"Thectocercus\" OR \"Touit\" OR \"Triclaria\" OR \"Agapornis\" OR \"Alisterus\" OR \"Aprosmictus\" OR \"Barnardius\" OR \"Bolbopsittacus\" OR \"Chalcopsitta\" OR \"Charmosyna\" OR \"Coracopsis\" OR \"Cyanoramphus\" OR \"Cyclopsitta\" OR \"Eclectus\" OR \"Eos\" OR \"Eunymphicus\" OR \"Geoffroyus\" OR \"Glossopsitta\" OR \"Lathamus\" OR \"Loriculus\" OR \"Lorius\" OR \"Melopsittacus\" OR \"Micropsitta\" OR \"Neophema\" OR \"Neopsephotus\" OR \"Neopsittacus\" OR \"Northiella\" OR \"Oreopsittacus\" OR \"Parvipsitta\" OR \"Pezoporus\" OR \"Phigys\" OR \"Platycercus\" OR \"Polytelis\" OR \"Prioniturus\" OR \"Prosopeia\" OR \"Psephotellus\" OR \"Psephotus\" OR \"Pseudeos\" OR \"Psittacella\" OR \"Psittacula\" OR \"Psittaculirostris\" OR \"Psitteuteles\" OR \"Psittinus\" OR \"Psittrichas\" OR \"Purpureicephalus\" OR \"Tanygnathus\" OR \"Trichoglossus\" OR \"Vini\" OR \"Nestor\" OR \"Strigops\" OR \"Pterocles\" OR \"Syrrhaptes\" OR \"Rhea\" OR \"Aptenodytes\" OR \"Eudyptes\" OR \"Eudyptula\" OR \"Megadyptes\" OR \"Pygoscelis\" OR \"Spheniscus\" OR \"Aegolius\" OR \"Asio\" OR \"Athene\" OR \"Bubo\" OR \"Glaucidium\" OR \"Ketupa\" OR \"Lophostrix\" OR \"Megascops\" OR \"Micrathene\" OR \"Ninox\" OR \"Otus\" OR \"Pseudoscops\" OR \"Psiloscops\" OR \"Pulsatrix\" OR \"Sceloglaux\" OR \"Scotopelia\" OR \"Strix\" OR \"Surnia\" OR \"Xenoglaux\" OR \"Phodilus\" OR \"Tyto\" OR \"Aepyornis\" OR \"Mullerornis\" OR \"Struthio\" OR \"Anhinga\" OR \"Fregata\" OR \"Leucocarbo\" OR \"Microcarbo\" OR \"Nannopterum\" OR \"Phalacrocorax\" OR \"Morus\" OR \"Sula\" OR \"Crypturellus\" OR \"Eudromia\" OR \"Nothocercus\" OR \"Nothoprocta\" OR \"Nothura\" OR \"Rhynchotus\" OR \"Tinamotis\" OR \"Tinamus\" OR \"Apalharpactes\" OR \"Apaloderma\" OR \"Harpactes\" OR \"Pharomachrus\" OR \"Trogon\" OR \"Tetrastes\" OR \"Hesperiphona\") AND (\"experiment\\*\" OR \"manipulat\\*\") )) OR AB= (((\"green\\*\" OR \"herb\\*\" OR \"aromatic\\*\") AND \"nest\\*\" AND (\"bird\\*\" OR \"aves\" OR \"avian\" OR \"ornithol\\*\" OR \"passerine\\*\" OR \"passeriform\\*\" OR \"songbird\\*\" OR \"Accipiter\" OR \"Aegypius\" OR \"Aquila\" OR \"Aviceda\" OR \"Busarellus\" OR \"Butastur\" OR \"Buteo\" OR \"Buteogallus\" OR \"Chondrohierax\" OR \"Circaetus\" OR \"Circus\" OR \"Clanga\" OR \"Elanoides\" OR \"Elanus\" OR \"Gampsonyx\" OR \"Geranoaetus\" OR \"Geranospiza\" OR \"Gypaetus\" OR \"Gypohierax\" OR \"Gyps\" OR \"Haliaeetus\" OR \"Haliastur\" OR \"Harpagus\" OR \"Harpia\" OR \"Hieraaetus\" OR \"Ictinaetus\" OR \"Ictinia\" OR \"Kaupifalco\" OR \"Leptodon\" OR \"Leucopternis\" OR \"Lophotriorchis\" OR \"Milvus\" OR \"Morphnarchus\" OR \"Morphnus\" OR \"Necrosyrtes\" OR \"Neophron\" OR \"Nisaetus\" OR \"Parabuteo\" OR \"Pernis\" OR \"Pithecophaga\" OR \"Polemaetus\" OR \"Pseudastur\" OR \"Rostrhamus\" OR \"Rupornis\" OR \"Sarcogyps\" OR \"Spilornis\" OR \"Spizaetus\" OR \"Stephanoaetus\" OR \"Terathopius\" OR \"Torgos\" OR \"Trigonoceps\" OR \"Cathartes\" OR \"Coragyps\" OR \"Gymnogyps\" OR \"Sarcoramphus\" OR \"Vultur\" OR \"Pandion\" OR \"Sagittarius\" OR \"Aix\" OR \"Alopochen\" OR \"Amazonetta\" OR \"Anas\" OR \"Anser\" OR \"Asarcornis\" OR \"Aythya\" OR \"Branta\" OR \"Bucephala\" OR \"Cairina\" OR \"Callonetta\" OR \"Cereopsis\" OR \"Chen\" OR \"Chenonetta\" OR \"Chloephaga\" OR \"Clangula\" OR \"Coscoroba\" OR \"Cyanochen\" OR \"Cygnus\" OR \"Dendrocygna\" OR \"Heteronetta\" OR \"Histrionicus\" OR \"Hymenolaimus\" OR \"Lophodytes\" OR \"Lophonetta\" OR \"Malacorhynchus\" OR \"Mareca\" OR \"Marmaronetta\" OR \"Melanitta\" OR \"Merganetta\" OR \"Mergellus\" OR \"Mergus\" OR \"Neochen\" OR \"Netta\" OR \"Nettapus\" OR \"Nomonyx\" OR \"Oxyura\" OR \"Plectropterus\" OR \"Polysticta\" OR \"Pteronetta\" OR \"Sarkidiornis\" OR \"Sibirionetta\" OR \"Somateria\" OR \"Spatula\" OR \"Tachyeres\" OR \"Tadorna\" OR \"Thalassornis\" OR \"Anhima\" OR \"Chauna\" OR \"Anseranas\" OR \"Aegotheles\" OR \"Aerodramus\" OR \"Aeronautes\" OR \"Apus\" OR \"Chaetura\" OR \"Collocalia\" OR \"Cypseloides\" OR \"Cypsiurus\" OR \"Hirundapus\" OR \"Panyptila\" OR \"Streptoprocne\" OR \"Tachornis\" OR \"Tachymarptis\" OR \"Hemiprocne\" OR \"Abeillia\" OR \"Adelomyia\" OR \"Aglaeactis\" OR \"Aglaiocercus\" OR \"Amazilia\" OR \"Androdon\" OR \"Anopetia\" OR \"Anthocephala\" OR \"Anthracothorax\" OR \"Archilochus\" OR \"Atthis\" OR \"Augastes\" OR \"Avocettula\" OR \"Basilinna\" OR \"Boissonneaua\" OR \"Calliphlox\" OR \"Calypte\" OR \"Campylopterus\" OR \"Chaetocercus\" OR \"Chalcostigma\" OR \"Chalybura\" OR \"Chlorestes\" OR \"Chlorostilbon\" OR \"Chrysolampis\" OR \"Chrysuronia\" OR \"Clytolaema\" OR \"Coeligena\" OR \"Colibri\" OR \"Cyanophaia\" OR \"Cynanthus\" OR \"Discosura\" OR \"Doricha\" OR \"Doryfera\" OR \"Elvira\" OR \"Ensifera\" OR \"Eriocnemis\" OR \"Eugenes\" OR \"Eulampis\" OR \"Eulidia\" OR \"Eupetomena\" OR \"Eupherusa\" OR \"Eutoxeres\" OR \"Florisuga\" OR \"Glaucis\" OR \"Goethalsia\" OR \"Goldmania\" OR \"Haplophaedia\" OR \"Heliactin\" OR \"Heliangelus\" OR \"Heliodoxa\" OR \"Heliomaster\" OR \"Heliothryx\" OR \"Hylocharis\" OR \"Juliamyia\" OR \"Klais\" OR \"Lafresnaya\" OR \"Lampornis\" OR \"Lamprolaima\" OR \"Lepidopyga\" OR \"Lesbia\" OR \"Leucippus\" OR \"Leucochloris\" OR \"Lophornis\" OR \"Mellisuga\" OR \"Metallura\" OR \"Microchera\" OR \"Myrmia\" OR \"Myrtis\" OR \"Ocreatus\" OR \"Opisthoprora\" OR \"Oreonympha\" OR \"Oreotrochilus\" OR \"Orthorhyncus\" OR \"Oxypogon\" OR \"Panterpe\" OR \"Patagona\" OR \"Phaeochroa\" OR \"Phaethornis\" OR \"Phlogophilus\" OR \"Polyonymus\" OR \"Polytmus\" OR \"Pterophanes\" OR \"Ramphodon\" OR \"Ramphomicron\" OR \"Rhodopis\" OR \"Sappho\" OR \"Schistes\" OR \"Selasphorus\" OR \"Sephanoides\" OR \"Stephanoxis\" OR \"Sternoclyta\" OR \"Taphrospilus\" OR \"Thalurania\" OR \"Thaumastura\" OR \"Threnetes\" OR \"Topaza\" OR \"Trochilus\" OR \"Urochroa\" OR \"Urosticte\" OR \"Apteryx\" OR \"Anthracoceros\" OR \"Buceros\" OR \"Bycanistes\" OR \"Lophoceros\" OR \"Penelopides\" OR \"Rhabdotorrhinus\" OR \"Rhyticeros\" OR \"Tockus\" OR \"Bucorvus\" OR \"Phoeniculus\" OR \"Rhinopomastus\" OR \"Upupa\" OR \"Antrostomus\" OR \"Caprimulgus\" OR \"Chordeiles\" OR \"Eleothreptus\" OR \"Eurostopodus\" OR \"Hydropsalis\" OR \"Lurocalis\" OR \"Lyncornis\" OR \"Nyctidromus\" OR \"Nyctiphrynus\" OR \"Nyctipolus\" OR \"Nyctiprogne\" OR \"Phalaenoptilus\" OR \"Setopagis\" OR \"Systellura\" OR \"Uropsalis\" OR \"Nyctibius\" OR \"Batrachostomus\" OR \"Podargus\" OR \"Steatornis\" OR \"Cariama\" OR \"Casuarius\" OR \"Dromaius\" OR \"Aethia\" OR \"Alca\" OR \"Alle\" OR \"Brachyramphus\" OR \"Cepphus\" OR \"Cerorhinca\" OR \"Fratercula\" OR \"Pinguinus\" OR \"Ptychoramphus\" OR \"Synthliboramphus\" OR \"Uria\" OR \"Burhinus\" OR \"Anarhynchus\" OR \"Charadrius\" OR \"Elseyornis\" OR \"Erythrogonys\" OR \"Hoploxypterus\" OR \"Oreopholus\" OR \"Peltohyas\" OR \"Phegornis\" OR \"Pluvialis\" OR \"Thinornis\" OR \"Vanellus\" OR \"Chionis\" OR \"Dromas\" OR \"Cursorius\" OR \"Glareola\" OR \"Rhinoptilus\" OR \"Stiltia\" OR \"Haematopus\" OR \"Actophilornis\" OR \"Hydrophasianus\" OR \"Irediparra\" OR \"Jacana\" OR \"Metopidius\" OR \"Microparra\" OR \"Anous\" OR \"Chlidonias\" OR \"Chroicocephalus\" OR \"Creagrus\" OR \"Gelochelidon\" OR \"Gygis\" OR \"Hydrocoloeus\" OR \"Hydroprogne\" OR \"Ichthyaetus\" OR \"Larosterna\" OR \"Larus\" OR \"Leucophaeus\" OR \"Onychoprion\" OR \"Pagophila\" OR \"Phaetusa\" OR \"Rhodostethia\" OR \"Rissa\" OR \"Rynchops\" OR \"Sterna\" OR \"Sternula\" OR \"Thalasseus\" OR \"Xema\" OR \"Pedionomus\" OR \"Pluvianellus\" OR \"Pluvianus\" OR \"Himantopus\" OR \"Recurvirostra\" OR \"Nycticryphes\" OR \"Rostratula\" OR \"Actitis\" OR \"Arenaria\" OR \"Bartramia\" OR \"Calidris\" OR \"Coenocorypha\" OR \"Gallinago\" OR \"Limnodromus\" OR \"Limosa\" OR \"Lymnocryptes\" OR \"Numenius\" OR \"Phalaropus\" OR \"Scolopax\" OR \"Tringa\" OR \"Xenus\" OR \"Stercorarius\" OR \"Attagis\" OR \"Thinocorus\" OR \"Turnix\" OR \"Ciconia\" OR \"Ephippiorhynchus\" OR \"Jabiru\" OR \"Leptoptilos\" OR \"Mycteria\" OR \"Colius\" OR \"Urocolius\" OR \"Alectroenas\" OR \"Alopecoenas\" OR \"Caloenas\" OR \"Chalcophaps\" OR \"Claravis\" OR \"Columba\" OR \"Columbina\" OR \"Didunculus\" OR \"Drepanoptila\" OR \"Ducula\" OR \"Ectopistes\" OR \"Gallicolumba\" OR \"Geopelia\" OR \"Geophaps\" OR \"Geotrygon\" OR \"Goura\" OR \"Gymnophaps\" OR \"Hemiphaga\" OR \"Henicophaps\" OR \"Leptotila\" OR \"Leptotrygon\" OR \"Leucosarcia\" OR \"Lopholaimus\" OR \"Macropygia\" OR \"Metriopelia\" OR \"Ocyphaps\" OR \"Oena\" OR \"Otidiphaps\" OR \"Patagioenas\" OR \"Petrophassa\" OR \"Pezophaps\" OR \"Phapitreron\" OR \"Phaps\" OR \"Ptilinopus\" OR \"Raphus\" OR \"Reinwardtoena\" OR \"Spilopelia\" OR \"Streptopelia\" OR \"Treron\" OR \"Trugon\" OR \"Turacoena\" OR \"Turtur\" OR \"Uropelia\" OR \"Zenaida\" OR \"Zentrygon\" OR \"Actenoides\" OR \"Alcedo\" OR \"Caridonax\" OR \"Ceryle\" OR \"Ceyx\" OR \"Chloroceryle\" OR \"Cittura\" OR \"Corythornis\" OR \"Dacelo\" OR \"Halcyon\" OR \"Ispidina\" OR \"Lacedo\" OR \"Megaceryle\" OR \"Melidora\" OR \"Syma\" OR \"Tanysiptera\" OR \"Todiramphus\" OR \"Atelornis\" OR \"Brachypteracias\" OR \"Geobiastes\" OR \"Coracias\" OR \"Eurystomus\" OR \"Merops\" OR \"Nyctyornis\" OR \"Baryphthengus\" OR \"Electron\" OR \"Eumomota\" OR \"Hylomanes\" OR \"Momotus\" OR \"Todus\" OR \"Cacomantis\" OR \"Carpococcyx\" OR \"Centropus\" OR \"Cercococcyx\" OR \"Chrysococcyx\" OR \"Clamator\" OR \"Coccycua\" OR \"Coccyzus\" OR \"Coua\" OR \"Crotophaga\" OR \"Cuculus\" OR \"Dasylophus\" OR \"Dromococcyx\" OR \"Eudynamys\" OR \"Geococcyx\" OR \"Guira\" OR \"Hierococcyx\" OR \"Morococcyx\" OR \"Neomorphus\" OR \"Pachycoccyx\" OR \"Phaenicophaeus\" OR \"Piaya\" OR \"Rhinortha\" OR \"Scythrops\" OR \"Surniculus\" OR \"Tapera\" OR \"Urodynamis\" OR \"Zanclostomus\" OR \"Dinornis\" OR \"Anomalopteryx\" OR \"Emeus\" OR \"Euryapteryx\" OR \"Eurypyga\" OR \"Rhynochetos\" OR \"Caracara\" OR \"Daptrius\" OR \"Falco\" OR \"Herpetotheres\" OR \"Ibycter\" OR \"Micrastur\" OR \"Microhierax\" OR \"Milvago\" OR \"Phalcoboenus\" OR \"Polihierax\" OR \"Spiziapteryx\" OR \"Aburria\" OR \"Chamaepetes\" OR \"Crax\" OR \"Mitu\" OR \"Nothocrax\" OR \"Oreophasis\" OR \"Ortalis\" OR \"Pauxi\" OR \"Penelope\" OR \"Penelopina\" OR \"Pipile\" OR \"Alectura\" OR \"Megapodius\" OR \"Acryllium\" OR \"Guttera\" OR \"Numida\" OR \"Callipepla\" OR \"Colinus\" OR \"Cyrtonyx\" OR \"Dendrortyx\" OR \"Odontophorus\" OR \"Oreortyx\" OR \"Philortyx\" OR \"Ptilopachus\" OR \"Rhynchortyx\" OR \"Alectoris\" OR \"Ammoperdix\" OR \"Arborophila\" OR \"Argusianus\" OR \"Bambusicola\" OR \"Bonasa\" OR \"Caloperdix\" OR \"Centrocercus\" OR \"Chrysolophus\" OR \"Coturnix\" OR \"Crossoptilon\" OR \"Dendragapus\" OR \"Excalfactoria\" OR \"Falcipennis\" OR \"Francolinus\" OR \"Gallus\" OR \"Haematortyx\" OR \"Ithaginis\" OR \"Lagopus\" OR \"Lerwa\" OR \"Lophophorus\" OR \"Lophura\" OR \"Lyrurus\" OR \"Meleagris\" OR \"Pavo\" OR \"Peliperdix\" OR \"Perdix\" OR \"Phasianus\" OR \"Polyplectron\" OR \"Pternistis\" OR \"Pucrasia\" OR \"Rhizothera\" OR \"Rollulus\" OR \"Scleroptila\" OR \"Syrmaticus\" OR \"Tetrao\" OR \"Tetraogallus\" OR \"Tetraophasis\" OR \"Tragopan\" OR \"Tympanuchus\" OR \"Gavia\" OR \"Aramus\" OR \"Anthropoides\" OR \"Antigone\" OR \"Balearica\" OR \"Bugeranus\" OR \"Grus\" OR \"Leucogeranus\" OR \"Heliornis\" OR \"Psophia\" OR \"Aenigmatolimnas\" OR \"Amaurolimnas\" OR \"Amaurornis\" OR \"Anurolimnas\" OR \"Aramides\" OR \"Atlantisia\" OR \"Coturnicops\" OR \"Crex\" OR \"Dryolimnas\" OR \"Eulabeornis\" OR \"Fulica\" OR \"Gallicrex\" OR \"Gallinula\" OR \"Gallirallus\" OR \"Laterallus\" OR \"Lewinia\" OR \"Micropygia\" OR \"Neocrex\" OR \"Nesoclopeus\" OR \"Paragallinula\" OR \"Pardirallus\" OR \"Porphyrio\" OR \"Porphyriops\" OR \"Porzana\" OR \"Rallicula\" OR \"Rallina\" OR \"Rallus\" OR \"Tribonyx\" OR \"Canirallus\" OR \"Sarothrura\" OR \"Leptosomus\" OR \"Corythaeola\" OR \"Corythaixoides\" OR \"Crinifer\" OR \"Musophaga\" OR \"Tauraco\" OR \"Opisthocomus\" OR \"Afrotis\" OR \"Ardeotis\" OR \"Chlamydotis\" OR \"Neotis\" OR \"Otis\" OR \"Tetrax\" OR \"Acanthisitta\" OR \"Pachyplichas\" OR \"Traversia\" OR \"Xenicus\" OR \"Acanthiza\" OR \"Acanthornis\" OR \"Aethomyias\" OR \"Aphelocephala\" OR \"Calamanthus\" OR \"Gerygone\" OR \"Hylacola\" OR \"Neosericornis\" OR \"Oreoscopus\" OR \"Origma\" OR \"Pachycare\" OR \"Pycnoptilus\" OR \"Pyrrholaemus\" OR \"Sericornis\" OR \"Smicrornis\" OR \"Acrocephalus\" OR \"Arundinax\" OR \"Calamonastides\" OR \"Hippolais\" OR \"Iduna\" OR \"Nesillas\" OR \"Aegithalos\" OR \"Leptopoecile\" OR \"Psaltriparus\" OR \"Aegithina\" OR \"Alaemon\" OR \"Alauda\" OR \"Alaudala\" OR \"Ammomanes\" OR \"Calandrella\" OR \"Calendulauda\" OR \"Chersomanes\" OR \"Eremophila\" OR \"Eremopterix\" OR \"Galerida\" OR \"Lullula\" OR \"Melanocorypha\" OR \"Mirafra\" OR \"Pinarocorys\" OR \"Spizocorys\" OR \"Artamus\" OR \"Gymnorhina\" OR \"Melloria\" OR \"Bombycilla\" OR \"Buphagus\" OR \"Calcarius\" OR \"Plectrophenax\" OR \"Rhynchophanes\" OR \"Callaeas\" OR \"Heteralocha\" OR \"Philesturnus\" OR \"Calyptophilus\" OR \"Campephaga\" OR \"Ceblepyris\" OR \"Coracina\" OR \"Edolisoma\" OR \"Lalage\" OR \"Malindangia\" OR \"Pericrocotus\" OR \"Amaurospiza\" OR \"Cardinalis\" OR \"Caryothraustes\" OR \"Chlorothraupis\" OR \"Cyanocompsa\" OR \"Cyanoloxia\" OR \"Granatellus\" OR \"Habia\" OR \"Passerina\" OR \"Periporphyrus\" OR \"Pheucticus\" OR \"Piranga\" OR \"Spiza\" OR \"Certhia\" OR \"Salpornis\" OR \"Abroscopus\" OR \"Cettia\" OR \"Horornis\" OR \"Phyllergates\" OR \"Tesia\" OR \"Urosphena\" OR \"Chloropsis\" OR \"Cinclus\" OR \"Apalis\" OR \"Artisornis\" OR \"Camaroptera\" OR \"Cisticola\" OR \"Eremomela\" OR \"Heliolais\" OR \"Hypergerus\" OR \"Neomixis\" OR \"Oreolais\" OR \"Orthotomus\" OR \"Phragmacia\" OR \"Poliolais\" OR \"Prinia\" OR \"Schistolais\" OR \"Urolais\" OR \"Urorhipis\" OR \"Climacteris\" OR \"Cormobates\" OR \"Conopophaga\" OR \"Struthidea\" OR \"Aphelocoma\" OR \"Calocitta\" OR \"Cissa\" OR \"Coloeus\" OR \"Corvus\" OR \"Cyanocitta\" OR \"Cyanocorax\" OR \"Cyanolyca\" OR \"Cyanopica\" OR \"Dendrocitta\" OR \"Garrulus\" OR \"Gymnorhinus\" OR \"Nucifraga\" OR \"Perisoreus\" OR \"Pica\" OR \"Platylophus\" OR \"Podoces\" OR \"Psilorhinus\" OR \"Ptilostomus\" OR \"Pyrrhocorax\" OR \"Urocissa\" OR \"Ampelioides\" OR \"Ampelion\" OR \"Carpornis\" OR \"Cephalopterus\" OR \"Conioptilon\" OR \"Cotinga\" OR \"Doliornis\" OR \"Gymnoderus\" OR \"Haematoderus\" OR \"Lipaugus\" OR \"Perissocephalus\" OR \"Phoenicircus\" OR \"Phytotoma\" OR \"Pipreola\" OR \"Porphyrolaema\" OR \"Procnias\" OR \"Pyroderus\" OR \"Querula\" OR \"Rupicola\" OR \"Snowornis\" OR \"Xipholena\" OR \"Zaratornis\" OR \"Dasyornis\" OR \"Dicaeum\" OR \"Prionochilus\" OR \"Dicrurus\" OR \"Donacobius\" OR \"Dulus\" OR \"Emberiza\" OR \"Amadina\" OR \"Amandava\" OR \"Cryptospiza\" OR \"Erythrura\" OR \"Estrilda\" OR \"Euodice\" OR \"Euschistospiza\" OR \"Lagonosticta\" OR \"Lonchura\" OR \"Mandingoa\" OR \"Neochmia\" OR \"Nesocharis\" OR \"Nigrita\" OR \"Ortygospiza\" OR \"Parmoptila\" OR \"Pyrenestes\" OR \"Pytilia\" OR \"Spermophaga\" OR \"Stagonopleura\" OR \"Taeniopygia\" OR \"Uraeginthus\" OR \"Calyptomena\" OR \"Cymbirhynchus\" OR \"Eurylaimus\" OR \"Psarisomus\" OR \"Serilophus\" OR \"Smithornis\" OR \"Chamaeza\" OR \"Formicarius\" OR \"Acanthis\" OR \"Agraphospiza\" OR \"Akialoa\" OR \"Bucanetes\" OR \"Carduelis\" OR \"Carpodacus\" OR \"Chloris\" OR \"Chlorodrepanis\" OR \"Chlorophonia\" OR \"Chrysocorythus\" OR \"Coccothraustes\" OR \"Crithagra\" OR \"Drepanis\" OR \"Eophona\" OR \"Euphonia\" OR \"Fringilla\" OR \"Haemorhous\" OR \"Hemignathus\" OR \"Himatione\" OR \"Leucosticte\" OR \"Linaria\" OR \"Linurgus\" OR \"Loxia\" OR \"Loxioides\" OR \"Loxops\" OR \"Magumma\" OR \"Melamprosops\" OR \"Oreomystis\" OR \"Paroreomyza\" OR \"Pinicola\" OR \"Procarduelis\" OR \"Pseudonestor\" OR \"Psittirostra\" OR \"Pyrrhoplectes\" OR \"Pyrrhula\" OR \"Rhodopechys\" OR \"Rhodospiza\" OR \"Serinus\" OR \"Spinus\" OR \"Telespiza\" OR \"Anabacerthia\" OR \"Anabazenops\" OR \"Ancistrops\" OR \"Anumbius\" OR \"Aphrastura\" OR \"Asthenes\" OR \"Automolus\" OR \"Berlepschia\" OR \"Campylorhamphus\" OR \"Certhiasomus\" OR \"Certhiaxis\" OR \"Cinclodes\" OR \"Clibanornis\" OR \"Coryphistera\" OR \"Cranioleuca\" OR \"Deconychura\" OR \"Dendrexetastes\" OR \"Dendrocincla\" OR \"Dendrocolaptes\" OR \"Dendroplex\" OR \"Drymornis\" OR \"Drymotoxeres\" OR \"Furnarius\" OR \"Geocerthia\" OR \"Geositta\" OR \"Glyphorynchus\" OR \"Heliobletus\" OR \"Hellmayrea\" OR \"Hylexetastes\" OR \"Lepidocolaptes\" OR \"Leptasthenura\" OR \"Limnoctites\" OR \"Limnornis\" OR \"Lochmias\" OR \"Margarornis\" OR \"Mazaria\" OR \"Megaxenops\" OR \"Metopothrix\" OR \"Microxenops\" OR \"Nasica\" OR \"Ochetorhynchus\" OR \"Phacellodomus\" OR \"Philydor\" OR \"Phleocryptes\" OR \"Premnoplex\" OR \"Premnornis\" OR \"Pseudasthenes\" OR \"Pseudocolaptes\" OR \"Pseudoseisura\" OR \"Pygarrhichas\" OR \"Roraimia\" OR \"Schoeniophylax\" OR \"Sclerurus\" OR \"Sittasomus\" OR \"Spartonoica\" OR \"Sylviorthorhynchus\" OR \"Synallaxis\" OR \"Syndactyla\" OR \"Tarphonomus\" OR \"Thripadectes\" OR \"Thripophaga\" OR \"Upucerthia\" OR \"Xenerpestes\" OR \"Xenops\" OR \"Xiphocolaptes\" OR \"Xiphorhynchus\" OR \"Grallaria\" OR \"Grallaricula\" OR \"Hylopezus\" OR \"Myrmothera\" OR \"Alopochelidon\" OR \"Atticora\" OR \"Cecropis\" OR \"Delichon\" OR \"Haplochelidon\" OR \"Hirundo\" OR \"Neochelidon\" OR \"Notiochelidon\" OR \"Orochelidon\" OR \"Petrochelidon\" OR \"Phedina\" OR \"Progne\" OR \"Psalidoprocne\" OR \"Pseudhirundo\" OR \"Pseudochelidon\" OR \"Ptyonoprogne\" OR \"Riparia\" OR \"Stelgidopteryx\" OR \"Tachycineta\" OR \"Hyliota\" OR \"Hypocolius\" OR \"Agelaioides\" OR \"Agelaius\" OR \"Agelasticus\" OR \"Amblycercus\" OR \"Amblyramphus\" OR \"Anumara\" OR \"Cacicus\" OR \"Chrysomus\" OR \"Curaeus\" OR \"Dives\" OR \"Dolichonyx\" OR \"Euphagus\" OR \"Gnorimopsar\" OR \"Gymnomystax\" OR \"Hypopyrrhus\" OR \"Icterus\" OR \"Lampropsar\" OR \"Leistes\" OR \"Macroagelaius\" OR \"Molothrus\" OR \"Nesopsar\" OR \"Oreopsar\" OR \"Psarocolius\" OR \"Pseudoleistes\" OR \"Quiscalus\" OR \"Sturnella\" OR \"Xanthocephalus\" OR \"Xanthopsar\" OR \"Icteria\" OR \"Ifrita\" OR \"Irena\" OR \"Corvinella\" OR \"Eurocephalus\" OR \"Lanius\" OR \"Actinodura\" OR \"Argya\" OR \"Garrulax\" OR \"Grammatoptila\" OR \"Heterophasia\" OR \"Ianthocincla\" OR \"Laniellus\" OR \"Leiothrix\" OR \"Liocichla\" OR \"Minla\" OR \"Pterorhinus\" OR \"Trochalopteron\" OR \"Turdoides\" OR \"Bradypterus\" OR \"Cincloramphus\" OR \"Helopsaltes\" OR \"Locustella\" OR \"Megalurus\" OR \"Poodytes\" OR \"Machaerirhynchus\" OR \"Graueria\" OR \"Hylia\" OR \"Macrosphenus\" OR \"Melocichla\" OR \"Sylvietta\" OR \"Chlorophoneus\" OR \"Dryoscopus\" OR \"Laniarius\" OR \"Malaconotus\" OR \"Nilaus\" OR \"Rhodophoneus\" OR \"Tchagra\" OR \"Telophorus\" OR \"Amytornis\" OR \"Chenorhamphus\" OR \"Clytomyias\" OR \"Malurus\" OR \"Stipiturus\" OR \"Melampitta\" OR \"Melanocharis\" OR \"Oedistoma\" OR \"Toxorhamphus\" OR \"Melanopareia\" OR \"Acanthagenys\" OR \"Acanthorhynchus\" OR \"Anthochaera\" OR \"Anthornis\" OR \"Caligavis\" OR \"Entomyzon\" OR \"Epthianura\" OR \"Glycifohia\" OR \"Gymnomyza\" OR \"Lichmera\" OR \"Manorina\" OR \"Melidectes\" OR \"Melilestes\" OR \"Meliphaga\" OR \"Melipotes\" OR \"Melithreptus\" OR \"Myzomela\" OR \"Nesoptilotis\" OR \"Philemon\" OR \"Phylidonyris\" OR \"Prosthemadera\" OR \"Ptiloprora\" OR \"Ptilotula\" OR \"Pycnopygius\" OR \"Timeliopsis\" OR \"Xanthotis\" OR \"Menura\" OR \"Allenia\" OR \"Cinclocerthia\" OR \"Dumetella\" OR \"Margarops\" OR \"Melanoptila\" OR \"Melanotis\" OR \"Mimus\" OR \"Oreoscoptes\" OR \"Ramphocinclus\" OR \"Toxostoma\" OR \"Lamprospiza\" OR \"Mitrospingus\" OR \"Moho\" OR \"Mohoua\" OR \"Arses\" OR \"Carterornis\" OR \"Clytorhynchus\" OR \"Grallina\" OR \"Hypothymis\" OR \"Monarcha\" OR \"Myiagra\" OR \"Symposiachrus\" OR \"Terpsiphone\" OR \"Trochocercus\" OR \"Anthus\" OR \"Macronyx\" OR \"Motacilla\" OR \"Alethe\" OR \"Anthipes\" OR \"Brachypteryx\" OR \"Calliope\" OR \"Campicoloides\" OR \"Cercotrichas\" OR \"Chamaetylas\" OR \"Copsychus\" OR \"Cossypha\" OR \"Cyanoptila\" OR \"Cyornis\" OR \"Enicurus\" OR \"Erithacus\" OR \"Eumyias\" OR \"Ficedula\" OR \"Fraseria\" OR \"Irania\" OR \"Larvivora\" OR \"Leonardina\" OR \"Luscinia\" OR \"Melaenornis\" OR \"Monticola\" OR \"Muscicapa\" OR \"Myiomela\" OR \"Myioparus\" OR \"Myophonus\" OR \"Myrmecocichla\" OR \"Niltava\" OR \"Oenanthe\" OR \"Phoenicurus\" OR \"Pogonocichla\" OR \"Saxicola\" OR \"Sheppardia\" OR \"Sholicola\" OR \"Stiphrornis\" OR \"Tarsiger\" OR \"Thamnolaea\" OR \"Vauriella\" OR \"Aethopyga\" OR \"Anabathmis\" OR \"Anthreptes\" OR \"Arachnothera\" OR \"Chalcomitra\" OR \"Cinnyris\" OR \"Cyanomitra\" OR \"Deleornis\" OR \"Hedydipna\" OR \"Kurochkinegramma\" OR \"Leptocoma\" OR \"Nectarinia\" OR \"Daphoenositta\" OR \"Nesospingus\" OR \"Nicator\" OR \"Notiomystis\" OR \"Aleadryas\" OR \"Oriolus\" OR \"Pitohui\" OR \"Sphecotheres\" OR \"Turnagra\" OR \"Colluricincla\" OR \"Falcunculus\" OR \"Melanorectes\" OR \"Pachycephala\" OR \"Pseudorectes\" OR \"Panurus\" OR \"Cicinnurus\" OR \"Diphyllodes\" OR \"Manucodia\" OR \"Paradisaea\" OR \"Ptiloris\" OR \"Paramythia\" OR \"Pardalotus\" OR \"Baeolophus\" OR \"Cephalopyrus\" OR \"Cyanistes\" OR \"Lophophanes\" OR \"Machlolophus\" OR \"Melaniparus\" OR \"Melanochlora\" OR \"Pardaliparus\" OR \"Parus\" OR \"Periparus\" OR \"Poecile\" OR \"Pseudopodoces\" OR \"Sittiparus\" OR \"Sylviparus\" OR \"Basileuterus\" OR \"Cardellina\" OR \"Catharopeza\" OR \"Dendroica\" OR \"Geothlypis\" OR \"Helmitheros\" OR \"Leiothlypis\" OR \"Limnothlypis\" OR \"Mniotilta\" OR \"Myioborus\" OR \"Myiothlypis\" OR \"Oporornis\" OR \"Oreothlypis\" OR \"Parkesia\" OR \"Protonotaria\" OR \"Seiurus\" OR \"Setophaga\" OR \"Vermivora\" OR \"Aimophila\" OR \"Ammodramus\" OR \"Amphispiza\" OR \"Arremon\" OR \"Arremonops\" OR \"Artemisiospiza\" OR \"Atlapetes\" OR \"Calamospiza\" OR \"Chlorospingus\" OR \"Chondestes\" OR \"Junco\" OR \"Melospiza\" OR \"Melozone\" OR \"Oreothraupis\" OR \"Oriturus\" OR \"Passerculus\" OR \"Passerella\" OR \"Peucaea\" OR \"Pezopetes\" OR \"Pipilo\" OR \"Pooecetes\" OR \"Pselliophorus\" OR \"Rhynchospiza\" OR \"Spizella\" OR \"Spizelloides\" OR \"Xenospiza\" OR \"Zonotrichia\" OR \"Carpospiza\" OR \"Gymnoris\" OR \"Hypocryptadius\" OR \"Montifringilla\" OR \"Onychostruthus\" OR \"Passer\" OR \"Petronia\" OR \"Pyrgilauda\" OR \"Alcippe\" OR \"Gampsorhynchus\" OR \"Illadopsis\" OR \"Jabouilleia\" OR \"Kenopia\" OR \"Laticilla\" OR \"Malacocincla\" OR \"Malacopteron\" OR \"Napothera\" OR \"Pellorneum\" OR \"Rimator\" OR \"Trichastoma\" OR \"Amalocichla\" OR \"Drymodes\" OR \"Eopsaltria\" OR \"Eugerygone\" OR \"Heteromyias\" OR \"Melanodryas\" OR \"Microeca\" OR \"Monachella\" OR \"Pachycephalopsis\" OR \"Peneoenanthe\" OR \"Peneothello\" OR \"Petroica\" OR \"Poecilodryas\" OR \"Tregellasia\" OR \"Peucedramus\" OR \"Microligea\" OR \"Phaenicophilus\" OR \"Xenoligea\" OR \"Phylloscopus\" OR \"Picathartes\" OR \"Antilophia\" OR \"Ceratopipra\" OR \"Chiroxiphia\" OR \"Chloropipo\" OR \"Corapipo\" OR \"Cryptopipo\" OR \"Heterocercus\" OR \"Ilicura\" OR \"Lepidothrix\" OR \"Machaeropterus\" OR \"Manacus\" OR \"Masius\" OR \"Neopelma\" OR \"Pipra\" OR \"Pseudopipra\" OR \"Tyranneutes\" OR \"Xenopipo\" OR \"Erythropitta\" OR \"Hydrornis\" OR \"Pitta\" OR \"Batis\" OR \"Platysteira\" OR \"Anaplectes\" OR \"Bubalornis\" OR \"Euplectes\" OR \"Malimbus\" OR \"Plocepasser\" OR \"Ploceus\" OR \"Quelea\" OR \"Sporopipes\" OR \"Pnoepyga\" OR \"Microbates\" OR \"Polioptila\" OR \"Ramphocaenus\" OR \"Garritornis\" OR \"Prunella\" OR \"Cinclosoma\" OR \"Ptilorrhoa\" OR \"Phainopepla\" OR \"Phainoptila\" OR \"Ptiliogonys\" OR \"Ailuroedus\" OR \"Amblyornis\" OR \"Ptilonorhynchus\" OR \"Sericulus\" OR \"Alophoixus\" OR \"Andropadus\" OR \"Arizelocichla\" OR \"Atimastillas\" OR \"Baeopogon\" OR \"Bleda\" OR \"Chlorocichla\" OR \"Criniger\" OR \"Eurillas\" OR \"Hemixos\" OR \"Hypsipetes\" OR \"Iole\" OR \"Ixos\" OR \"Neolestes\" OR \"Phyllastrephus\" OR \"Pycnonotus\" OR \"Spizixos\" OR \"Stelgidillas\" OR \"Tricholestes\" OR \"Regulus\" OR \"Anthoscopus\" OR \"Auriparus\" OR \"Remiz\" OR \"Rhagologus\" OR \"Eleoscytalopus\" OR \"Liosceles\" OR \"Psilorhamphus\" OR \"Pteroptochos\" OR \"Scelorchilus\" OR \"Scytalopus\" OR \"Teledromas\" OR \"Rhipidura\" OR \"Rhodinocichla\" OR \"Sapayoa\" OR \"Sitta\" OR \"Spindalis\" OR \"Chelidorhynx\" OR \"Culicicapa\" OR \"Elminia\" OR \"Acridotheres\" OR \"Agropsar\" OR \"Ampeliceps\" OR \"Aplonis\" OR \"Basilornis\" OR \"Cinnyricinclus\" OR \"Creatophora\" OR \"Gracula\" OR \"Gracupica\" OR \"Hartlaubius\" OR \"Hylopsar\" OR \"Lamprotornis\" OR \"Leucopsar\" OR \"Mino\" OR \"Notopholia\" OR \"Onychognathus\" OR \"Pastor\" OR \"Poeoptera\" OR \"Rhabdornis\" OR \"Sarcops\" OR \"Scissirostrum\" OR \"Speculipastor\" OR \"Spodiopsar\" OR \"Streptocitta\" OR \"Sturnia\" OR \"Sturnus\" OR \"Chamaea\" OR \"Chleuasicus\" OR \"Chloropeta\" OR \"Chrysomma\" OR \"Conostoma\" OR \"Fulvetta\" OR \"Lioparus\" OR \"Paradoxornis\" OR \"Pseudoalcippe\" OR \"Psittiparus\" OR \"Rhopophilus\" OR \"Sinosuthora\" OR \"Suthora\" OR \"Sylvia\" OR \"Teretistris\" OR \"Akletos\" OR \"Ampelornis\" OR \"Aprositornis\" OR \"Batara\" OR \"Cercomacra\" OR \"Cercomacroides\" OR \"Cymbilaimus\" OR \"Dichrozona\" OR \"Drymophila\" OR \"Dysithamnus\" OR \"Epinecrophylla\" OR \"Euchrepomis\" OR \"Formicivora\" OR \"Frederickena\" OR \"Gymnocichla\" OR \"Gymnopithys\" OR \"Hafferia\" OR \"Herpsilochmus\" OR \"Hylophylax\" OR \"Hypocnemis\" OR \"Hypocnemoides\" OR \"Hypoedaleus\" OR \"Isleria\" OR \"Mackenziaena\" OR \"Megastictus\" OR \"Microrhopias\" OR \"Myrmeciza\" OR \"Myrmelastes\" OR \"Myrmoborus\" OR \"Myrmochanes\" OR \"Myrmoderus\" OR \"Myrmophylax\" OR \"Myrmorchilus\" OR \"Myrmornis\" OR \"Myrmotherula\" OR \"Neoctantes\" OR \"Oneillornis\" OR \"Percnostola\" OR \"Phaenostictus\" OR \"Phlegopsis\" OR \"Pithys\" OR \"Poliocrania\" OR \"Pygiptila\" OR \"Pyriglena\" OR \"Rhegmatorhina\" OR \"Rhopias\" OR \"Rhopornis\" OR \"Sakesphorus\" OR \"Sciaphylax\" OR \"Sclateria\" OR \"Sipia\" OR \"Taraba\" OR \"Thamnistes\" OR \"Thamnomanes\" OR \"Thamnophilus\" OR \"Willisornis\" OR \"Xenornis\" OR \"Anisognathus\" OR \"Bangsia\" OR \"Buthraupis\" OR \"Calochaetes\" OR \"Catamblyrhynchus\" OR \"Catamenia\" OR \"Charitospiza\" OR \"Chlorochrysa\" OR \"Chlorophanes\" OR \"Chlorornis\" OR \"Chrysothlypis\" OR \"Cissopis\" OR \"Cnemoscopus\" OR \"Coereba\" OR \"Compsospiza\" OR \"Compsothraupis\" OR \"Conirostrum\" OR \"Conothraupis\" OR \"Coryphospingus\" OR \"Creurgops\" OR \"Cyanerpes\" OR \"Cyanicterus\" OR \"Cypsnagra\" OR \"Dacnis\" OR \"Delothraupis\" OR \"Diglossa\" OR \"Diuca\" OR \"Dolospingus\" OR \"Donacospiza\" OR \"Dubusia\" OR \"Emberizoides\" OR \"Embernagra\" OR \"Eucometis\" OR \"Euneornis\" OR \"Geospiza\" OR \"Gubernatrix\" OR \"Haplospiza\" OR \"Hemispingus\" OR \"Hemithraupis\" OR \"Heterospingus\" OR \"Incaspiza\" OR \"Iridophanes\" OR \"Iridosornis\" OR \"Lanio\" OR \"Lophospingus\" OR \"Loxigilla\" OR \"Loxipasser\" OR \"Melanodera\" OR \"Melanospiza\" OR \"Melopyrrha\" OR \"Nemosia\" OR \"Nephelornis\" OR \"Oreomanes\" OR \"Oryzoborus\" OR \"Parkerthraustes\" OR \"Paroaria\" OR \"Phrygilus\" OR \"Piezorina\" OR \"Pipraeidea\" OR \"Poospiza\" OR \"Pyrrhocoma\" OR \"Ramphocelus\" OR \"Rhodospingus\" OR \"Saltator\" OR \"Saltatricula\" OR \"Schistochlamys\" OR \"Sericossypha\" OR \"Sicalis\" OR \"Sporophila\" OR \"Stephanophorus\" OR \"Tachyphonus\" OR \"Tangara\" OR \"Tersina\" OR \"Thlypopsis\" OR \"Thraupis\" OR \"Tiaris\" OR \"Trichothraupis\" OR \"Volatinia\" OR \"Wetmorethraupis\" OR \"Xenodacnis\" OR \"Xenospingus\" OR \"Tichodroma\" OR \"Macronus\" OR \"Pomatorhinus\" OR \"Spelaeornis\" OR \"Stachyridopsis\" OR \"Stachyris\" OR \"Iodopleura\" OR \"Laniisoma\" OR \"Laniocera\" OR \"Myiobius\" OR \"Onychorhynchus\" OR \"Oxyruncus\" OR \"Pachyramphus\" OR \"Schiffornis\" OR \"Terenotriccus\" OR \"Tityra\" OR \"Xenopsaris\" OR \"Campylorhynchus\" OR \"Cantorchilus\" OR \"Catherpes\" OR \"Cinnycerthia\" OR \"Cistothorus\" OR \"Cyphorhinus\" OR \"Henicorhina\" OR \"Microcerculus\" OR \"Odontorchilus\" OR \"Pheugopedius\" OR \"Salpinctes\" OR \"Thryomanes\" OR \"Thryophilus\" OR \"Thryothorus\" OR \"Troglodytes\" OR \"Uropsila\" OR \"Catharus\" OR \"Cichlopsis\" OR \"Entomodestes\" OR \"Geokichla\" OR \"Hylocichla\" OR \"Ixoreus\" OR \"Myadestes\" OR \"Neocossyphus\" OR \"Ridgwayia\" OR \"Sialia\" OR \"Stizorhina\" OR \"Turdus\" OR \"Zoothera\" OR \"Agriornis\" OR \"Alectrurus\" OR \"Anairetes\" OR \"Aphanotriccus\" OR \"Arundinicola\" OR \"Atalotriccus\" OR \"Attila\" OR \"Camptostoma\" OR \"Capsiempis\" OR \"Casiornis\" OR \"Cnemarchus\" OR \"Cnemotriccus\" OR \"Cnipodectes\" OR \"Colonia\" OR \"Colorhamphus\" OR \"Conopias\" OR \"Contopus\" OR \"Corythopis\" OR \"Culicivora\" OR \"Deltarhynchus\" OR \"Elaenia\" OR \"Empidonax\" OR \"Empidonomus\" OR \"Euscarthmus\" OR \"Fluvicola\" OR \"Griseotyrannus\" OR \"Gubernetes\" OR \"Hemitriccus\" OR \"Heteroxolmis\" OR \"Hirundinea\" OR \"Hymenops\" OR \"Inezia\" OR \"Knipolegus\" OR \"Lathrotriccus\" OR \"Legatus\" OR \"Leptopogon\" OR \"Lessonia\" OR \"Lophotriccus\" OR \"Machetornis\" OR \"Mecocerculus\" OR \"Megarynchus\" OR \"Mionectes\" OR \"Mitrephanes\" OR \"Muscigralla\" OR \"Muscisaxicola\" OR \"Myiarchus\" OR \"Myiodynastes\" OR \"Myiopagis\" OR \"Myiophobus\" OR \"Myiornis\" OR \"Myiotheretes\" OR \"Myiotriccus\" OR \"Myiozetetes\" OR \"Neopipo\" OR \"Neoxolmis\" OR \"Nephelomyias\" OR \"Ochthoeca\" OR \"Ochthornis\" OR \"Oncostoma\" OR \"Ornithion\" OR \"Phaeomyias\" OR \"Philohydor\" OR \"Phyllomyias\" OR \"Phylloscartes\" OR \"Piprites\" OR \"Pitangus\" OR \"Platyrinchus\" OR \"Poecilotriccus\" OR \"Pogonotriccus\" OR \"Polioxolmis\" OR \"Polystictus\" OR \"Pseudelaenia\" OR \"Pseudocolopteryx\" OR \"Pseudotriccus\" OR \"Pyrocephalus\" OR \"Pyrrhomyias\" OR \"Ramphotrigon\" OR \"Rhynchocyclus\" OR \"Rhytipterna\" OR \"Satrapa\" OR \"Sayornis\" OR \"Serpophaga\" OR \"Silvicultrix\" OR \"Sirystes\" OR \"Stigmatura\" OR \"Sublegatus\" OR \"Suiriri\" OR \"Tachuris\" OR \"Taeniotriccus\" OR \"Todirostrum\" OR \"Tolmomyias\" OR \"Tumbezia\" OR \"Tyrannopsis\" OR \"Tyrannulus\" OR \"Tyrannus\" OR \"Uromyias\" OR \"Xenotriccus\" OR \"Xolmis\" OR \"Zimmerius\" OR \"Urocynchramus\" OR \"Artamella\" OR \"Calicalicus\" OR \"Cyanolanius\" OR \"Euryceros\" OR \"Falculea\" OR \"Hypositta\" OR \"Leptopterus\" OR \"Mystacornis\" OR \"Newtonia\" OR \"Oriolia\" OR \"Philentoma\" OR \"Prionops\" OR \"Pseudobias\" OR \"Schetba\" OR \"Tephrodornis\" OR \"Tylas\" OR \"Vanga\" OR \"Xenopirostris\" OR \"Anomalospiza\" OR \"Vidua\" OR \"Cyclarhis\" OR \"Erpornis\" OR \"Hylophilus\" OR \"Pteruthius\" OR \"Vireo\" OR \"Vireolanius\" OR \"Zeledonia\" OR \"Apalopteron\" OR \"Dasycrotapha\" OR \"Heleia\" OR \"Lophozosterops\" OR \"Sterrhoptilus\" OR \"Yuhina\" OR \"Zosterops\" OR \"Zosterornis\" OR \"Agamia\" OR \"Ardea\" OR \"Ardeola\" OR \"Botaurus\" OR \"Bubulcus\" OR \"Butorides\" OR \"Cochlearius\" OR \"Dupetor\" OR \"Egretta\" OR \"Gorsachius\" OR \"Ixobrychus\" OR \"Nyctanassa\" OR \"Nycticorax\" OR \"Pilherodius\" OR \"Syrigma\" OR \"Tigriornis\" OR \"Tigrisoma\" OR \"Zebrilus\" OR \"Balaeniceps\" OR \"Pelecanus\" OR \"Scopus\" OR \"Bostrychia\" OR \"Eudocimus\" OR \"Geronticus\" OR \"Lophotibis\" OR \"Mesembrinibis\" OR \"Nipponia\" OR \"Phimosus\" OR \"Platalea\" OR \"Plegadis\" OR \"Pseudibis\" OR \"Theristicus\" OR \"Threskiornis\" OR \"Phaethon\" OR \"Phoeniconaias\" OR \"Phoenicoparrus\" OR \"Phoenicopterus\" OR \"Bucco\" OR \"Chelidoptera\" OR \"Hapaloptila\" OR \"Hypnelus\" OR \"Malacoptila\" OR \"Micromonacha\" OR \"Monasa\" OR \"Nonnula\" OR \"Notharchus\" OR \"Nystalus\" OR \"Capito\" OR \"Eubucco\" OR \"Brachygalba\" OR \"Galbalcyrhynchus\" OR \"Galbula\" OR \"Jacamaralcyon\" OR \"Jacamerops\" OR \"Indicator\" OR \"Melichneutes\" OR \"Melignomon\" OR \"Prodotiscus\" OR \"Buccanodon\" OR \"Gymnobucco\" OR \"Lybius\" OR \"Pogoniulus\" OR \"Stactolaema\" OR \"Trachyphonus\" OR \"Psilopogon\" OR \"Blythipicus\" OR \"Campephilus\" OR \"Campethera\" OR \"Celeus\" OR \"Chloropicus\" OR \"Chrysocolaptes\" OR \"Chrysophlegma\" OR \"Colaptes\" OR \"Dendrocopos\" OR \"Dendrocoptes\" OR \"Dendropicos\" OR \"Dinopium\" OR \"Dryobates\" OR \"Dryocopus\" OR \"Gecinulus\" OR \"Geocolaptes\" OR \"Jynx\" OR \"Leiopicus\" OR \"Leuconotopicus\" OR \"Meiglyptes\" OR \"Melanerpes\" OR \"Micropternus\" OR \"Mulleripicus\" OR \"Nesoctites\" OR \"Picoides\" OR \"Piculus\" OR \"Picumnus\" OR \"Picus\" OR \"Reinwardtipicus\" OR \"Sasia\" OR \"Sphyrapicus\" OR \"Veniliornis\" OR \"Yungipicus\" OR \"Andigena\" OR \"Aulacorhynchus\" OR \"Pteroglossus\" OR \"Ramphastos\" OR \"Selenidera\" OR \"Semnornis\" OR \"Aechmophorus\" OR \"Podiceps\" OR \"Podilymbus\" OR \"Poliocephalus\" OR \"Rollandia\" OR \"Tachybaptus\" OR \"Diomedea\" OR \"Phoebastria\" OR \"Phoebetria\" OR \"Thalassarche\" OR \"Hydrobates\" OR \"Oceanodroma\" OR \"Fregetta\" OR \"Garrodia\" OR \"Nesofregetta\" OR \"Oceanites\" OR \"Pelagodroma\" OR \"Aphrodroma\" OR \"Ardenna\" OR \"Bulweria\" OR \"Calonectris\" OR \"Daption\" OR \"Fulmarus\" OR \"Halobaena\" OR \"Macronectes\" OR \"Pachyptila\" OR \"Pagodroma\" OR \"Pelecanoides\" OR \"Procellaria\" OR \"Pseudobulweria\" OR \"Pterodroma\" OR \"Puffinus\" OR \"Thalassoica\" OR \"Cacatua\" OR \"Callocephalon\" OR \"Calyptorhynchus\" OR \"Eolophus\" OR \"Lophochroa\" OR \"Nymphicus\" OR \"Probosciger\" OR \"Alipiopsitta\" OR \"Amazona\" OR \"Anodorhynchus\" OR \"Ara\" OR \"Aratinga\" OR \"Bolborhynchus\" OR \"Brotogeris\" OR \"Conuropsis\" OR \"Cyanoliseus\" OR \"Cyanopsitta\" OR \"Deroptyus\" OR \"Diopsittaca\" OR \"Enicognathus\" OR \"Eupsittula\" OR \"Forpus\" OR \"Graydidascalus\" OR \"Guarouba\" OR \"Guaruba\" OR \"Hapalopsittaca\" OR \"Leptosittaca\" OR \"Myiopsitta\" OR \"Nannopsittaca\" OR \"Orthopsittaca\" OR \"Pionites\" OR \"Pionopsitta\" OR \"Pionus\" OR \"Poicephalus\" OR \"Primolius\" OR \"Psilopsiagon\" OR \"Psittacara\" OR \"Psittacus\" OR \"Pyrilia\" OR \"Pyrrhura\" OR \"Rhynchopsitta\" OR \"Thectocercus\" OR \"Touit\" OR \"Triclaria\" OR \"Agapornis\" OR \"Alisterus\" OR \"Aprosmictus\" OR \"Barnardius\" OR \"Bolbopsittacus\" OR \"Chalcopsitta\" OR \"Charmosyna\" OR \"Coracopsis\" OR \"Cyanoramphus\" OR \"Cyclopsitta\" OR \"Eclectus\" OR \"Eos\" OR \"Eunymphicus\" OR \"Geoffroyus\" OR \"Glossopsitta\" OR \"Lathamus\" OR \"Loriculus\" OR \"Lorius\" OR \"Melopsittacus\" OR \"Micropsitta\" OR \"Neophema\" OR \"Neopsephotus\" OR \"Neopsittacus\" OR \"Northiella\" OR \"Oreopsittacus\" OR \"Parvipsitta\" OR \"Pezoporus\" OR \"Phigys\" OR \"Platycercus\" OR \"Polytelis\" OR \"Prioniturus\" OR \"Prosopeia\" OR \"Psephotellus\" OR \"Psephotus\" OR \"Pseudeos\" OR \"Psittacella\" OR \"Psittacula\" OR \"Psittaculirostris\" OR \"Psitteuteles\" OR \"Psittinus\" OR \"Psittrichas\" OR \"Purpureicephalus\" OR \"Tanygnathus\" OR \"Trichoglossus\" OR \"Vini\" OR \"Nestor\" OR \"Strigops\" OR \"Pterocles\" OR \"Syrrhaptes\" OR \"Rhea\" OR \"Aptenodytes\" OR \"Eudyptes\" OR \"Eudyptula\" OR \"Megadyptes\" OR \"Pygoscelis\" OR \"Spheniscus\" OR \"Aegolius\" OR \"Asio\" OR \"Athene\" OR \"Bubo\" OR \"Glaucidium\" OR \"Ketupa\" OR \"Lophostrix\" OR \"Megascops\" OR \"Micrathene\" OR \"Ninox\" OR \"Otus\" OR \"Pseudoscops\" OR \"Psiloscops\" OR \"Pulsatrix\" OR \"Sceloglaux\" OR \"Scotopelia\" OR \"Strix\" OR \"Surnia\" OR \"Xenoglaux\" OR \"Phodilus\" OR \"Tyto\" OR \"Aepyornis\" OR \"Mullerornis\" OR \"Struthio\" OR \"Anhinga\" OR \"Fregata\" OR \"Leucocarbo\" OR \"Microcarbo\" OR \"Nannopterum\" OR \"Phalacrocorax\" OR \"Morus\" OR \"Sula\" OR \"Crypturellus\" OR \"Eudromia\" OR \"Nothocercus\" OR \"Nothoprocta\" OR \"Nothura\" OR \"Rhynchotus\" OR \"Tinamotis\" OR \"Tinamus\" OR \"Apalharpactes\" OR \"Apaloderma\" OR \"Harpactes\" OR \"Pharomachrus\" OR \"Trogon\" OR \"Tetrastes\" OR \"Hesperiphona\") AND (\"experiment\\*\" OR \"manipulat\\*\") )) OR AK= (((\"green\\*\" OR \"herb\\*\" OR \"aromatic\\*\") AND \"nest\\*\" AND (\"bird\\*\" OR \"aves\" OR \"avian\" OR \"ornithol\\*\" OR \"passerine\\*\" OR \"passeriform\\*\" OR \"songbird\\*\" OR \"Accipiter\" OR \"Aegypius\" OR \"Aquila\" OR \"Aviceda\" OR \"Busarellus\" OR \"Butastur\" OR \"Buteo\" OR \"Buteogallus\" OR \"Chondrohierax\" OR \"Circaetus\" OR \"Circus\" OR \"Clanga\" OR \"Elanoides\" OR \"Elanus\" OR \"Gampsonyx\" OR \"Geranoaetus\" OR \"Geranospiza\" OR \"Gypaetus\" OR \"Gypohierax\" OR \"Gyps\" OR \"Haliaeetus\" OR \"Haliastur\" OR \"Harpagus\" OR \"Harpia\" OR \"Hieraaetus\" OR \"Ictinaetus\" OR \"Ictinia\" OR \"Kaupifalco\" OR \"Leptodon\" OR \"Leucopternis\" OR \"Lophotriorchis\" OR \"Milvus\" OR \"Morphnarchus\" OR \"Morphnus\" OR \"Necrosyrtes\" OR \"Neophron\" OR \"Nisaetus\" OR \"Parabuteo\" OR \"Pernis\" OR \"Pithecophaga\" OR \"Polemaetus\" OR \"Pseudastur\" OR \"Rostrhamus\" OR \"Rupornis\" OR \"Sarcogyps\" OR \"Spilornis\" OR \"Spizaetus\" OR \"Stephanoaetus\" OR \"Terathopius\" OR \"Torgos\" OR \"Trigonoceps\" OR \"Cathartes\" OR \"Coragyps\" OR \"Gymnogyps\" OR \"Sarcoramphus\" OR \"Vultur\" OR \"Pandion\" OR \"Sagittarius\" OR \"Aix\" OR \"Alopochen\" OR \"Amazonetta\" OR \"Anas\" OR \"Anser\" OR \"Asarcornis\" OR \"Aythya\" OR \"Branta\" OR \"Bucephala\" OR \"Cairina\" OR \"Callonetta\" OR \"Cereopsis\" OR \"Chen\" OR \"Chenonetta\" OR \"Chloephaga\" OR \"Clangula\" OR \"Coscoroba\" OR \"Cyanochen\" OR \"Cygnus\" OR \"Dendrocygna\" OR \"Heteronetta\" OR \"Histrionicus\" OR \"Hymenolaimus\" OR \"Lophodytes\" OR \"Lophonetta\" OR \"Malacorhynchus\" OR \"Mareca\" OR \"Marmaronetta\" OR \"Melanitta\" OR \"Merganetta\" OR \"Mergellus\" OR \"Mergus\" OR \"Neochen\" OR \"Netta\" OR \"Nettapus\" OR \"Nomonyx\" OR \"Oxyura\" OR \"Plectropterus\" OR \"Polysticta\" OR \"Pteronetta\" OR \"Sarkidiornis\" OR \"Sibirionetta\" OR \"Somateria\" OR \"Spatula\" OR \"Tachyeres\" OR \"Tadorna\" OR \"Thalassornis\" OR \"Anhima\" OR \"Chauna\" OR \"Anseranas\" OR \"Aegotheles\" OR \"Aerodramus\" OR \"Aeronautes\" OR \"Apus\" OR \"Chaetura\" OR \"Collocalia\" OR \"Cypseloides\" OR \"Cypsiurus\" OR \"Hirundapus\" OR \"Panyptila\" OR \"Streptoprocne\" OR \"Tachornis\" OR \"Tachymarptis\" OR \"Hemiprocne\" OR \"Abeillia\" OR \"Adelomyia\" OR \"Aglaeactis\" OR \"Aglaiocercus\" OR \"Amazilia\" OR \"Androdon\" OR \"Anopetia\" OR \"Anthocephala\" OR \"Anthracothorax\" OR \"Archilochus\" OR \"Atthis\" OR \"Augastes\" OR \"Avocettula\" OR \"Basilinna\" OR \"Boissonneaua\" OR \"Calliphlox\" OR \"Calypte\" OR \"Campylopterus\" OR \"Chaetocercus\" OR \"Chalcostigma\" OR \"Chalybura\" OR \"Chlorestes\" OR \"Chlorostilbon\" OR \"Chrysolampis\" OR \"Chrysuronia\" OR \"Clytolaema\" OR \"Coeligena\" OR \"Colibri\" OR \"Cyanophaia\" OR \"Cynanthus\" OR \"Discosura\" OR \"Doricha\" OR \"Doryfera\" OR \"Elvira\" OR \"Ensifera\" OR \"Eriocnemis\" OR \"Eugenes\" OR \"Eulampis\" OR \"Eulidia\" OR \"Eupetomena\" OR \"Eupherusa\" OR \"Eutoxeres\" OR \"Florisuga\" OR \"Glaucis\" OR \"Goethalsia\" OR \"Goldmania\" OR \"Haplophaedia\" OR \"Heliactin\" OR \"Heliangelus\" OR \"Heliodoxa\" OR \"Heliomaster\" OR \"Heliothryx\" OR \"Hylocharis\" OR \"Juliamyia\" OR \"Klais\" OR \"Lafresnaya\" OR \"Lampornis\" OR \"Lamprolaima\" OR \"Lepidopyga\" OR \"Lesbia\" OR \"Leucippus\" OR \"Leucochloris\" OR \"Lophornis\" OR \"Mellisuga\" OR \"Metallura\" OR \"Microchera\" OR \"Myrmia\" OR \"Myrtis\" OR \"Ocreatus\" OR \"Opisthoprora\" OR \"Oreonympha\" OR \"Oreotrochilus\" OR \"Orthorhyncus\" OR \"Oxypogon\" OR \"Panterpe\" OR \"Patagona\" OR \"Phaeochroa\" OR \"Phaethornis\" OR \"Phlogophilus\" OR \"Polyonymus\" OR \"Polytmus\" OR \"Pterophanes\" OR \"Ramphodon\" OR \"Ramphomicron\" OR \"Rhodopis\" OR \"Sappho\" OR \"Schistes\" OR \"Selasphorus\" OR \"Sephanoides\" OR \"Stephanoxis\" OR \"Sternoclyta\" OR \"Taphrospilus\" OR \"Thalurania\" OR \"Thaumastura\" OR \"Threnetes\" OR \"Topaza\" OR \"Trochilus\" OR \"Urochroa\" OR \"Urosticte\" OR \"Apteryx\" OR \"Anthracoceros\" OR \"Buceros\" OR \"Bycanistes\" OR \"Lophoceros\" OR \"Penelopides\" OR \"Rhabdotorrhinus\" OR \"Rhyticeros\" OR \"Tockus\" OR \"Bucorvus\" OR \"Phoeniculus\" OR \"Rhinopomastus\" OR \"Upupa\" OR \"Antrostomus\" OR \"Caprimulgus\" OR \"Chordeiles\" OR \"Eleothreptus\" OR \"Eurostopodus\" OR \"Hydropsalis\" OR \"Lurocalis\" OR \"Lyncornis\" OR \"Nyctidromus\" OR \"Nyctiphrynus\" OR \"Nyctipolus\" OR \"Nyctiprogne\" OR \"Phalaenoptilus\" OR \"Setopagis\" OR \"Systellura\" OR \"Uropsalis\" OR \"Nyctibius\" OR \"Batrachostomus\" OR \"Podargus\" OR \"Steatornis\" OR \"Cariama\" OR \"Casuarius\" OR \"Dromaius\" OR \"Aethia\" OR \"Alca\" OR \"Alle\" OR \"Brachyramphus\" OR \"Cepphus\" OR \"Cerorhinca\" OR \"Fratercula\" OR \"Pinguinus\" OR \"Ptychoramphus\" OR \"Synthliboramphus\" OR \"Uria\" OR \"Burhinus\" OR \"Anarhynchus\" OR \"Charadrius\" OR \"Elseyornis\" OR \"Erythrogonys\" OR \"Hoploxypterus\" OR \"Oreopholus\" OR \"Peltohyas\" OR \"Phegornis\" OR \"Pluvialis\" OR \"Thinornis\" OR \"Vanellus\" OR \"Chionis\" OR \"Dromas\" OR \"Cursorius\" OR \"Glareola\" OR \"Rhinoptilus\" OR \"Stiltia\" OR \"Haematopus\" OR \"Actophilornis\" OR \"Hydrophasianus\" OR \"Irediparra\" OR \"Jacana\" OR \"Metopidius\" OR \"Microparra\" OR \"Anous\" OR \"Chlidonias\" OR \"Chroicocephalus\" OR \"Creagrus\" OR \"Gelochelidon\" OR \"Gygis\" OR \"Hydrocoloeus\" OR \"Hydroprogne\" OR \"Ichthyaetus\" OR \"Larosterna\" OR \"Larus\" OR \"Leucophaeus\" OR \"Onychoprion\" OR \"Pagophila\" OR \"Phaetusa\" OR \"Rhodostethia\" OR \"Rissa\" OR \"Rynchops\" OR \"Sterna\" OR \"Sternula\" OR \"Thalasseus\" OR \"Xema\" OR \"Pedionomus\" OR \"Pluvianellus\" OR \"Pluvianus\" OR \"Himantopus\" OR \"Recurvirostra\" OR \"Nycticryphes\" OR \"Rostratula\" OR \"Actitis\" OR \"Arenaria\" OR \"Bartramia\" OR \"Calidris\" OR \"Coenocorypha\" OR \"Gallinago\" OR \"Limnodromus\" OR \"Limosa\" OR \"Lymnocryptes\" OR \"Numenius\" OR \"Phalaropus\" OR \"Scolopax\" OR \"Tringa\" OR \"Xenus\" OR \"Stercorarius\" OR \"Attagis\" OR \"Thinocorus\" OR \"Turnix\" OR \"Ciconia\" OR \"Ephippiorhynchus\" OR \"Jabiru\" OR \"Leptoptilos\" OR \"Mycteria\" OR \"Colius\" OR \"Urocolius\" OR \"Alectroenas\" OR \"Alopecoenas\" OR \"Caloenas\" OR \"Chalcophaps\" OR \"Claravis\" OR \"Columba\" OR \"Columbina\" OR \"Didunculus\" OR \"Drepanoptila\" OR \"Ducula\" OR \"Ectopistes\" OR \"Gallicolumba\" OR \"Geopelia\" OR \"Geophaps\" OR \"Geotrygon\" OR \"Goura\" OR \"Gymnophaps\" OR \"Hemiphaga\" OR \"Henicophaps\" OR \"Leptotila\" OR \"Leptotrygon\" OR \"Leucosarcia\" OR \"Lopholaimus\" OR \"Macropygia\" OR \"Metriopelia\" OR \"Ocyphaps\" OR \"Oena\" OR \"Otidiphaps\" OR \"Patagioenas\" OR \"Petrophassa\" OR \"Pezophaps\" OR \"Phapitreron\" OR \"Phaps\" OR \"Ptilinopus\" OR \"Raphus\" OR \"Reinwardtoena\" OR \"Spilopelia\" OR \"Streptopelia\" OR \"Treron\" OR \"Trugon\" OR \"Turacoena\" OR \"Turtur\" OR \"Uropelia\" OR \"Zenaida\" OR \"Zentrygon\" OR \"Actenoides\" OR \"Alcedo\" OR \"Caridonax\" OR \"Ceryle\" OR \"Ceyx\" OR \"Chloroceryle\" OR \"Cittura\" OR \"Corythornis\" OR \"Dacelo\" OR \"Halcyon\" OR \"Ispidina\" OR \"Lacedo\" OR \"Megaceryle\" OR \"Melidora\" OR \"Syma\" OR \"Tanysiptera\" OR \"Todiramphus\" OR \"Atelornis\" OR \"Brachypteracias\" OR \"Geobiastes\" OR \"Coracias\" OR \"Eurystomus\" OR \"Merops\" OR \"Nyctyornis\" OR \"Baryphthengus\" OR \"Electron\" OR \"Eumomota\" OR \"Hylomanes\" OR \"Momotus\" OR \"Todus\" OR \"Cacomantis\" OR \"Carpococcyx\" OR \"Centropus\" OR \"Cercococcyx\" OR \"Chrysococcyx\" OR \"Clamator\" OR \"Coccycua\" OR \"Coccyzus\" OR \"Coua\" OR \"Crotophaga\" OR \"Cuculus\" OR \"Dasylophus\" OR \"Dromococcyx\" OR \"Eudynamys\" OR \"Geococcyx\" OR \"Guira\" OR \"Hierococcyx\" OR \"Morococcyx\" OR \"Neomorphus\" OR \"Pachycoccyx\" OR \"Phaenicophaeus\" OR \"Piaya\" OR \"Rhinortha\" OR \"Scythrops\" OR \"Surniculus\" OR \"Tapera\" OR \"Urodynamis\" OR \"Zanclostomus\" OR \"Dinornis\" OR \"Anomalopteryx\" OR \"Emeus\" OR \"Euryapteryx\" OR \"Eurypyga\" OR \"Rhynochetos\" OR \"Caracara\" OR \"Daptrius\" OR \"Falco\" OR \"Herpetotheres\" OR \"Ibycter\" OR \"Micrastur\" OR \"Microhierax\" OR \"Milvago\" OR \"Phalcoboenus\" OR \"Polihierax\" OR \"Spiziapteryx\" OR \"Aburria\" OR \"Chamaepetes\" OR \"Crax\" OR \"Mitu\" OR \"Nothocrax\" OR \"Oreophasis\" OR \"Ortalis\" OR \"Pauxi\" OR \"Penelope\" OR \"Penelopina\" OR \"Pipile\" OR \"Alectura\" OR \"Megapodius\" OR \"Acryllium\" OR \"Guttera\" OR \"Numida\" OR \"Callipepla\" OR \"Colinus\" OR \"Cyrtonyx\" OR \"Dendrortyx\" OR \"Odontophorus\" OR \"Oreortyx\" OR \"Philortyx\" OR \"Ptilopachus\" OR \"Rhynchortyx\" OR \"Alectoris\" OR \"Ammoperdix\" OR \"Arborophila\" OR \"Argusianus\" OR \"Bambusicola\" OR \"Bonasa\" OR \"Caloperdix\" OR \"Centrocercus\" OR \"Chrysolophus\" OR \"Coturnix\" OR \"Crossoptilon\" OR \"Dendragapus\" OR \"Excalfactoria\" OR \"Falcipennis\" OR \"Francolinus\" OR \"Gallus\" OR \"Haematortyx\" OR \"Ithaginis\" OR \"Lagopus\" OR \"Lerwa\" OR \"Lophophorus\" OR \"Lophura\" OR \"Lyrurus\" OR \"Meleagris\" OR \"Pavo\" OR \"Peliperdix\" OR \"Perdix\" OR \"Phasianus\" OR \"Polyplectron\" OR \"Pternistis\" OR \"Pucrasia\" OR \"Rhizothera\" OR \"Rollulus\" OR \"Scleroptila\" OR \"Syrmaticus\" OR \"Tetrao\" OR \"Tetraogallus\" OR \"Tetraophasis\" OR \"Tragopan\" OR \"Tympanuchus\" OR \"Gavia\" OR \"Aramus\" OR \"Anthropoides\" OR \"Antigone\" OR \"Balearica\" OR \"Bugeranus\" OR \"Grus\" OR \"Leucogeranus\" OR \"Heliornis\" OR \"Psophia\" OR \"Aenigmatolimnas\" OR \"Amaurolimnas\" OR \"Amaurornis\" OR \"Anurolimnas\" OR \"Aramides\" OR \"Atlantisia\" OR \"Coturnicops\" OR \"Crex\" OR \"Dryolimnas\" OR \"Eulabeornis\" OR \"Fulica\" OR \"Gallicrex\" OR \"Gallinula\" OR \"Gallirallus\" OR \"Laterallus\" OR \"Lewinia\" OR \"Micropygia\" OR \"Neocrex\" OR \"Nesoclopeus\" OR \"Paragallinula\" OR \"Pardirallus\" OR \"Porphyrio\" OR \"Porphyriops\" OR \"Porzana\" OR \"Rallicula\" OR \"Rallina\" OR \"Rallus\" OR \"Tribonyx\" OR \"Canirallus\" OR \"Sarothrura\" OR \"Leptosomus\" OR \"Corythaeola\" OR \"Corythaixoides\" OR \"Crinifer\" OR \"Musophaga\" OR \"Tauraco\" OR \"Opisthocomus\" OR \"Afrotis\" OR \"Ardeotis\" OR \"Chlamydotis\" OR \"Neotis\" OR \"Otis\" OR \"Tetrax\" OR \"Acanthisitta\" OR \"Pachyplichas\" OR \"Traversia\" OR \"Xenicus\" OR \"Acanthiza\" OR \"Acanthornis\" OR \"Aethomyias\" OR \"Aphelocephala\" OR \"Calamanthus\" OR \"Gerygone\" OR \"Hylacola\" OR \"Neosericornis\" OR \"Oreoscopus\" OR \"Origma\" OR \"Pachycare\" OR \"Pycnoptilus\" OR \"Pyrrholaemus\" OR \"Sericornis\" OR \"Smicrornis\" OR \"Acrocephalus\" OR \"Arundinax\" OR \"Calamonastides\" OR \"Hippolais\" OR \"Iduna\" OR \"Nesillas\" OR \"Aegithalos\" OR \"Leptopoecile\" OR \"Psaltriparus\" OR \"Aegithina\" OR \"Alaemon\" OR \"Alauda\" OR \"Alaudala\" OR \"Ammomanes\" OR \"Calandrella\" OR \"Calendulauda\" OR \"Chersomanes\" OR \"Eremophila\" OR \"Eremopterix\" OR \"Galerida\" OR \"Lullula\" OR \"Melanocorypha\" OR \"Mirafra\" OR \"Pinarocorys\" OR \"Spizocorys\" OR \"Artamus\" OR \"Gymnorhina\" OR \"Melloria\" OR \"Bombycilla\" OR \"Buphagus\" OR \"Calcarius\" OR \"Plectrophenax\" OR \"Rhynchophanes\" OR \"Callaeas\" OR \"Heteralocha\" OR \"Philesturnus\" OR \"Calyptophilus\" OR \"Campephaga\" OR \"Ceblepyris\" OR \"Coracina\" OR \"Edolisoma\" OR \"Lalage\" OR \"Malindangia\" OR \"Pericrocotus\" OR \"Amaurospiza\" OR \"Cardinalis\" OR \"Caryothraustes\" OR \"Chlorothraupis\" OR \"Cyanocompsa\" OR \"Cyanoloxia\" OR \"Granatellus\" OR \"Habia\" OR \"Passerina\" OR \"Periporphyrus\" OR \"Pheucticus\" OR \"Piranga\" OR \"Spiza\" OR \"Certhia\" OR \"Salpornis\" OR \"Abroscopus\" OR \"Cettia\" OR \"Horornis\" OR \"Phyllergates\" OR \"Tesia\" OR \"Urosphena\" OR \"Chloropsis\" OR \"Cinclus\" OR \"Apalis\" OR \"Artisornis\" OR \"Camaroptera\" OR \"Cisticola\" OR \"Eremomela\" OR \"Heliolais\" OR \"Hypergerus\" OR \"Neomixis\" OR \"Oreolais\" OR \"Orthotomus\" OR \"Phragmacia\" OR \"Poliolais\" OR \"Prinia\" OR \"Schistolais\" OR \"Urolais\" OR \"Urorhipis\" OR \"Climacteris\" OR \"Cormobates\" OR \"Conopophaga\" OR \"Struthidea\" OR \"Aphelocoma\" OR \"Calocitta\" OR \"Cissa\" OR \"Coloeus\" OR \"Corvus\" OR \"Cyanocitta\" OR \"Cyanocorax\" OR \"Cyanolyca\" OR \"Cyanopica\" OR \"Dendrocitta\" OR \"Garrulus\" OR \"Gymnorhinus\" OR \"Nucifraga\" OR \"Perisoreus\" OR \"Pica\" OR \"Platylophus\" OR \"Podoces\" OR \"Psilorhinus\" OR \"Ptilostomus\" OR \"Pyrrhocorax\" OR \"Urocissa\" OR \"Ampelioides\" OR \"Ampelion\" OR \"Carpornis\" OR \"Cephalopterus\" OR \"Conioptilon\" OR \"Cotinga\" OR \"Doliornis\" OR \"Gymnoderus\" OR \"Haematoderus\" OR \"Lipaugus\" OR \"Perissocephalus\" OR \"Phoenicircus\" OR \"Phytotoma\" OR \"Pipreola\" OR \"Porphyrolaema\" OR \"Procnias\" OR \"Pyroderus\" OR \"Querula\" OR \"Rupicola\" OR \"Snowornis\" OR \"Xipholena\" OR \"Zaratornis\" OR \"Dasyornis\" OR \"Dicaeum\" OR \"Prionochilus\" OR \"Dicrurus\" OR \"Donacobius\" OR \"Dulus\" OR \"Emberiza\" OR \"Amadina\" OR \"Amandava\" OR \"Cryptospiza\" OR \"Erythrura\" OR \"Estrilda\" OR \"Euodice\" OR \"Euschistospiza\" OR \"Lagonosticta\" OR \"Lonchura\" OR \"Mandingoa\" OR \"Neochmia\" OR \"Nesocharis\" OR \"Nigrita\" OR \"Ortygospiza\" OR \"Parmoptila\" OR \"Pyrenestes\" OR \"Pytilia\" OR \"Spermophaga\" OR \"Stagonopleura\" OR \"Taeniopygia\" OR \"Uraeginthus\" OR \"Calyptomena\" OR \"Cymbirhynchus\" OR \"Eurylaimus\" OR \"Psarisomus\" OR \"Serilophus\" OR \"Smithornis\" OR \"Chamaeza\" OR \"Formicarius\" OR \"Acanthis\" OR \"Agraphospiza\" OR \"Akialoa\" OR \"Bucanetes\" OR \"Carduelis\" OR \"Carpodacus\" OR \"Chloris\" OR \"Chlorodrepanis\" OR \"Chlorophonia\" OR \"Chrysocorythus\" OR \"Coccothraustes\" OR \"Crithagra\" OR \"Drepanis\" OR \"Eophona\" OR \"Euphonia\" OR \"Fringilla\" OR \"Haemorhous\" OR \"Hemignathus\" OR \"Himatione\" OR \"Leucosticte\" OR \"Linaria\" OR \"Linurgus\" OR \"Loxia\" OR \"Loxioides\" OR \"Loxops\" OR \"Magumma\" OR \"Melamprosops\" OR \"Oreomystis\" OR \"Paroreomyza\" OR \"Pinicola\" OR \"Procarduelis\" OR \"Pseudonestor\" OR \"Psittirostra\" OR \"Pyrrhoplectes\" OR \"Pyrrhula\" OR \"Rhodopechys\" OR \"Rhodospiza\" OR \"Serinus\" OR \"Spinus\" OR \"Telespiza\" OR \"Anabacerthia\" OR \"Anabazenops\" OR \"Ancistrops\" OR \"Anumbius\" OR \"Aphrastura\" OR \"Asthenes\" OR \"Automolus\" OR \"Berlepschia\" OR \"Campylorhamphus\" OR \"Certhiasomus\" OR \"Certhiaxis\" OR \"Cinclodes\" OR \"Clibanornis\" OR \"Coryphistera\" OR \"Cranioleuca\" OR \"Deconychura\" OR \"Dendrexetastes\" OR \"Dendrocincla\" OR \"Dendrocolaptes\" OR \"Dendroplex\" OR \"Drymornis\" OR \"Drymotoxeres\" OR \"Furnarius\" OR \"Geocerthia\" OR \"Geositta\" OR \"Glyphorynchus\" OR \"Heliobletus\" OR \"Hellmayrea\" OR \"Hylexetastes\" OR \"Lepidocolaptes\" OR \"Leptasthenura\" OR \"Limnoctites\" OR \"Limnornis\" OR \"Lochmias\" OR \"Margarornis\" OR \"Mazaria\" OR \"Megaxenops\" OR \"Metopothrix\" OR \"Microxenops\" OR \"Nasica\" OR \"Ochetorhynchus\" OR \"Phacellodomus\" OR \"Philydor\" OR \"Phleocryptes\" OR \"Premnoplex\" OR \"Premnornis\" OR \"Pseudasthenes\" OR \"Pseudocolaptes\" OR \"Pseudoseisura\" OR \"Pygarrhichas\" OR \"Roraimia\" OR \"Schoeniophylax\" OR \"Sclerurus\" OR \"Sittasomus\" OR \"Spartonoica\" OR \"Sylviorthorhynchus\" OR \"Synallaxis\" OR \"Syndactyla\" OR \"Tarphonomus\" OR \"Thripadectes\" OR \"Thripophaga\" OR \"Upucerthia\" OR \"Xenerpestes\" OR \"Xenops\" OR \"Xiphocolaptes\" OR \"Xiphorhynchus\" OR \"Grallaria\" OR \"Grallaricula\" OR \"Hylopezus\" OR \"Myrmothera\" OR \"Alopochelidon\" OR \"Atticora\" OR \"Cecropis\" OR \"Delichon\" OR \"Haplochelidon\" OR \"Hirundo\" OR \"Neochelidon\" OR \"Notiochelidon\" OR \"Orochelidon\" OR \"Petrochelidon\" OR \"Phedina\" OR \"Progne\" OR \"Psalidoprocne\" OR \"Pseudhirundo\" OR \"Pseudochelidon\" OR \"Ptyonoprogne\" OR \"Riparia\" OR \"Stelgidopteryx\" OR \"Tachycineta\" OR \"Hyliota\" OR \"Hypocolius\" OR \"Agelaioides\" OR \"Agelaius\" OR \"Agelasticus\" OR \"Amblycercus\" OR \"Amblyramphus\" OR \"Anumara\" OR \"Cacicus\" OR \"Chrysomus\" OR \"Curaeus\" OR \"Dives\" OR \"Dolichonyx\" OR \"Euphagus\" OR \"Gnorimopsar\" OR \"Gymnomystax\" OR \"Hypopyrrhus\" OR \"Icterus\" OR \"Lampropsar\" OR \"Leistes\" OR \"Macroagelaius\" OR \"Molothrus\" OR \"Nesopsar\" OR \"Oreopsar\" OR \"Psarocolius\" OR \"Pseudoleistes\" OR \"Quiscalus\" OR \"Sturnella\" OR \"Xanthocephalus\" OR \"Xanthopsar\" OR \"Icteria\" OR \"Ifrita\" OR \"Irena\" OR \"Corvinella\" OR \"Eurocephalus\" OR \"Lanius\" OR \"Actinodura\" OR \"Argya\" OR \"Garrulax\" OR \"Grammatoptila\" OR \"Heterophasia\" OR \"Ianthocincla\" OR \"Laniellus\" OR \"Leiothrix\" OR \"Liocichla\" OR \"Minla\" OR \"Pterorhinus\" OR \"Trochalopteron\" OR \"Turdoides\" OR \"Bradypterus\" OR \"Cincloramphus\" OR \"Helopsaltes\" OR \"Locustella\" OR \"Megalurus\" OR \"Poodytes\" OR \"Machaerirhynchus\" OR \"Graueria\" OR \"Hylia\" OR \"Macrosphenus\" OR \"Melocichla\" OR \"Sylvietta\" OR \"Chlorophoneus\" OR \"Dryoscopus\" OR \"Laniarius\" OR \"Malaconotus\" OR \"Nilaus\" OR \"Rhodophoneus\" OR \"Tchagra\" OR \"Telophorus\" OR \"Amytornis\" OR \"Chenorhamphus\" OR \"Clytomyias\" OR \"Malurus\" OR \"Stipiturus\" OR \"Melampitta\" OR \"Melanocharis\" OR \"Oedistoma\" OR \"Toxorhamphus\" OR \"Melanopareia\" OR \"Acanthagenys\" OR \"Acanthorhynchus\" OR \"Anthochaera\" OR \"Anthornis\" OR \"Caligavis\" OR \"Entomyzon\" OR \"Epthianura\" OR \"Glycifohia\" OR \"Gymnomyza\" OR \"Lichmera\" OR \"Manorina\" OR \"Melidectes\" OR \"Melilestes\" OR \"Meliphaga\" OR \"Melipotes\" OR \"Melithreptus\" OR \"Myzomela\" OR \"Nesoptilotis\" OR \"Philemon\" OR \"Phylidonyris\" OR \"Prosthemadera\" OR \"Ptiloprora\" OR \"Ptilotula\" OR \"Pycnopygius\" OR \"Timeliopsis\" OR \"Xanthotis\" OR \"Menura\" OR \"Allenia\" OR \"Cinclocerthia\" OR \"Dumetella\" OR \"Margarops\" OR \"Melanoptila\" OR \"Melanotis\" OR \"Mimus\" OR \"Oreoscoptes\" OR \"Ramphocinclus\" OR \"Toxostoma\" OR \"Lamprospiza\" OR \"Mitrospingus\" OR \"Moho\" OR \"Mohoua\" OR \"Arses\" OR \"Carterornis\" OR \"Clytorhynchus\" OR \"Grallina\" OR \"Hypothymis\" OR \"Monarcha\" OR \"Myiagra\" OR \"Symposiachrus\" OR \"Terpsiphone\" OR \"Trochocercus\" OR \"Anthus\" OR \"Macronyx\" OR \"Motacilla\" OR \"Alethe\" OR \"Anthipes\" OR \"Brachypteryx\" OR \"Calliope\" OR \"Campicoloides\" OR \"Cercotrichas\" OR \"Chamaetylas\" OR \"Copsychus\" OR \"Cossypha\" OR \"Cyanoptila\" OR \"Cyornis\" OR \"Enicurus\" OR \"Erithacus\" OR \"Eumyias\" OR \"Ficedula\" OR \"Fraseria\" OR \"Irania\" OR \"Larvivora\" OR \"Leonardina\" OR \"Luscinia\" OR \"Melaenornis\" OR \"Monticola\" OR \"Muscicapa\" OR \"Myiomela\" OR \"Myioparus\" OR \"Myophonus\" OR \"Myrmecocichla\" OR \"Niltava\" OR \"Oenanthe\" OR \"Phoenicurus\" OR \"Pogonocichla\" OR \"Saxicola\" OR \"Sheppardia\" OR \"Sholicola\" OR \"Stiphrornis\" OR \"Tarsiger\" OR \"Thamnolaea\" OR \"Vauriella\" OR \"Aethopyga\" OR \"Anabathmis\" OR \"Anthreptes\" OR \"Arachnothera\" OR \"Chalcomitra\" OR \"Cinnyris\" OR \"Cyanomitra\" OR \"Deleornis\" OR \"Hedydipna\" OR \"Kurochkinegramma\" OR \"Leptocoma\" OR \"Nectarinia\" OR \"Daphoenositta\" OR \"Nesospingus\" OR \"Nicator\" OR \"Notiomystis\" OR \"Aleadryas\" OR \"Oriolus\" OR \"Pitohui\" OR \"Sphecotheres\" OR \"Turnagra\" OR \"Colluricincla\" OR \"Falcunculus\" OR \"Melanorectes\" OR \"Pachycephala\" OR \"Pseudorectes\" OR \"Panurus\" OR \"Cicinnurus\" OR \"Diphyllodes\" OR \"Manucodia\" OR \"Paradisaea\" OR \"Ptiloris\" OR \"Paramythia\" OR \"Pardalotus\" OR \"Baeolophus\" OR \"Cephalopyrus\" OR \"Cyanistes\" OR \"Lophophanes\" OR \"Machlolophus\" OR \"Melaniparus\" OR \"Melanochlora\" OR \"Pardaliparus\" OR \"Parus\" OR \"Periparus\" OR \"Poecile\" OR \"Pseudopodoces\" OR \"Sittiparus\" OR \"Sylviparus\" OR \"Basileuterus\" OR \"Cardellina\" OR \"Catharopeza\" OR \"Dendroica\" OR \"Geothlypis\" OR \"Helmitheros\" OR \"Leiothlypis\" OR \"Limnothlypis\" OR \"Mniotilta\" OR \"Myioborus\" OR \"Myiothlypis\" OR \"Oporornis\" OR \"Oreothlypis\" OR \"Parkesia\" OR \"Protonotaria\" OR \"Seiurus\" OR \"Setophaga\" OR \"Vermivora\" OR \"Aimophila\" OR \"Ammodramus\" OR \"Amphispiza\" OR \"Arremon\" OR \"Arremonops\" OR \"Artemisiospiza\" OR \"Atlapetes\" OR \"Calamospiza\" OR \"Chlorospingus\" OR \"Chondestes\" OR \"Junco\" OR \"Melospiza\" OR \"Melozone\" OR \"Oreothraupis\" OR \"Oriturus\" OR \"Passerculus\" OR \"Passerella\" OR \"Peucaea\" OR \"Pezopetes\" OR \"Pipilo\" OR \"Pooecetes\" OR \"Pselliophorus\" OR \"Rhynchospiza\" OR \"Spizella\" OR \"Spizelloides\" OR \"Xenospiza\" OR \"Zonotrichia\" OR \"Carpospiza\" OR \"Gymnoris\" OR \"Hypocryptadius\" OR \"Montifringilla\" OR \"Onychostruthus\" OR \"Passer\" OR \"Petronia\" OR \"Pyrgilauda\" OR \"Alcippe\" OR \"Gampsorhynchus\" OR \"Illadopsis\" OR \"Jabouilleia\" OR \"Kenopia\" OR \"Laticilla\" OR \"Malacocincla\" OR \"Malacopteron\" OR \"Napothera\" OR \"Pellorneum\" OR \"Rimator\" OR \"Trichastoma\" OR \"Amalocichla\" OR \"Drymodes\" OR \"Eopsaltria\" OR \"Eugerygone\" OR \"Heteromyias\" OR \"Melanodryas\" OR \"Microeca\" OR \"Monachella\" OR \"Pachycephalopsis\" OR \"Peneoenanthe\" OR \"Peneothello\" OR \"Petroica\" OR \"Poecilodryas\" OR \"Tregellasia\" OR \"Peucedramus\" OR \"Microligea\" OR \"Phaenicophilus\" OR \"Xenoligea\" OR \"Phylloscopus\" OR \"Picathartes\" OR \"Antilophia\" OR \"Ceratopipra\" OR \"Chiroxiphia\" OR \"Chloropipo\" OR \"Corapipo\" OR \"Cryptopipo\" OR \"Heterocercus\" OR \"Ilicura\" OR \"Lepidothrix\" OR \"Machaeropterus\" OR \"Manacus\" OR \"Masius\" OR \"Neopelma\" OR \"Pipra\" OR \"Pseudopipra\" OR \"Tyranneutes\" OR \"Xenopipo\" OR \"Erythropitta\" OR \"Hydrornis\" OR \"Pitta\" OR \"Batis\" OR \"Platysteira\" OR \"Anaplectes\" OR \"Bubalornis\" OR \"Euplectes\" OR \"Malimbus\" OR \"Plocepasser\" OR \"Ploceus\" OR \"Quelea\" OR \"Sporopipes\" OR \"Pnoepyga\" OR \"Microbates\" OR \"Polioptila\" OR \"Ramphocaenus\" OR \"Garritornis\" OR \"Prunella\" OR \"Cinclosoma\" OR \"Ptilorrhoa\" OR \"Phainopepla\" OR \"Phainoptila\" OR \"Ptiliogonys\" OR \"Ailuroedus\" OR \"Amblyornis\" OR \"Ptilonorhynchus\" OR \"Sericulus\" OR \"Alophoixus\" OR \"Andropadus\" OR \"Arizelocichla\" OR \"Atimastillas\" OR \"Baeopogon\" OR \"Bleda\" OR \"Chlorocichla\" OR \"Criniger\" OR \"Eurillas\" OR \"Hemixos\" OR \"Hypsipetes\" OR \"Iole\" OR \"Ixos\" OR \"Neolestes\" OR \"Phyllastrephus\" OR \"Pycnonotus\" OR \"Spizixos\" OR \"Stelgidillas\" OR \"Tricholestes\" OR \"Regulus\" OR \"Anthoscopus\" OR \"Auriparus\" OR \"Remiz\" OR \"Rhagologus\" OR \"Eleoscytalopus\" OR \"Liosceles\" OR \"Psilorhamphus\" OR \"Pteroptochos\" OR \"Scelorchilus\" OR \"Scytalopus\" OR \"Teledromas\" OR \"Rhipidura\" OR \"Rhodinocichla\" OR \"Sapayoa\" OR \"Sitta\" OR \"Spindalis\" OR \"Chelidorhynx\" OR \"Culicicapa\" OR \"Elminia\" OR \"Acridotheres\" OR \"Agropsar\" OR \"Ampeliceps\" OR \"Aplonis\" OR \"Basilornis\" OR \"Cinnyricinclus\" OR \"Creatophora\" OR \"Gracula\" OR \"Gracupica\" OR \"Hartlaubius\" OR \"Hylopsar\" OR \"Lamprotornis\" OR \"Leucopsar\" OR \"Mino\" OR \"Notopholia\" OR \"Onychognathus\" OR \"Pastor\" OR \"Poeoptera\" OR \"Rhabdornis\" OR \"Sarcops\" OR \"Scissirostrum\" OR \"Speculipastor\" OR \"Spodiopsar\" OR \"Streptocitta\" OR \"Sturnia\" OR \"Sturnus\" OR \"Chamaea\" OR \"Chleuasicus\" OR \"Chloropeta\" OR \"Chrysomma\" OR \"Conostoma\" OR \"Fulvetta\" OR \"Lioparus\" OR \"Paradoxornis\" OR \"Pseudoalcippe\" OR \"Psittiparus\" OR \"Rhopophilus\" OR \"Sinosuthora\" OR \"Suthora\" OR \"Sylvia\" OR \"Teretistris\" OR \"Akletos\" OR \"Ampelornis\" OR \"Aprositornis\" OR \"Batara\" OR \"Cercomacra\" OR \"Cercomacroides\" OR \"Cymbilaimus\" OR \"Dichrozona\" OR \"Drymophila\" OR \"Dysithamnus\" OR \"Epinecrophylla\" OR \"Euchrepomis\" OR \"Formicivora\" OR \"Frederickena\" OR \"Gymnocichla\" OR \"Gymnopithys\" OR \"Hafferia\" OR \"Herpsilochmus\" OR \"Hylophylax\" OR \"Hypocnemis\" OR \"Hypocnemoides\" OR \"Hypoedaleus\" OR \"Isleria\" OR \"Mackenziaena\" OR \"Megastictus\" OR \"Microrhopias\" OR \"Myrmeciza\" OR \"Myrmelastes\" OR \"Myrmoborus\" OR \"Myrmochanes\" OR \"Myrmoderus\" OR \"Myrmophylax\" OR \"Myrmorchilus\" OR \"Myrmornis\" OR \"Myrmotherula\" OR \"Neoctantes\" OR \"Oneillornis\" OR \"Percnostola\" OR \"Phaenostictus\" OR \"Phlegopsis\" OR \"Pithys\" OR \"Poliocrania\" OR \"Pygiptila\" OR \"Pyriglena\" OR \"Rhegmatorhina\" OR \"Rhopias\" OR \"Rhopornis\" OR \"Sakesphorus\" OR \"Sciaphylax\" OR \"Sclateria\" OR \"Sipia\" OR \"Taraba\" OR \"Thamnistes\" OR \"Thamnomanes\" OR \"Thamnophilus\" OR \"Willisornis\" OR \"Xenornis\" OR \"Anisognathus\" OR \"Bangsia\" OR \"Buthraupis\" OR \"Calochaetes\" OR \"Catamblyrhynchus\" OR \"Catamenia\" OR \"Charitospiza\" OR \"Chlorochrysa\" OR \"Chlorophanes\" OR \"Chlorornis\" OR \"Chrysothlypis\" OR \"Cissopis\" OR \"Cnemoscopus\" OR \"Coereba\" OR \"Compsospiza\" OR \"Compsothraupis\" OR \"Conirostrum\" OR \"Conothraupis\" OR \"Coryphospingus\" OR \"Creurgops\" OR \"Cyanerpes\" OR \"Cyanicterus\" OR \"Cypsnagra\" OR \"Dacnis\" OR \"Delothraupis\" OR \"Diglossa\" OR \"Diuca\" OR \"Dolospingus\" OR \"Donacospiza\" OR \"Dubusia\" OR \"Emberizoides\" OR \"Embernagra\" OR \"Eucometis\" OR \"Euneornis\" OR \"Geospiza\" OR \"Gubernatrix\" OR \"Haplospiza\" OR \"Hemispingus\" OR \"Hemithraupis\" OR \"Heterospingus\" OR \"Incaspiza\" OR \"Iridophanes\" OR \"Iridosornis\" OR \"Lanio\" OR \"Lophospingus\" OR \"Loxigilla\" OR \"Loxipasser\" OR \"Melanodera\" OR \"Melanospiza\" OR \"Melopyrrha\" OR \"Nemosia\" OR \"Nephelornis\" OR \"Oreomanes\" OR \"Oryzoborus\" OR \"Parkerthraustes\" OR \"Paroaria\" OR \"Phrygilus\" OR \"Piezorina\" OR \"Pipraeidea\" OR \"Poospiza\" OR \"Pyrrhocoma\" OR \"Ramphocelus\" OR \"Rhodospingus\" OR \"Saltator\" OR \"Saltatricula\" OR \"Schistochlamys\" OR \"Sericossypha\" OR \"Sicalis\" OR \"Sporophila\" OR \"Stephanophorus\" OR \"Tachyphonus\" OR \"Tangara\" OR \"Tersina\" OR \"Thlypopsis\" OR \"Thraupis\" OR \"Tiaris\" OR \"Trichothraupis\" OR \"Volatinia\" OR \"Wetmorethraupis\" OR \"Xenodacnis\" OR \"Xenospingus\" OR \"Tichodroma\" OR \"Macronus\" OR \"Pomatorhinus\" OR \"Spelaeornis\" OR \"Stachyridopsis\" OR \"Stachyris\" OR \"Iodopleura\" OR \"Laniisoma\" OR \"Laniocera\" OR \"Myiobius\" OR \"Onychorhynchus\" OR \"Oxyruncus\" OR \"Pachyramphus\" OR \"Schiffornis\" OR \"Terenotriccus\" OR \"Tityra\" OR \"Xenopsaris\" OR \"Campylorhynchus\" OR \"Cantorchilus\" OR \"Catherpes\" OR \"Cinnycerthia\" OR \"Cistothorus\" OR \"Cyphorhinus\" OR \"Henicorhina\" OR \"Microcerculus\" OR \"Odontorchilus\" OR \"Pheugopedius\" OR \"Salpinctes\" OR \"Thryomanes\" OR \"Thryophilus\" OR \"Thryothorus\" OR \"Troglodytes\" OR \"Uropsila\" OR \"Catharus\" OR \"Cichlopsis\" OR \"Entomodestes\" OR \"Geokichla\" OR \"Hylocichla\" OR \"Ixoreus\" OR \"Myadestes\" OR \"Neocossyphus\" OR \"Ridgwayia\" OR \"Sialia\" OR \"Stizorhina\" OR \"Turdus\" OR \"Zoothera\" OR \"Agriornis\" OR \"Alectrurus\" OR \"Anairetes\" OR \"Aphanotriccus\" OR \"Arundinicola\" OR \"Atalotriccus\" OR \"Attila\" OR \"Camptostoma\" OR \"Capsiempis\" OR \"Casiornis\" OR \"Cnemarchus\" OR \"Cnemotriccus\" OR \"Cnipodectes\" OR \"Colonia\" OR \"Colorhamphus\" OR \"Conopias\" OR \"Contopus\" OR \"Corythopis\" OR \"Culicivora\" OR \"Deltarhynchus\" OR \"Elaenia\" OR \"Empidonax\" OR \"Empidonomus\" OR \"Euscarthmus\" OR \"Fluvicola\" OR \"Griseotyrannus\" OR \"Gubernetes\" OR \"Hemitriccus\" OR \"Heteroxolmis\" OR \"Hirundinea\" OR \"Hymenops\" OR \"Inezia\" OR \"Knipolegus\" OR \"Lathrotriccus\" OR \"Legatus\" OR \"Leptopogon\" OR \"Lessonia\" OR \"Lophotriccus\" OR \"Machetornis\" OR \"Mecocerculus\" OR \"Megarynchus\" OR \"Mionectes\" OR \"Mitrephanes\" OR \"Muscigralla\" OR \"Muscisaxicola\" OR \"Myiarchus\" OR \"Myiodynastes\" OR \"Myiopagis\" OR \"Myiophobus\" OR \"Myiornis\" OR \"Myiotheretes\" OR \"Myiotriccus\" OR \"Myiozetetes\" OR \"Neopipo\" OR \"Neoxolmis\" OR \"Nephelomyias\" OR \"Ochthoeca\" OR \"Ochthornis\" OR \"Oncostoma\" OR \"Ornithion\" OR \"Phaeomyias\" OR \"Philohydor\" OR \"Phyllomyias\" OR \"Phylloscartes\" OR \"Piprites\" OR \"Pitangus\" OR \"Platyrinchus\" OR \"Poecilotriccus\" OR \"Pogonotriccus\" OR \"Polioxolmis\" OR \"Polystictus\" OR \"Pseudelaenia\" OR \"Pseudocolopteryx\" OR \"Pseudotriccus\" OR \"Pyrocephalus\" OR \"Pyrrhomyias\" OR \"Ramphotrigon\" OR \"Rhynchocyclus\" OR \"Rhytipterna\" OR \"Satrapa\" OR \"Sayornis\" OR \"Serpophaga\" OR \"Silvicultrix\" OR \"Sirystes\" OR \"Stigmatura\" OR \"Sublegatus\" OR \"Suiriri\" OR \"Tachuris\" OR \"Taeniotriccus\" OR \"Todirostrum\" OR \"Tolmomyias\" OR \"Tumbezia\" OR \"Tyrannopsis\" OR \"Tyrannulus\" OR \"Tyrannus\" OR \"Uromyias\" OR \"Xenotriccus\" OR \"Xolmis\" OR \"Zimmerius\" OR \"Urocynchramus\" OR \"Artamella\" OR \"Calicalicus\" OR \"Cyanolanius\" OR \"Euryceros\" OR \"Falculea\" OR \"Hypositta\" OR \"Leptopterus\" OR \"Mystacornis\" OR \"Newtonia\" OR \"Oriolia\" OR \"Philentoma\" OR \"Prionops\" OR \"Pseudobias\" OR \"Schetba\" OR \"Tephrodornis\" OR \"Tylas\" OR \"Vanga\" OR \"Xenopirostris\" OR \"Anomalospiza\" OR \"Vidua\" OR \"Cyclarhis\" OR \"Erpornis\" OR \"Hylophilus\" OR \"Pteruthius\" OR \"Vireo\" OR \"Vireolanius\" OR \"Zeledonia\" OR \"Apalopteron\" OR \"Dasycrotapha\" OR \"Heleia\" OR \"Lophozosterops\" OR \"Sterrhoptilus\" OR \"Yuhina\" OR \"Zosterops\" OR \"Zosterornis\" OR \"Agamia\" OR \"Ardea\" OR \"Ardeola\" OR \"Botaurus\" OR \"Bubulcus\" OR \"Butorides\" OR \"Cochlearius\" OR \"Dupetor\" OR \"Egretta\" OR \"Gorsachius\" OR \"Ixobrychus\" OR \"Nyctanassa\" OR \"Nycticorax\" OR \"Pilherodius\" OR \"Syrigma\" OR \"Tigriornis\" OR \"Tigrisoma\" OR \"Zebrilus\" OR \"Balaeniceps\" OR \"Pelecanus\" OR \"Scopus\" OR \"Bostrychia\" OR \"Eudocimus\" OR \"Geronticus\" OR \"Lophotibis\" OR \"Mesembrinibis\" OR \"Nipponia\" OR \"Phimosus\" OR \"Platalea\" OR \"Plegadis\" OR \"Pseudibis\" OR \"Theristicus\" OR \"Threskiornis\" OR \"Phaethon\" OR \"Phoeniconaias\" OR \"Phoenicoparrus\" OR \"Phoenicopterus\" OR \"Bucco\" OR \"Chelidoptera\" OR \"Hapaloptila\" OR \"Hypnelus\" OR \"Malacoptila\" OR \"Micromonacha\" OR \"Monasa\" OR \"Nonnula\" OR \"Notharchus\" OR \"Nystalus\" OR \"Capito\" OR \"Eubucco\" OR \"Brachygalba\" OR \"Galbalcyrhynchus\" OR \"Galbula\" OR \"Jacamaralcyon\" OR \"Jacamerops\" OR \"Indicator\" OR \"Melichneutes\" OR \"Melignomon\" OR \"Prodotiscus\" OR \"Buccanodon\" OR \"Gymnobucco\" OR \"Lybius\" OR \"Pogoniulus\" OR \"Stactolaema\" OR \"Trachyphonus\" OR \"Psilopogon\" OR \"Blythipicus\" OR \"Campephilus\" OR \"Campethera\" OR \"Celeus\" OR \"Chloropicus\" OR \"Chrysocolaptes\" OR \"Chrysophlegma\" OR \"Colaptes\" OR \"Dendrocopos\" OR \"Dendrocoptes\" OR \"Dendropicos\" OR \"Dinopium\" OR \"Dryobates\" OR \"Dryocopus\" OR \"Gecinulus\" OR \"Geocolaptes\" OR \"Jynx\" OR \"Leiopicus\" OR \"Leuconotopicus\" OR \"Meiglyptes\" OR \"Melanerpes\" OR \"Micropternus\" OR \"Mulleripicus\" OR \"Nesoctites\" OR \"Picoides\" OR \"Piculus\" OR \"Picumnus\" OR \"Picus\" OR \"Reinwardtipicus\" OR \"Sasia\" OR \"Sphyrapicus\" OR \"Veniliornis\" OR \"Yungipicus\" OR \"Andigena\" OR \"Aulacorhynchus\" OR \"Pteroglossus\" OR \"Ramphastos\" OR \"Selenidera\" OR \"Semnornis\" OR \"Aechmophorus\" OR \"Podiceps\" OR \"Podilymbus\" OR \"Poliocephalus\" OR \"Rollandia\" OR \"Tachybaptus\" OR \"Diomedea\" OR \"Phoebastria\" OR \"Phoebetria\" OR \"Thalassarche\" OR \"Hydrobates\" OR \"Oceanodroma\" OR \"Fregetta\" OR \"Garrodia\" OR \"Nesofregetta\" OR \"Oceanites\" OR \"Pelagodroma\" OR \"Aphrodroma\" OR \"Ardenna\" OR \"Bulweria\" OR \"Calonectris\" OR \"Daption\" OR \"Fulmarus\" OR \"Halobaena\" OR \"Macronectes\" OR \"Pachyptila\" OR \"Pagodroma\" OR \"Pelecanoides\" OR \"Procellaria\" OR \"Pseudobulweria\" OR \"Pterodroma\" OR \"Puffinus\" OR \"Thalassoica\" OR \"Cacatua\" OR \"Callocephalon\" OR \"Calyptorhynchus\" OR \"Eolophus\" OR \"Lophochroa\" OR \"Nymphicus\" OR \"Probosciger\" OR \"Alipiopsitta\" OR \"Amazona\" OR \"Anodorhynchus\" OR \"Ara\" OR \"Aratinga\" OR \"Bolborhynchus\" OR \"Brotogeris\" OR \"Conuropsis\" OR \"Cyanoliseus\" OR \"Cyanopsitta\" OR \"Deroptyus\" OR \"Diopsittaca\" OR \"Enicognathus\" OR \"Eupsittula\" OR \"Forpus\" OR \"Graydidascalus\" OR \"Guarouba\" OR \"Guaruba\" OR \"Hapalopsittaca\" OR \"Leptosittaca\" OR \"Myiopsitta\" OR \"Nannopsittaca\" OR \"Orthopsittaca\" OR \"Pionites\" OR \"Pionopsitta\" OR \"Pionus\" OR \"Poicephalus\" OR \"Primolius\" OR \"Psilopsiagon\" OR \"Psittacara\" OR \"Psittacus\" OR \"Pyrilia\" OR \"Pyrrhura\" OR \"Rhynchopsitta\" OR \"Thectocercus\" OR \"Touit\" OR \"Triclaria\" OR \"Agapornis\" OR \"Alisterus\" OR \"Aprosmictus\" OR \"Barnardius\" OR \"Bolbopsittacus\" OR \"Chalcopsitta\" OR \"Charmosyna\" OR \"Coracopsis\" OR \"Cyanoramphus\" OR \"Cyclopsitta\" OR \"Eclectus\" OR \"Eos\" OR \"Eunymphicus\" OR \"Geoffroyus\" OR \"Glossopsitta\" OR \"Lathamus\" OR \"Loriculus\" OR \"Lorius\" OR \"Melopsittacus\" OR \"Micropsitta\" OR \"Neophema\" OR \"Neopsephotus\" OR \"Neopsittacus\" OR \"Northiella\" OR \"Oreopsittacus\" OR \"Parvipsitta\" OR \"Pezoporus\" OR \"Phigys\" OR \"Platycercus\" OR \"Polytelis\" OR \"Prioniturus\" OR \"Prosopeia\" OR \"Psephotellus\" OR \"Psephotus\" OR \"Pseudeos\" OR \"Psittacella\" OR \"Psittacula\" OR \"Psittaculirostris\" OR \"Psitteuteles\" OR \"Psittinus\" OR \"Psittrichas\" OR \"Purpureicephalus\" OR \"Tanygnathus\" OR \"Trichoglossus\" OR \"Vini\" OR \"Nestor\" OR \"Strigops\" OR \"Pterocles\" OR \"Syrrhaptes\" OR \"Rhea\" OR \"Aptenodytes\" OR \"Eudyptes\" OR \"Eudyptula\" OR \"Megadyptes\" OR \"Pygoscelis\" OR \"Spheniscus\" OR \"Aegolius\" OR \"Asio\" OR \"Athene\" OR \"Bubo\" OR \"Glaucidium\" OR \"Ketupa\" OR \"Lophostrix\" OR \"Megascops\" OR \"Micrathene\" OR \"Ninox\" OR \"Otus\" OR \"Pseudoscops\" OR \"Psiloscops\" OR \"Pulsatrix\" OR \"Sceloglaux\" OR \"Scotopelia\" OR \"Strix\" OR \"Surnia\" OR \"Xenoglaux\" OR \"Phodilus\" OR \"Tyto\" OR \"Aepyornis\" OR \"Mullerornis\" OR \"Struthio\" OR \"Anhinga\" OR \"Fregata\" OR \"Leucocarbo\" OR \"Microcarbo\" OR \"Nannopterum\" OR \"Phalacrocorax\" OR \"Morus\" OR \"Sula\" OR \"Crypturellus\" OR \"Eudromia\" OR \"Nothocercus\" OR \"Nothoprocta\" OR \"Nothura\" OR \"Rhynchotus\" OR \"Tinamotis\" OR \"Tinamus\" OR \"Apalharpactes\" OR \"Apaloderma\" OR \"Harpactes\" OR \"Pharomachrus\" OR \"Trogon\" OR \"Tetrastes\" OR \"Hesperiphona\") AND (\"experiment\\*\" OR \"manipulat\\*\")))\\>\\\n\\\nThe search was also conducted on SCOPUS using Advance Search Option and Title Abstract and Keyword (TITLE-ABS-KEY) on the same dates using the string\\\n\\\n\\<TITLE-ABS-KEY (((\"green\\*\" OR \"herb\\*\" OR \"aromatic\\*\") AND \"nest\\*\" AND (\"bird\\*\" OR \"aves\" OR \"avian\" OR \"ornithol\\*\" OR \"passerine\\*\" OR \"passeriform\\*\" OR \"songbird\\*\" OR \"Accipiter\" OR \"Aegypius\" OR \"Aquila\" OR \"Aviceda\" OR \"Busarellus\" OR \"Butastur\" OR \"Buteo\" OR \"Buteogallus\" OR \"Chondrohierax\" OR \"Circaetus\" OR \"Circus\" OR \"Clanga\" OR \"Elanoides\" OR \"Elanus\" OR \"Gampsonyx\" OR \"Geranoaetus\" OR \"Geranospiza\" OR \"Gypaetus\" OR \"Gypohierax\" OR \"Gyps\" OR \"Haliaeetus\" OR \"Haliastur\" OR \"Harpagus\" OR \"Harpia\" OR \"Hieraaetus\" OR \"Ictinaetus\" OR \"Ictinia\" OR \"Kaupifalco\" OR \"Leptodon\" OR \"Leucopternis\" OR \"Lophotriorchis\" OR \"Milvus\" OR \"Morphnarchus\" OR \"Morphnus\" OR \"Necrosyrtes\" OR \"Neophron\" OR \"Nisaetus\" OR \"Parabuteo\" OR \"Pernis\" OR \"Pithecophaga\" OR \"Polemaetus\" OR \"Pseudastur\" OR \"Rostrhamus\" OR \"Rupornis\" OR \"Sarcogyps\" OR \"Spilornis\" OR \"Spizaetus\" OR \"Stephanoaetus\" OR \"Terathopius\" OR \"Torgos\" OR \"Trigonoceps\" OR \"Cathartes\" OR \"Coragyps\" OR \"Gymnogyps\" OR \"Sarcoramphus\" OR \"Vultur\" OR \"Pandion\" OR \"Sagittarius\" OR \"Aix\" OR \"Alopochen\" OR \"Amazonetta\" OR \"Anas\" OR \"Anser\" OR \"Asarcornis\" OR \"Aythya\" OR \"Branta\" OR \"Bucephala\" OR \"Cairina\" OR \"Callonetta\" OR \"Cereopsis\" OR \"Chen\" OR \"Chenonetta\" OR \"Chloephaga\" OR \"Clangula\" OR \"Coscoroba\" OR \"Cyanochen\" OR \"Cygnus\" OR \"Dendrocygna\" OR \"Heteronetta\" OR \"Histrionicus\" OR \"Hymenolaimus\" OR \"Lophodytes\" OR \"Lophonetta\" OR \"Malacorhynchus\" OR \"Mareca\" OR \"Marmaronetta\" OR \"Melanitta\" OR \"Merganetta\" OR \"Mergellus\" OR \"Mergus\" OR \"Neochen\" OR \"Netta\" OR \"Nettapus\" OR \"Nomonyx\" OR \"Oxyura\" OR \"Plectropterus\" OR \"Polysticta\" OR \"Pteronetta\" OR \"Sarkidiornis\" OR \"Sibirionetta\" OR \"Somateria\" OR \"Spatula\" OR \"Tachyeres\" OR \"Tadorna\" OR \"Thalassornis\" OR \"Anhima\" OR \"Chauna\" OR \"Anseranas\" OR \"Aegotheles\" OR \"Aerodramus\" OR \"Aeronautes\" OR \"Apus\" OR \"Chaetura\" OR \"Collocalia\" OR \"Cypseloides\" OR \"Cypsiurus\" OR \"Hirundapus\" OR \"Panyptila\" OR \"Streptoprocne\" OR \"Tachornis\" OR \"Tachymarptis\" OR \"Hemiprocne\" OR \"Abeillia\" OR \"Adelomyia\" OR \"Aglaeactis\" OR \"Aglaiocercus\" OR \"Amazilia\" OR \"Androdon\" OR \"Anopetia\" OR \"Anthocephala\" OR \"Anthracothorax\" OR \"Archilochus\" OR \"Atthis\" OR \"Augastes\" OR \"Avocettula\" OR \"Basilinna\" OR \"Boissonneaua\" OR \"Calliphlox\" OR \"Calypte\" OR \"Campylopterus\" OR \"Chaetocercus\" OR \"Chalcostigma\" OR \"Chalybura\" OR \"Chlorestes\" OR \"Chlorostilbon\" OR \"Chrysolampis\" OR \"Chrysuronia\" OR \"Clytolaema\" OR \"Coeligena\" OR \"Colibri\" OR \"Cyanophaia\" OR \"Cynanthus\" OR \"Discosura\" OR \"Doricha\" OR \"Doryfera\" OR \"Elvira\" OR \"Ensifera\" OR \"Eriocnemis\" OR \"Eugenes\" OR \"Eulampis\" OR \"Eulidia\" OR \"Eupetomena\" OR \"Eupherusa\" OR \"Eutoxeres\" OR \"Florisuga\" OR \"Glaucis\" OR \"Goethalsia\" OR \"Goldmania\" OR \"Haplophaedia\" OR \"Heliactin\" OR \"Heliangelus\" OR \"Heliodoxa\" OR \"Heliomaster\" OR \"Heliothryx\" OR \"Hylocharis\" OR \"Juliamyia\" OR \"Klais\" OR \"Lafresnaya\" OR \"Lampornis\" OR \"Lamprolaima\" OR \"Lepidopyga\" OR \"Lesbia\" OR \"Leucippus\" OR \"Leucochloris\" OR \"Lophornis\" OR \"Mellisuga\" OR \"Metallura\" OR \"Microchera\" OR \"Myrmia\" OR \"Myrtis\" OR \"Ocreatus\" OR \"Opisthoprora\" OR \"Oreonympha\" OR \"Oreotrochilus\" OR \"Orthorhyncus\" OR \"Oxypogon\" OR \"Panterpe\" OR \"Patagona\" OR \"Phaeochroa\" OR \"Phaethornis\" OR \"Phlogophilus\" OR \"Polyonymus\" OR \"Polytmus\" OR \"Pterophanes\" OR \"Ramphodon\" OR \"Ramphomicron\" OR \"Rhodopis\" OR \"Sappho\" OR \"Schistes\" OR \"Selasphorus\" OR \"Sephanoides\" OR \"Stephanoxis\" OR \"Sternoclyta\" OR \"Taphrospilus\" OR \"Thalurania\" OR \"Thaumastura\" OR \"Threnetes\" OR \"Topaza\" OR \"Trochilus\" OR \"Urochroa\" OR \"Urosticte\" OR \"Apteryx\" OR \"Anthracoceros\" OR \"Buceros\" OR \"Bycanistes\" OR \"Lophoceros\" OR \"Penelopides\" OR \"Rhabdotorrhinus\" OR \"Rhyticeros\" OR \"Tockus\" OR \"Bucorvus\" OR \"Phoeniculus\" OR \"Rhinopomastus\" OR \"Upupa\" OR \"Antrostomus\" OR \"Caprimulgus\" OR \"Chordeiles\" OR \"Eleothreptus\" OR \"Eurostopodus\" OR \"Hydropsalis\" OR \"Lurocalis\" OR \"Lyncornis\" OR \"Nyctidromus\" OR \"Nyctiphrynus\" OR \"Nyctipolus\" OR \"Nyctiprogne\" OR \"Phalaenoptilus\" OR \"Setopagis\" OR \"Systellura\" OR \"Uropsalis\" OR \"Nyctibius\" OR \"Batrachostomus\" OR \"Podargus\" OR \"Steatornis\" OR \"Cariama\" OR \"Casuarius\" OR \"Dromaius\" OR \"Aethia\" OR \"Alca\" OR \"Alle\" OR \"Brachyramphus\" OR \"Cepphus\" OR \"Cerorhinca\" OR \"Fratercula\" OR \"Pinguinus\" OR \"Ptychoramphus\" OR \"Synthliboramphus\" OR \"Uria\" OR \"Burhinus\" OR \"Anarhynchus\" OR \"Charadrius\" OR \"Elseyornis\" OR \"Erythrogonys\" OR \"Hoploxypterus\" OR \"Oreopholus\" OR \"Peltohyas\" OR \"Phegornis\" OR \"Pluvialis\" OR \"Thinornis\" OR \"Vanellus\" OR \"Chionis\" OR \"Dromas\" OR \"Cursorius\" OR \"Glareola\" OR \"Rhinoptilus\" OR \"Stiltia\" OR \"Haematopus\" OR \"Actophilornis\" OR \"Hydrophasianus\" OR \"Irediparra\" OR \"Jacana\" OR \"Metopidius\" OR \"Microparra\" OR \"Anous\" OR \"Chlidonias\" OR \"Chroicocephalus\" OR \"Creagrus\" OR \"Gelochelidon\" OR \"Gygis\" OR \"Hydrocoloeus\" OR \"Hydroprogne\" OR \"Ichthyaetus\" OR \"Larosterna\" OR \"Larus\" OR \"Leucophaeus\" OR \"Onychoprion\" OR \"Pagophila\" OR \"Phaetusa\" OR \"Rhodostethia\" OR \"Rissa\" OR \"Rynchops\" OR \"Sterna\" OR \"Sternula\" OR \"Thalasseus\" OR \"Xema\" OR \"Pedionomus\" OR \"Pluvianellus\" OR \"Pluvianus\" OR \"Himantopus\" OR \"Recurvirostra\" OR \"Nycticryphes\" OR \"Rostratula\" OR \"Actitis\" OR \"Arenaria\" OR \"Bartramia\" OR \"Calidris\" OR \"Coenocorypha\" OR \"Gallinago\" OR \"Limnodromus\" OR \"Limosa\" OR \"Lymnocryptes\" OR \"Numenius\" OR \"Phalaropus\" OR \"Scolopax\" OR \"Tringa\" OR \"Xenus\" OR \"Stercorarius\" OR \"Attagis\" OR \"Thinocorus\" OR \"Turnix\" OR \"Ciconia\" OR \"Ephippiorhynchus\" OR \"Jabiru\" OR \"Leptoptilos\" OR \"Mycteria\" OR \"Colius\" OR \"Urocolius\" OR \"Alectroenas\" OR \"Alopecoenas\" OR \"Caloenas\" OR \"Chalcophaps\" OR \"Claravis\" OR \"Columba\" OR \"Columbina\" OR \"Didunculus\" OR \"Drepanoptila\" OR \"Ducula\" OR \"Ectopistes\" OR \"Gallicolumba\" OR \"Geopelia\" OR \"Geophaps\" OR \"Geotrygon\" OR \"Goura\" OR \"Gymnophaps\" OR \"Hemiphaga\" OR \"Henicophaps\" OR \"Leptotila\" OR \"Leptotrygon\" OR \"Leucosarcia\" OR \"Lopholaimus\" OR \"Macropygia\" OR \"Metriopelia\" OR \"Ocyphaps\" OR \"Oena\" OR \"Otidiphaps\" OR \"Patagioenas\" OR \"Petrophassa\" OR \"Pezophaps\" OR \"Phapitreron\" OR \"Phaps\" OR \"Ptilinopus\" OR \"Raphus\" OR \"Reinwardtoena\" OR \"Spilopelia\" OR \"Streptopelia\" OR \"Treron\" OR \"Trugon\" OR \"Turacoena\" OR \"Turtur\" OR \"Uropelia\" OR \"Zenaida\" OR \"Zentrygon\" OR \"Actenoides\" OR \"Alcedo\" OR \"Caridonax\" OR \"Ceryle\" OR \"Ceyx\" OR \"Chloroceryle\" OR \"Cittura\" OR \"Corythornis\" OR \"Dacelo\" OR \"Halcyon\" OR \"Ispidina\" OR \"Lacedo\" OR \"Megaceryle\" OR \"Melidora\" OR \"Syma\" OR \"Tanysiptera\" OR \"Todiramphus\" OR \"Atelornis\" OR \"Brachypteracias\" OR \"Geobiastes\" OR \"Coracias\" OR \"Eurystomus\" OR \"Merops\" OR \"Nyctyornis\" OR \"Baryphthengus\" OR \"Electron\" OR \"Eumomota\" OR \"Hylomanes\" OR \"Momotus\" OR \"Todus\" OR \"Cacomantis\" OR \"Carpococcyx\" OR \"Centropus\" OR \"Cercococcyx\" OR \"Chrysococcyx\" OR \"Clamator\" OR \"Coccycua\" OR \"Coccyzus\" OR \"Coua\" OR \"Crotophaga\" OR \"Cuculus\" OR \"Dasylophus\" OR \"Dromococcyx\" OR \"Eudynamys\" OR \"Geococcyx\" OR \"Guira\" OR \"Hierococcyx\" OR \"Morococcyx\" OR \"Neomorphus\" OR \"Pachycoccyx\" OR \"Phaenicophaeus\" OR \"Piaya\" OR \"Rhinortha\" OR \"Scythrops\" OR \"Surniculus\" OR \"Tapera\" OR \"Urodynamis\" OR \"Zanclostomus\" OR \"Dinornis\" OR \"Anomalopteryx\" OR \"Emeus\" OR \"Euryapteryx\" OR \"Eurypyga\" OR \"Rhynochetos\" OR \"Caracara\" OR \"Daptrius\" OR \"Falco\" OR \"Herpetotheres\" OR \"Ibycter\" OR \"Micrastur\" OR \"Microhierax\" OR \"Milvago\" OR \"Phalcoboenus\" OR \"Polihierax\" OR \"Spiziapteryx\" OR \"Aburria\" OR \"Chamaepetes\" OR \"Crax\" OR \"Mitu\" OR \"Nothocrax\" OR \"Oreophasis\" OR \"Ortalis\" OR \"Pauxi\" OR \"Penelope\" OR \"Penelopina\" OR \"Pipile\" OR \"Alectura\" OR \"Megapodius\" OR \"Acryllium\" OR \"Guttera\" OR \"Numida\" OR \"Callipepla\" OR \"Colinus\" OR \"Cyrtonyx\" OR \"Dendrortyx\" OR \"Odontophorus\" OR \"Oreortyx\" OR \"Philortyx\" OR \"Ptilopachus\" OR \"Rhynchortyx\" OR \"Alectoris\" OR \"Ammoperdix\" OR \"Arborophila\" OR \"Argusianus\" OR \"Bambusicola\" OR \"Bonasa\" OR \"Caloperdix\" OR \"Centrocercus\" OR \"Chrysolophus\" OR \"Coturnix\" OR \"Crossoptilon\" OR \"Dendragapus\" OR \"Excalfactoria\" OR \"Falcipennis\" OR \"Francolinus\" OR \"Gallus\" OR \"Haematortyx\" OR \"Ithaginis\" OR \"Lagopus\" OR \"Lerwa\" OR \"Lophophorus\" OR \"Lophura\" OR \"Lyrurus\" OR \"Meleagris\" OR \"Pavo\" OR \"Peliperdix\" OR \"Perdix\" OR \"Phasianus\" OR \"Polyplectron\" OR \"Pternistis\" OR \"Pucrasia\" OR \"Rhizothera\" OR \"Rollulus\" OR \"Scleroptila\" OR \"Syrmaticus\" OR \"Tetrao\" OR \"Tetraogallus\" OR \"Tetraophasis\" OR \"Tragopan\" OR \"Tympanuchus\" OR \"Gavia\" OR \"Aramus\" OR \"Anthropoides\" OR \"Antigone\" OR \"Balearica\" OR \"Bugeranus\" OR \"Grus\" OR \"Leucogeranus\" OR \"Heliornis\" OR \"Psophia\" OR \"Aenigmatolimnas\" OR \"Amaurolimnas\" OR \"Amaurornis\" OR \"Anurolimnas\" OR \"Aramides\" OR \"Atlantisia\" OR \"Coturnicops\" OR \"Crex\" OR \"Dryolimnas\" OR \"Eulabeornis\" OR \"Fulica\" OR \"Gallicrex\" OR \"Gallinula\" OR \"Gallirallus\" OR \"Laterallus\" OR \"Lewinia\" OR \"Micropygia\" OR \"Neocrex\" OR \"Nesoclopeus\" OR \"Paragallinula\" OR \"Pardirallus\" OR \"Porphyrio\" OR \"Porphyriops\" OR \"Porzana\" OR \"Rallicula\" OR \"Rallina\" OR \"Rallus\" OR \"Tribonyx\" OR \"Canirallus\" OR \"Sarothrura\" OR \"Leptosomus\" OR \"Corythaeola\" OR \"Corythaixoides\" OR \"Crinifer\" OR \"Musophaga\" OR \"Tauraco\" OR \"Opisthocomus\" OR \"Afrotis\" OR \"Ardeotis\" OR \"Chlamydotis\" OR \"Neotis\" OR \"Otis\" OR \"Tetrax\" OR \"Acanthisitta\" OR \"Pachyplichas\" OR \"Traversia\" OR \"Xenicus\" OR \"Acanthiza\" OR \"Acanthornis\" OR \"Aethomyias\" OR \"Aphelocephala\" OR \"Calamanthus\" OR \"Gerygone\" OR \"Hylacola\" OR \"Neosericornis\" OR \"Oreoscopus\" OR \"Origma\" OR \"Pachycare\" OR \"Pycnoptilus\" OR \"Pyrrholaemus\" OR \"Sericornis\" OR \"Smicrornis\" OR \"Acrocephalus\" OR \"Arundinax\" OR \"Calamonastides\" OR \"Hippolais\" OR \"Iduna\" OR \"Nesillas\" OR \"Aegithalos\" OR \"Leptopoecile\" OR \"Psaltriparus\" OR \"Aegithina\" OR \"Alaemon\" OR \"Alauda\" OR \"Alaudala\" OR \"Ammomanes\" OR \"Calandrella\" OR \"Calendulauda\" OR \"Chersomanes\" OR \"Eremophila\" OR \"Eremopterix\" OR \"Galerida\" OR \"Lullula\" OR \"Melanocorypha\" OR \"Mirafra\" OR \"Pinarocorys\" OR \"Spizocorys\" OR \"Artamus\" OR \"Gymnorhina\" OR \"Melloria\" OR \"Bombycilla\" OR \"Buphagus\" OR \"Calcarius\" OR \"Plectrophenax\" OR \"Rhynchophanes\" OR \"Callaeas\" OR \"Heteralocha\" OR \"Philesturnus\" OR \"Calyptophilus\" OR \"Campephaga\" OR \"Ceblepyris\" OR \"Coracina\" OR \"Edolisoma\" OR \"Lalage\" OR \"Malindangia\" OR \"Pericrocotus\" OR \"Amaurospiza\" OR \"Cardinalis\" OR \"Caryothraustes\" OR \"Chlorothraupis\" OR \"Cyanocompsa\" OR \"Cyanoloxia\" OR \"Granatellus\" OR \"Habia\" OR \"Passerina\" OR \"Periporphyrus\" OR \"Pheucticus\" OR \"Piranga\" OR \"Spiza\" OR \"Certhia\" OR \"Salpornis\" OR \"Abroscopus\" OR \"Cettia\" OR \"Horornis\" OR \"Phyllergates\" OR \"Tesia\" OR \"Urosphena\" OR \"Chloropsis\" OR \"Cinclus\" OR \"Apalis\" OR \"Artisornis\" OR \"Camaroptera\" OR \"Cisticola\" OR \"Eremomela\" OR \"Heliolais\" OR \"Hypergerus\" OR \"Neomixis\" OR \"Oreolais\" OR \"Orthotomus\" OR \"Phragmacia\" OR \"Poliolais\" OR \"Prinia\" OR \"Schistolais\" OR \"Urolais\" OR \"Urorhipis\" OR \"Climacteris\" OR \"Cormobates\" OR \"Conopophaga\" OR \"Struthidea\" OR \"Aphelocoma\" OR \"Calocitta\" OR \"Cissa\" OR \"Coloeus\" OR \"Corvus\" OR \"Cyanocitta\" OR \"Cyanocorax\" OR \"Cyanolyca\" OR \"Cyanopica\" OR \"Dendrocitta\" OR \"Garrulus\" OR \"Gymnorhinus\" OR \"Nucifraga\" OR \"Perisoreus\" OR \"Pica\" OR \"Platylophus\" OR \"Podoces\" OR \"Psilorhinus\" OR \"Ptilostomus\" OR \"Pyrrhocorax\" OR \"Urocissa\" OR \"Ampelioides\" OR \"Ampelion\" OR \"Carpornis\" OR \"Cephalopterus\" OR \"Conioptilon\" OR \"Cotinga\" OR \"Doliornis\" OR \"Gymnoderus\" OR \"Haematoderus\" OR \"Lipaugus\" OR \"Perissocephalus\" OR \"Phoenicircus\" OR \"Phytotoma\" OR \"Pipreola\" OR \"Porphyrolaema\" OR \"Procnias\" OR \"Pyroderus\" OR \"Querula\" OR \"Rupicola\" OR \"Snowornis\" OR \"Xipholena\" OR \"Zaratornis\" OR \"Dasyornis\" OR \"Dicaeum\" OR \"Prionochilus\" OR \"Dicrurus\" OR \"Donacobius\" OR \"Dulus\" OR \"Emberiza\" OR \"Amadina\" OR \"Amandava\" OR \"Cryptospiza\" OR \"Erythrura\" OR \"Estrilda\" OR \"Euodice\" OR \"Euschistospiza\" OR \"Lagonosticta\" OR \"Lonchura\" OR \"Mandingoa\" OR \"Neochmia\" OR \"Nesocharis\" OR \"Nigrita\" OR \"Ortygospiza\" OR \"Parmoptila\" OR \"Pyrenestes\" OR \"Pytilia\" OR \"Spermophaga\" OR \"Stagonopleura\" OR \"Taeniopygia\" OR \"Uraeginthus\" OR \"Calyptomena\" OR \"Cymbirhynchus\" OR \"Eurylaimus\" OR \"Psarisomus\" OR \"Serilophus\" OR \"Smithornis\" OR \"Chamaeza\" OR \"Formicarius\" OR \"Acanthis\" OR \"Agraphospiza\" OR \"Akialoa\" OR \"Bucanetes\" OR \"Carduelis\" OR \"Carpodacus\" OR \"Chloris\" OR \"Chlorodrepanis\" OR \"Chlorophonia\" OR \"Chrysocorythus\" OR \"Coccothraustes\" OR \"Crithagra\" OR \"Drepanis\" OR \"Eophona\" OR \"Euphonia\" OR \"Fringilla\" OR \"Haemorhous\" OR \"Hemignathus\" OR \"Himatione\" OR \"Leucosticte\" OR \"Linaria\" OR \"Linurgus\" OR \"Loxia\" OR \"Loxioides\" OR \"Loxops\" OR \"Magumma\" OR \"Melamprosops\" OR \"Oreomystis\" OR \"Paroreomyza\" OR \"Pinicola\" OR \"Procarduelis\" OR \"Pseudonestor\" OR \"Psittirostra\" OR \"Pyrrhoplectes\" OR \"Pyrrhula\" OR \"Rhodopechys\" OR \"Rhodospiza\" OR \"Serinus\" OR \"Spinus\" OR \"Telespiza\" OR \"Anabacerthia\" OR \"Anabazenops\" OR \"Ancistrops\" OR \"Anumbius\" OR \"Aphrastura\" OR \"Asthenes\" OR \"Automolus\" OR \"Berlepschia\" OR \"Campylorhamphus\" OR \"Certhiasomus\" OR \"Certhiaxis\" OR \"Cinclodes\" OR \"Clibanornis\" OR \"Coryphistera\" OR \"Cranioleuca\" OR \"Deconychura\" OR \"Dendrexetastes\" OR \"Dendrocincla\" OR \"Dendrocolaptes\" OR \"Dendroplex\" OR \"Drymornis\" OR \"Drymotoxeres\" OR \"Furnarius\" OR \"Geocerthia\" OR \"Geositta\" OR \"Glyphorynchus\" OR \"Heliobletus\" OR \"Hellmayrea\" OR \"Hylexetastes\" OR \"Lepidocolaptes\" OR \"Leptasthenura\" OR \"Limnoctites\" OR \"Limnornis\" OR \"Lochmias\" OR \"Margarornis\" OR \"Mazaria\" OR \"Megaxenops\" OR \"Metopothrix\" OR \"Microxenops\" OR \"Nasica\" OR \"Ochetorhynchus\" OR \"Phacellodomus\" OR \"Philydor\" OR \"Phleocryptes\" OR \"Premnoplex\" OR \"Premnornis\" OR \"Pseudasthenes\" OR \"Pseudocolaptes\" OR \"Pseudoseisura\" OR \"Pygarrhichas\" OR \"Roraimia\" OR \"Schoeniophylax\" OR \"Sclerurus\" OR \"Sittasomus\" OR \"Spartonoica\" OR \"Sylviorthorhynchus\" OR \"Synallaxis\" OR \"Syndactyla\" OR \"Tarphonomus\" OR \"Thripadectes\" OR \"Thripophaga\" OR \"Upucerthia\" OR \"Xenerpestes\" OR \"Xenops\" OR \"Xiphocolaptes\" OR \"Xiphorhynchus\" OR \"Grallaria\" OR \"Grallaricula\" OR \"Hylopezus\" OR \"Myrmothera\" OR \"Alopochelidon\" OR \"Atticora\" OR \"Cecropis\" OR \"Delichon\" OR \"Haplochelidon\" OR \"Hirundo\" OR \"Neochelidon\" OR \"Notiochelidon\" OR \"Orochelidon\" OR \"Petrochelidon\" OR \"Phedina\" OR \"Progne\" OR \"Psalidoprocne\" OR \"Pseudhirundo\" OR \"Pseudochelidon\" OR \"Ptyonoprogne\" OR \"Riparia\" OR \"Stelgidopteryx\" OR \"Tachycineta\" OR \"Hyliota\" OR \"Hypocolius\" OR \"Agelaioides\" OR \"Agelaius\" OR \"Agelasticus\" OR \"Amblycercus\" OR \"Amblyramphus\" OR \"Anumara\" OR \"Cacicus\" OR \"Chrysomus\" OR \"Curaeus\" OR \"Dives\" OR \"Dolichonyx\" OR \"Euphagus\" OR \"Gnorimopsar\" OR \"Gymnomystax\" OR \"Hypopyrrhus\" OR \"Icterus\" OR \"Lampropsar\" OR \"Leistes\" OR \"Macroagelaius\" OR \"Molothrus\" OR \"Nesopsar\" OR \"Oreopsar\" OR \"Psarocolius\" OR \"Pseudoleistes\" OR \"Quiscalus\" OR \"Sturnella\" OR \"Xanthocephalus\" OR \"Xanthopsar\" OR \"Icteria\" OR \"Ifrita\" OR \"Irena\" OR \"Corvinella\" OR \"Eurocephalus\" OR \"Lanius\" OR \"Actinodura\" OR \"Argya\" OR \"Garrulax\" OR \"Grammatoptila\" OR \"Heterophasia\" OR \"Ianthocincla\" OR \"Laniellus\" OR \"Leiothrix\" OR \"Liocichla\" OR \"Minla\" OR \"Pterorhinus\" OR \"Trochalopteron\" OR \"Turdoides\" OR \"Bradypterus\" OR \"Cincloramphus\" OR \"Helopsaltes\" OR \"Locustella\" OR \"Megalurus\" OR \"Poodytes\" OR \"Machaerirhynchus\" OR \"Graueria\" OR \"Hylia\" OR \"Macrosphenus\" OR \"Melocichla\" OR \"Sylvietta\" OR \"Chlorophoneus\" OR \"Dryoscopus\" OR \"Laniarius\" OR \"Malaconotus\" OR \"Nilaus\" OR \"Rhodophoneus\" OR \"Tchagra\" OR \"Telophorus\" OR \"Amytornis\" OR \"Chenorhamphus\" OR \"Clytomyias\" OR \"Malurus\" OR \"Stipiturus\" OR \"Melampitta\" OR \"Melanocharis\" OR \"Oedistoma\" OR \"Toxorhamphus\" OR \"Melanopareia\" OR \"Acanthagenys\" OR \"Acanthorhynchus\" OR \"Anthochaera\" OR \"Anthornis\" OR \"Caligavis\" OR \"Entomyzon\" OR \"Epthianura\" OR \"Glycifohia\" OR \"Gymnomyza\" OR \"Lichmera\" OR \"Manorina\" OR \"Melidectes\" OR \"Melilestes\" OR \"Meliphaga\" OR \"Melipotes\" OR \"Melithreptus\" OR \"Myzomela\" OR \"Nesoptilotis\" OR \"Philemon\" OR \"Phylidonyris\" OR \"Prosthemadera\" OR \"Ptiloprora\" OR \"Ptilotula\" OR \"Pycnopygius\" OR \"Timeliopsis\" OR \"Xanthotis\" OR \"Menura\" OR \"Allenia\" OR \"Cinclocerthia\" OR \"Dumetella\" OR \"Margarops\" OR \"Melanoptila\" OR \"Melanotis\" OR \"Mimus\" OR \"Oreoscoptes\" OR \"Ramphocinclus\" OR \"Toxostoma\" OR \"Lamprospiza\" OR \"Mitrospingus\" OR \"Moho\" OR \"Mohoua\" OR \"Arses\" OR \"Carterornis\" OR \"Clytorhynchus\" OR \"Grallina\" OR \"Hypothymis\" OR \"Monarcha\" OR \"Myiagra\" OR \"Symposiachrus\" OR \"Terpsiphone\" OR \"Trochocercus\" OR \"Anthus\" OR \"Macronyx\" OR \"Motacilla\" OR \"Alethe\" OR \"Anthipes\" OR \"Brachypteryx\" OR \"Calliope\" OR \"Campicoloides\" OR \"Cercotrichas\" OR \"Chamaetylas\" OR \"Copsychus\" OR \"Cossypha\" OR \"Cyanoptila\" OR \"Cyornis\" OR \"Enicurus\" OR \"Erithacus\" OR \"Eumyias\" OR \"Ficedula\" OR \"Fraseria\" OR \"Irania\" OR \"Larvivora\" OR \"Leonardina\" OR \"Luscinia\" OR \"Melaenornis\" OR \"Monticola\" OR \"Muscicapa\" OR \"Myiomela\" OR \"Myioparus\" OR \"Myophonus\" OR \"Myrmecocichla\" OR \"Niltava\" OR \"Oenanthe\" OR \"Phoenicurus\" OR \"Pogonocichla\" OR \"Saxicola\" OR \"Sheppardia\" OR \"Sholicola\" OR \"Stiphrornis\" OR \"Tarsiger\" OR \"Thamnolaea\" OR \"Vauriella\" OR \"Aethopyga\" OR \"Anabathmis\" OR \"Anthreptes\" OR \"Arachnothera\" OR \"Chalcomitra\" OR \"Cinnyris\" OR \"Cyanomitra\" OR \"Deleornis\" OR \"Hedydipna\" OR \"Kurochkinegramma\" OR \"Leptocoma\" OR \"Nectarinia\" OR \"Daphoenositta\" OR \"Nesospingus\" OR \"Nicator\" OR \"Notiomystis\" OR \"Aleadryas\" OR \"Oriolus\" OR \"Pitohui\" OR \"Sphecotheres\" OR \"Turnagra\" OR \"Colluricincla\" OR \"Falcunculus\" OR \"Melanorectes\" OR \"Pachycephala\" OR \"Pseudorectes\" OR \"Panurus\" OR \"Cicinnurus\" OR \"Diphyllodes\" OR \"Manucodia\" OR \"Paradisaea\" OR \"Ptiloris\" OR \"Paramythia\" OR \"Pardalotus\" OR \"Baeolophus\" OR \"Cephalopyrus\" OR \"Cyanistes\" OR \"Lophophanes\" OR \"Machlolophus\" OR \"Melaniparus\" OR \"Melanochlora\" OR \"Pardaliparus\" OR \"Parus\" OR \"Periparus\" OR \"Poecile\" OR \"Pseudopodoces\" OR \"Sittiparus\" OR \"Sylviparus\" OR \"Basileuterus\" OR \"Cardellina\" OR \"Catharopeza\" OR \"Dendroica\" OR \"Geothlypis\" OR \"Helmitheros\" OR \"Leiothlypis\" OR \"Limnothlypis\" OR \"Mniotilta\" OR \"Myioborus\" OR \"Myiothlypis\" OR \"Oporornis\" OR \"Oreothlypis\" OR \"Parkesia\" OR \"Protonotaria\" OR \"Seiurus\" OR \"Setophaga\" OR \"Vermivora\" OR \"Aimophila\" OR \"Ammodramus\" OR \"Amphispiza\" OR \"Arremon\" OR \"Arremonops\" OR \"Artemisiospiza\" OR \"Atlapetes\" OR \"Calamospiza\" OR \"Chlorospingus\" OR \"Chondestes\" OR \"Junco\" OR \"Melospiza\" OR \"Melozone\" OR \"Oreothraupis\" OR \"Oriturus\" OR \"Passerculus\" OR \"Passerella\" OR \"Peucaea\" OR \"Pezopetes\" OR \"Pipilo\" OR \"Pooecetes\" OR \"Pselliophorus\" OR \"Rhynchospiza\" OR \"Spizella\" OR \"Spizelloides\" OR \"Xenospiza\" OR \"Zonotrichia\" OR \"Carpospiza\" OR \"Gymnoris\" OR \"Hypocryptadius\" OR \"Montifringilla\" OR \"Onychostruthus\" OR \"Passer\" OR \"Petronia\" OR \"Pyrgilauda\" OR \"Alcippe\" OR \"Gampsorhynchus\" OR \"Illadopsis\" OR \"Jabouilleia\" OR \"Kenopia\" OR \"Laticilla\" OR \"Malacocincla\" OR \"Malacopteron\" OR \"Napothera\" OR \"Pellorneum\" OR \"Rimator\" OR \"Trichastoma\" OR \"Amalocichla\" OR \"Drymodes\" OR \"Eopsaltria\" OR \"Eugerygone\" OR \"Heteromyias\" OR \"Melanodryas\" OR \"Microeca\" OR \"Monachella\" OR \"Pachycephalopsis\" OR \"Peneoenanthe\" OR \"Peneothello\" OR \"Petroica\" OR \"Poecilodryas\" OR \"Tregellasia\" OR \"Peucedramus\" OR \"Microligea\" OR \"Phaenicophilus\" OR \"Xenoligea\" OR \"Phylloscopus\" OR \"Picathartes\" OR \"Antilophia\" OR \"Ceratopipra\" OR \"Chiroxiphia\" OR \"Chloropipo\" OR \"Corapipo\" OR \"Cryptopipo\" OR \"Heterocercus\" OR \"Ilicura\" OR \"Lepidothrix\" OR \"Machaeropterus\" OR \"Manacus\" OR \"Masius\" OR \"Neopelma\" OR \"Pipra\" OR \"Pseudopipra\" OR \"Tyranneutes\" OR \"Xenopipo\" OR \"Erythropitta\" OR \"Hydrornis\" OR \"Pitta\" OR \"Batis\" OR \"Platysteira\" OR \"Anaplectes\" OR \"Bubalornis\" OR \"Euplectes\" OR \"Malimbus\" OR \"Plocepasser\" OR \"Ploceus\" OR \"Quelea\" OR \"Sporopipes\" OR \"Pnoepyga\" OR \"Microbates\" OR \"Polioptila\" OR \"Ramphocaenus\" OR \"Garritornis\" OR \"Prunella\" OR \"Cinclosoma\" OR \"Ptilorrhoa\" OR \"Phainopepla\" OR \"Phainoptila\" OR \"Ptiliogonys\" OR \"Ailuroedus\" OR \"Amblyornis\" OR \"Ptilonorhynchus\" OR \"Sericulus\" OR \"Alophoixus\" OR \"Andropadus\" OR \"Arizelocichla\" OR \"Atimastillas\" OR \"Baeopogon\" OR \"Bleda\" OR \"Chlorocichla\" OR \"Criniger\" OR \"Eurillas\" OR \"Hemixos\" OR \"Hypsipetes\" OR \"Iole\" OR \"Ixos\" OR \"Neolestes\" OR \"Phyllastrephus\" OR \"Pycnonotus\" OR \"Spizixos\" OR \"Stelgidillas\" OR \"Tricholestes\" OR \"Regulus\" OR \"Anthoscopus\" OR \"Auriparus\" OR \"Remiz\" OR \"Rhagologus\" OR \"Eleoscytalopus\" OR \"Liosceles\" OR \"Psilorhamphus\" OR \"Pteroptochos\" OR \"Scelorchilus\" OR \"Scytalopus\" OR \"Teledromas\" OR \"Rhipidura\" OR \"Rhodinocichla\" OR \"Sapayoa\" OR \"Sitta\" OR \"Spindalis\" OR \"Chelidorhynx\" OR \"Culicicapa\" OR \"Elminia\" OR \"Acridotheres\" OR \"Agropsar\" OR \"Ampeliceps\" OR \"Aplonis\" OR \"Basilornis\" OR \"Cinnyricinclus\" OR \"Creatophora\" OR \"Gracula\" OR \"Gracupica\" OR \"Hartlaubius\" OR \"Hylopsar\" OR \"Lamprotornis\" OR \"Leucopsar\" OR \"Mino\" OR \"Notopholia\" OR \"Onychognathus\" OR \"Pastor\" OR \"Poeoptera\" OR \"Rhabdornis\" OR \"Sarcops\" OR \"Scissirostrum\" OR \"Speculipastor\" OR \"Spodiopsar\" OR \"Streptocitta\" OR \"Sturnia\" OR \"Sturnus\" OR \"Chamaea\" OR \"Chleuasicus\" OR \"Chloropeta\" OR \"Chrysomma\" OR \"Conostoma\" OR \"Fulvetta\" OR \"Lioparus\" OR \"Paradoxornis\" OR \"Pseudoalcippe\" OR \"Psittiparus\" OR \"Rhopophilus\" OR \"Sinosuthora\" OR \"Suthora\" OR \"Sylvia\" OR \"Teretistris\" OR \"Akletos\" OR \"Ampelornis\" OR \"Aprositornis\" OR \"Batara\" OR \"Cercomacra\" OR \"Cercomacroides\" OR \"Cymbilaimus\" OR \"Dichrozona\" OR \"Drymophila\" OR \"Dysithamnus\" OR \"Epinecrophylla\" OR \"Euchrepomis\" OR \"Formicivora\" OR \"Frederickena\" OR \"Gymnocichla\" OR \"Gymnopithys\" OR \"Hafferia\" OR \"Herpsilochmus\" OR \"Hylophylax\" OR \"Hypocnemis\" OR \"Hypocnemoides\" OR \"Hypoedaleus\" OR \"Isleria\" OR \"Mackenziaena\" OR \"Megastictus\" OR \"Microrhopias\" OR \"Myrmeciza\" OR \"Myrmelastes\" OR \"Myrmoborus\" OR \"Myrmochanes\" OR \"Myrmoderus\" OR \"Myrmophylax\" OR \"Myrmorchilus\" OR \"Myrmornis\" OR \"Myrmotherula\" OR \"Neoctantes\" OR \"Oneillornis\" OR \"Percnostola\" OR \"Phaenostictus\" OR \"Phlegopsis\" OR \"Pithys\" OR \"Poliocrania\" OR \"Pygiptila\" OR \"Pyriglena\" OR \"Rhegmatorhina\" OR \"Rhopias\" OR \"Rhopornis\" OR \"Sakesphorus\" OR \"Sciaphylax\" OR \"Sclateria\" OR \"Sipia\" OR \"Taraba\" OR \"Thamnistes\" OR \"Thamnomanes\" OR \"Thamnophilus\" OR \"Willisornis\" OR \"Xenornis\" OR \"Anisognathus\" OR \"Bangsia\" OR \"Buthraupis\" OR \"Calochaetes\" OR \"Catamblyrhynchus\" OR \"Catamenia\" OR \"Charitospiza\" OR \"Chlorochrysa\" OR \"Chlorophanes\" OR \"Chlorornis\" OR \"Chrysothlypis\" OR \"Cissopis\" OR \"Cnemoscopus\" OR \"Coereba\" OR \"Compsospiza\" OR \"Compsothraupis\" OR \"Conirostrum\" OR \"Conothraupis\" OR \"Coryphospingus\" OR \"Creurgops\" OR \"Cyanerpes\" OR \"Cyanicterus\" OR \"Cypsnagra\" OR \"Dacnis\" OR \"Delothraupis\" OR \"Diglossa\" OR \"Diuca\" OR \"Dolospingus\" OR \"Donacospiza\" OR \"Dubusia\" OR \"Emberizoides\" OR \"Embernagra\" OR \"Eucometis\" OR \"Euneornis\" OR \"Geospiza\" OR \"Gubernatrix\" OR \"Haplospiza\" OR \"Hemispingus\" OR \"Hemithraupis\" OR \"Heterospingus\" OR \"Incaspiza\" OR \"Iridophanes\" OR \"Iridosornis\" OR \"Lanio\" OR \"Lophospingus\" OR \"Loxigilla\" OR \"Loxipasser\" OR \"Melanodera\" OR \"Melanospiza\" OR \"Melopyrrha\" OR \"Nemosia\" OR \"Nephelornis\" OR \"Oreomanes\" OR \"Oryzoborus\" OR \"Parkerthraustes\" OR \"Paroaria\" OR \"Phrygilus\" OR \"Piezorina\" OR \"Pipraeidea\" OR \"Poospiza\" OR \"Pyrrhocoma\" OR \"Ramphocelus\" OR \"Rhodospingus\" OR \"Saltator\" OR \"Saltatricula\" OR \"Schistochlamys\" OR \"Sericossypha\" OR \"Sicalis\" OR \"Sporophila\" OR \"Stephanophorus\" OR \"Tachyphonus\" OR \"Tangara\" OR \"Tersina\" OR \"Thlypopsis\" OR \"Thraupis\" OR \"Tiaris\" OR \"Trichothraupis\" OR \"Volatinia\" OR \"Wetmorethraupis\" OR \"Xenodacnis\" OR \"Xenospingus\" OR \"Tichodroma\" OR \"Macronus\" OR \"Pomatorhinus\" OR \"Spelaeornis\" OR \"Stachyridopsis\" OR \"Stachyris\" OR \"Iodopleura\" OR \"Laniisoma\" OR \"Laniocera\" OR \"Myiobius\" OR \"Onychorhynchus\" OR \"Oxyruncus\" OR \"Pachyramphus\" OR \"Schiffornis\" OR \"Terenotriccus\" OR \"Tityra\" OR \"Xenopsaris\" OR \"Campylorhynchus\" OR \"Cantorchilus\" OR \"Catherpes\" OR \"Cinnycerthia\" OR \"Cistothorus\" OR \"Cyphorhinus\" OR \"Henicorhina\" OR \"Microcerculus\" OR \"Odontorchilus\" OR \"Pheugopedius\" OR \"Salpinctes\" OR \"Thryomanes\" OR \"Thryophilus\" OR \"Thryothorus\" OR \"Troglodytes\" OR \"Uropsila\" OR \"Catharus\" OR \"Cichlopsis\" OR \"Entomodestes\" OR \"Geokichla\" OR \"Hylocichla\" OR \"Ixoreus\" OR \"Myadestes\" OR \"Neocossyphus\" OR \"Ridgwayia\" OR \"Sialia\" OR \"Stizorhina\" OR \"Turdus\" OR \"Zoothera\" OR \"Agriornis\" OR \"Alectrurus\" OR \"Anairetes\" OR \"Aphanotriccus\" OR \"Arundinicola\" OR \"Atalotriccus\" OR \"Attila\" OR \"Camptostoma\" OR \"Capsiempis\" OR \"Casiornis\" OR \"Cnemarchus\" OR \"Cnemotriccus\" OR \"Cnipodectes\" OR \"Colonia\" OR \"Colorhamphus\" OR \"Conopias\" OR \"Contopus\" OR \"Corythopis\" OR \"Culicivora\" OR \"Deltarhynchus\" OR \"Elaenia\" OR \"Empidonax\" OR \"Empidonomus\" OR \"Euscarthmus\" OR \"Fluvicola\" OR \"Griseotyrannus\" OR \"Gubernetes\" OR \"Hemitriccus\" OR \"Heteroxolmis\" OR \"Hirundinea\" OR \"Hymenops\" OR \"Inezia\" OR \"Knipolegus\" OR \"Lathrotriccus\" OR \"Legatus\" OR \"Leptopogon\" OR \"Lessonia\" OR \"Lophotriccus\" OR \"Machetornis\" OR \"Mecocerculus\" OR \"Megarynchus\" OR \"Mionectes\" OR \"Mitrephanes\" OR \"Muscigralla\" OR \"Muscisaxicola\" OR \"Myiarchus\" OR \"Myiodynastes\" OR \"Myiopagis\" OR \"Myiophobus\" OR \"Myiornis\" OR \"Myiotheretes\" OR \"Myiotriccus\" OR \"Myiozetetes\" OR \"Neopipo\" OR \"Neoxolmis\" OR \"Nephelomyias\" OR \"Ochthoeca\" OR \"Ochthornis\" OR \"Oncostoma\" OR \"Ornithion\" OR \"Phaeomyias\" OR \"Philohydor\" OR \"Phyllomyias\" OR \"Phylloscartes\" OR \"Piprites\" OR \"Pitangus\" OR \"Platyrinchus\" OR \"Poecilotriccus\" OR \"Pogonotriccus\" OR \"Polioxolmis\" OR \"Polystictus\" OR \"Pseudelaenia\" OR \"Pseudocolopteryx\" OR \"Pseudotriccus\" OR \"Pyrocephalus\" OR \"Pyrrhomyias\" OR \"Ramphotrigon\" OR \"Rhynchocyclus\" OR \"Rhytipterna\" OR \"Satrapa\" OR \"Sayornis\" OR \"Serpophaga\" OR \"Silvicultrix\" OR \"Sirystes\" OR \"Stigmatura\" OR \"Sublegatus\" OR \"Suiriri\" OR \"Tachuris\" OR \"Taeniotriccus\" OR \"Todirostrum\" OR \"Tolmomyias\" OR \"Tumbezia\" OR \"Tyrannopsis\" OR \"Tyrannulus\" OR \"Tyrannus\" OR \"Uromyias\" OR \"Xenotriccus\" OR \"Xolmis\" OR \"Zimmerius\" OR \"Urocynchramus\" OR \"Artamella\" OR \"Calicalicus\" OR \"Cyanolanius\" OR \"Euryceros\" OR \"Falculea\" OR \"Hypositta\" OR \"Leptopterus\" OR \"Mystacornis\" OR \"Newtonia\" OR \"Oriolia\" OR \"Philentoma\" OR \"Prionops\" OR \"Pseudobias\" OR \"Schetba\" OR \"Tephrodornis\" OR \"Tylas\" OR \"Vanga\" OR \"Xenopirostris\" OR \"Anomalospiza\" OR \"Vidua\" OR \"Cyclarhis\" OR \"Erpornis\" OR \"Hylophilus\" OR \"Pteruthius\" OR \"Vireo\" OR \"Vireolanius\" OR \"Zeledonia\" OR \"Apalopteron\" OR \"Dasycrotapha\" OR \"Heleia\" OR \"Lophozosterops\" OR \"Sterrhoptilus\" OR \"Yuhina\" OR \"Zosterops\" OR \"Zosterornis\" OR \"Agamia\" OR \"Ardea\" OR \"Ardeola\" OR \"Botaurus\" OR \"Bubulcus\" OR \"Butorides\" OR \"Cochlearius\" OR \"Dupetor\" OR \"Egretta\" OR \"Gorsachius\" OR \"Ixobrychus\" OR \"Nyctanassa\" OR \"Nycticorax\" OR \"Pilherodius\" OR \"Syrigma\" OR \"Tigriornis\" OR \"Tigrisoma\" OR \"Zebrilus\" OR \"Balaeniceps\" OR \"Pelecanus\" OR \"Scopus\" OR \"Bostrychia\" OR \"Eudocimus\" OR \"Geronticus\" OR \"Lophotibis\" OR \"Mesembrinibis\" OR \"Nipponia\" OR \"Phimosus\" OR \"Platalea\" OR \"Plegadis\" OR \"Pseudibis\" OR \"Theristicus\" OR \"Threskiornis\" OR \"Phaethon\" OR \"Phoeniconaias\" OR \"Phoenicoparrus\" OR \"Phoenicopterus\" OR \"Bucco\" OR \"Chelidoptera\" OR \"Hapaloptila\" OR \"Hypnelus\" OR \"Malacoptila\" OR \"Micromonacha\" OR \"Monasa\" OR \"Nonnula\" OR \"Notharchus\" OR \"Nystalus\" OR \"Capito\" OR \"Eubucco\" OR \"Brachygalba\" OR \"Galbalcyrhynchus\" OR \"Galbula\" OR \"Jacamaralcyon\" OR \"Jacamerops\" OR \"Indicator\" OR \"Melichneutes\" OR \"Melignomon\" OR \"Prodotiscus\" OR \"Buccanodon\" OR \"Gymnobucco\" OR \"Lybius\" OR \"Pogoniulus\" OR \"Stactolaema\" OR \"Trachyphonus\" OR \"Psilopogon\" OR \"Blythipicus\" OR \"Campephilus\" OR \"Campethera\" OR \"Celeus\" OR \"Chloropicus\" OR \"Chrysocolaptes\" OR \"Chrysophlegma\" OR \"Colaptes\" OR \"Dendrocopos\" OR \"Dendrocoptes\" OR \"Dendropicos\" OR \"Dinopium\" OR \"Dryobates\" OR \"Dryocopus\" OR \"Gecinulus\" OR \"Geocolaptes\" OR \"Jynx\" OR \"Leiopicus\" OR \"Leuconotopicus\" OR \"Meiglyptes\" OR \"Melanerpes\" OR \"Micropternus\" OR \"Mulleripicus\" OR \"Nesoctites\" OR \"Picoides\" OR \"Piculus\" OR \"Picumnus\" OR \"Picus\" OR \"Reinwardtipicus\" OR \"Sasia\" OR \"Sphyrapicus\" OR \"Veniliornis\" OR \"Yungipicus\" OR \"Andigena\" OR \"Aulacorhynchus\" OR \"Pteroglossus\" OR \"Ramphastos\" OR \"Selenidera\" OR \"Semnornis\" OR \"Aechmophorus\" OR \"Podiceps\" OR \"Podilymbus\" OR \"Poliocephalus\" OR \"Rollandia\" OR \"Tachybaptus\" OR \"Diomedea\" OR \"Phoebastria\" OR \"Phoebetria\" OR \"Thalassarche\" OR \"Hydrobates\" OR \"Oceanodroma\" OR \"Fregetta\" OR \"Garrodia\" OR \"Nesofregetta\" OR \"Oceanites\" OR \"Pelagodroma\" OR \"Aphrodroma\" OR \"Ardenna\" OR \"Bulweria\" OR \"Calonectris\" OR \"Daption\" OR \"Fulmarus\" OR \"Halobaena\" OR \"Macronectes\" OR \"Pachyptila\" OR \"Pagodroma\" OR \"Pelecanoides\" OR \"Procellaria\" OR \"Pseudobulweria\" OR \"Pterodroma\" OR \"Puffinus\" OR \"Thalassoica\" OR \"Cacatua\" OR \"Callocephalon\" OR \"Calyptorhynchus\" OR \"Eolophus\" OR \"Lophochroa\" OR \"Nymphicus\" OR \"Probosciger\" OR \"Alipiopsitta\" OR \"Amazona\" OR \"Anodorhynchus\" OR \"Ara\" OR \"Aratinga\" OR \"Bolborhynchus\" OR \"Brotogeris\" OR \"Conuropsis\" OR \"Cyanoliseus\" OR \"Cyanopsitta\" OR \"Deroptyus\" OR \"Diopsittaca\" OR \"Enicognathus\" OR \"Eupsittula\" OR \"Forpus\" OR \"Graydidascalus\" OR \"Guarouba\" OR \"Guaruba\" OR \"Hapalopsittaca\" OR \"Leptosittaca\" OR \"Myiopsitta\" OR \"Nannopsittaca\" OR \"Orthopsittaca\" OR \"Pionites\" OR \"Pionopsitta\" OR \"Pionus\" OR \"Poicephalus\" OR \"Primolius\" OR \"Psilopsiagon\" OR \"Psittacara\" OR \"Psittacus\" OR \"Pyrilia\" OR \"Pyrrhura\" OR \"Rhynchopsitta\" OR \"Thectocercus\" OR \"Touit\" OR \"Triclaria\" OR \"Agapornis\" OR \"Alisterus\" OR \"Aprosmictus\" OR \"Barnardius\" OR \"Bolbopsittacus\" OR \"Chalcopsitta\" OR \"Charmosyna\" OR \"Coracopsis\" OR \"Cyanoramphus\" OR \"Cyclopsitta\" OR \"Eclectus\" OR \"Eos\" OR \"Eunymphicus\" OR \"Geoffroyus\" OR \"Glossopsitta\" OR \"Lathamus\" OR \"Loriculus\" OR \"Lorius\" OR \"Melopsittacus\" OR \"Micropsitta\" OR \"Neophema\" OR \"Neopsephotus\" OR \"Neopsittacus\" OR \"Northiella\" OR \"Oreopsittacus\" OR \"Parvipsitta\" OR \"Pezoporus\" OR \"Phigys\" OR \"Platycercus\" OR \"Polytelis\" OR \"Prioniturus\" OR \"Prosopeia\" OR \"Psephotellus\" OR \"Psephotus\" OR \"Pseudeos\" OR \"Psittacella\" OR \"Psittacula\" OR \"Psittaculirostris\" OR \"Psitteuteles\" OR \"Psittinus\" OR \"Psittrichas\" OR \"Purpureicephalus\" OR \"Tanygnathus\" OR \"Trichoglossus\" OR \"Vini\" OR \"Nestor\" OR \"Strigops\" OR \"Pterocles\" OR \"Syrrhaptes\" OR \"Rhea\" OR \"Aptenodytes\" OR \"Eudyptes\" OR \"Eudyptula\" OR \"Megadyptes\" OR \"Pygoscelis\" OR \"Spheniscus\" OR \"Aegolius\" OR \"Asio\" OR \"Athene\" OR \"Bubo\" OR \"Glaucidium\" OR \"Ketupa\" OR \"Lophostrix\" OR \"Megascops\" OR \"Micrathene\" OR \"Ninox\" OR \"Otus\" OR \"Pseudoscops\" OR \"Psiloscops\" OR \"Pulsatrix\" OR \"Sceloglaux\" OR \"Scotopelia\" OR \"Strix\" OR \"Surnia\" OR \"Xenoglaux\" OR \"Phodilus\" OR \"Tyto\" OR \"Aepyornis\" OR \"Mullerornis\" OR \"Struthio\" OR \"Anhinga\" OR \"Fregata\" OR \"Leucocarbo\" OR \"Microcarbo\" OR \"Nannopterum\" OR \"Phalacrocorax\" OR \"Morus\" OR \"Sula\" OR \"Crypturellus\" OR \"Eudromia\" OR \"Nothocercus\" OR \"Nothoprocta\" OR \"Nothura\" OR \"Rhynchotus\" OR \"Tinamotis\" OR \"Tinamus\" OR \"Apalharpactes\" OR \"Apaloderma\" OR \"Harpactes\" OR \"Pharomachrus\" OR \"Trogon\" OR \"Tetrastes\" OR \"Hesperiphona\") AND (\"experiment\\*\" OR \"manipulat\\*\") ))\\>\n\nComplete search string for the systematic search\n:::\n\n::: {#figsupp-decision-tree}\n![](images/Decision_Tree_updated.png)\n:::\n\n::: {#figsupp-prisma-flowchart}\nThis is the prisma flowchart\n:::\n\n::: {#figsupp-correlation}\nTable for different values of correlation\n:::\n\n::: {#figsupp-MLMA-excluded}\nModel output and plot including proxies that were excluded\n:::\n\n\n\n</details>\n",
    "supporting": [
      "manuscript_GNM_files/figure-docx"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}